### ISSUE TITLE
Test failure on SequenceToolsTest$PermuteCyclic.permuteCyclicPerformance on biojava-core subproject

### ISSUE THREAD

**Issue by jlerbsc** [biojava/biojava#1008]
On the latest release there is a test failure on biojava-core subproject. It seems to be caused by the improvement factor which is below the threshold (5).
> [ERROR] Failures: 
[ERROR]   SequenceToolsTest$PermuteCyclic.permuteCyclicPerformance:77 expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 428, Failures: 1, Errors: 0, Skipped: 8

System.err

> 229
89

**Comment by richarda23** [comment]
I originally added permuteCyclic2 as a more robust and simpler method than permuteCyclic, without breaking backwards compatibility, and this performance test was mainly to show that it performed better as well. The 5x speed-up is not a hard requirement. Perhaps it would suffice to have a test showing it didn't perform worse. Alternatively, we could just replace the implementation of permuteCyclic with that of permuteCyclic2 and avoid the need for performance comparison test altogether.
