### ISSUE TITLE
Calculating Ramachandran Angles from a PDB File

### ISSUE THREAD

**Issue by LobsterMan123** [biojava/biojava#1028]
Would someone please tell me if BioJava can calculate Ramachandran angles for amino acids found in a PDB file (prefferably a PDB file that contains multiple "snapshots" of different conformations of the protein in question such as is found in PDB files from NMR experiments)?

**Comment by josemduarte** [comment]
Absolutely it can, but you need to write some code to calculate the torsion angles. See this old piece of code that does it with another library different from BioJava. Adapting it to BioJava should be pretty straight forward.

https://github.com/eppic-team/owl/blob/78bb383cab0620c475bef36799c6608681065318/src/main/java/owl/core/structure/PdbChain.java#L2932-L2955

For the basics on how to parse a PDBx/mmCIF file see for instance this demo script included in biojava-structure: https://github.com/biojava/biojava/blob/master/biojava-structure/src/main/java/demo/DemoContacts.java

**Comment by josemduarte** [comment]
Correction, torsion angle calculation is already available in biojava, see https://github.com/biojava/biojava/blob/89a40ff2d477c58a40db4f90c2db557070ab607c/biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java#L242

and for psi/phi angles:
https://github.com/biojava/biojava/blob/89a40ff2d477c58a40db4f90c2db557070ab607c/biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java#L308

https://github.com/biojava/biojava/blob/89a40ff2d477c58a40db4f90c2db557070ab607c/biojava-structure/src/main/java/org/biojava/nbio/structure/Calc.java#L275

**Comment by LobsterMan123** [comment]
Thank you for this.  For the BioJava one (the most recent one you sent me), would you please tell me if there is a tutorial on how to use this (I couldn't find anything in the online tutorial docs for using the feature to calculate Ramachandran angles)?  Do I need to modify the code in these links for the BioJava one in order to use it in my own programs to calculate Ramachandran angles?

Also, can these codes be used in a headless environment without the GUI?

Thanks again.

**Comment by emckee2006** [comment]
Yes, you can use it headless.

You would read in your structure, like in the tutorial, and then loop over
the amino acids in your chain calling compute phi and compute psi for each
successive pair.

Something like this pseudocode:

Bool first = true;
Residue previous residue;
For residue in chain {
  If !first {
    Double phi = calcphi(residue, previous residue)
    Double psi = calculatepsi(residue previous residue);
  }
  First = false;
  Previous residue = residue;
}
