### ISSUE TITLE
New release based on Java 11

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#1035]
I'd like to propose that we make our first Java 11 release and call it 6.1.0. That will mean that BioJava won't be possible to use under a JRE 8 from that moment on. 

Is there anything against that?

**Comment by emckee2006** [comment]
If there any reason we should drop java 8 support?

**Comment by heuermh** [comment]
+1 from me

**Comment by aalhossary** [comment]
I support the idea in principle. But I prefer deferring the dependency change only to be in synchrony with the next big structural change (i.e. BioJava 7.0).

**Comment by emckee2006** [comment]
As long as the library supports the newer java versions, then I guess my
question would be better framed as: why remove java compatibility if it's
not necessary?

**Comment by josemduarte** [comment]
See some reasons in the post I linked above. For instance this point:

> using an old software stack can severely limit your selection of useful third-party libraries and/or tools. A given library that you really need might require a more recent Java version or (possibly even worse) a library that you already use increases it's Java version requirement with a new major release (leaving you stuck with an old Java version and an old software version that might be missing important bug fixes).

This is a very real concern for us. Some libraries that we depend on have moved to java 11.

**Comment by josemduarte** [comment]
Ok given the discussion here it seems prudent to use `7.0.0` for the new version. I will change the milestone.

`6.1.0` will be the next release, still based on java 8 with a few fixes and additions.

**Comment by aalhossary** [comment]
@josemduarte When is 7.0.0 expected?
I have one or two open pull requests that I couldn't handle yet because of the pressure of my new work.

**Comment by josemduarte** [comment]
It's not specially urgent but at the same time I don't want to leave the problem open for too long. I'll propose to do the release no later than the end of January 2023. I'll set that date in the milestone.

**Comment by josemduarte** [comment]
A reminder to everyone that tomorrow is the date set for the 7.0.0 (java 11 based) release. I'll be merging PRs and producing the release tomorrow.

**Comment by aalhossary** [comment]
@josemduarte Thank you for the reminder.
It seems that #993 will not catch BioJava 7.0.0.
Let's continue the discussion stress-free from the time constraint and aim at a better comprehensive redesign of the interfaces by BioJava 7.5 or 8.0 (whichever comes first).

**Comment by josemduarte** [comment]
BioJava 7.0.0 is out now
