### ISSUE TITLE
Aromaticity calculation (Protein)

### ISSUE THREAD

**Issue by simoesrenato** [biojava/biojava#1037]
This feature calculates the aromaticity value of a protein according to Lobry, 1994. It is simply the relative frequency of Phe+Trp+Tyr.

**Comment by josemduarte** [comment]
Thanks for creating the issue. I can see the commit that mentions it. Did you mean perhaps to create a pull request?

**Comment by simoesrenato** [comment]
Hi Jose, I really think it could have been a pull request, is it possible to do this merge or do I submit again?

**Comment by josemduarte** [comment]
I don't think there's a pull request yet. You will need to create one from your fork.

See [some docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) if you need help.
