### ISSUE TITLE
Q: How can I print the 3-letter protein sequence?

### ISSUE THREAD

**Issue by DominantDuck** [biojava/biojava#1048]
I am creating a simple DNA to Protein Converter; I am utilizing the Protein Sequence class to do so. However, I get a single-letter protein sequence, rather than a triple-letter protein sequence. In other words I want "Pro" rather than "P."

Here is a section of the classes I am using:

```
proSeq = rnaSeq.getProteinSequence();
        String printPro = proSeq.getSequenceAsString();
        printPro = printPro.toUpperCase();


        System.out.println("Protein: " + printPro);

```
Here is the output:
```
Enter DNA sequence: 
CCTTGGGGAATATCTTCGATGAATCCGTACACGCTGGACGGTACTCGCC
mRNA: CCUUGGGGAAUAUCUUCGAUGAAUCCGUACACGCUGGACGGUACUCGCC
Protein: PWGISSMNPYTLDGTR
```

**Comment by DominantDuck** [comment]
**Utilize Array:**

`String[][] aminoAcids = {
                {"A", "Ala"},
                {"R", "Arg"},
                {"N", "Asn"},
                {"D", "Asp"},
                {"C", "Cys"},
                {"E", "Glu"},
                {"Q", "Gln"},
                {"G", "Gly"},
                {"H", "His"},
                {"I", "Ile"},
                {"L", "Leu"},
                {"K", "Lys"},
                {"M", "Met"},
                {"F", "Phe"},
                {"P", "Pro"},
                {"S", "Ser"},
                {"T", "Thr"},
                {"W", "Trp"},
                {"Y", "Tyr"},
                {"V", "Val"}
 };
`


**Run for-loop:**

        StringBuilder proteinBuilder = new StringBuilder();
        boolean stopFound = false;

        for (int i = 0; i < printPro.length(); i++) {
            char singleLetterName = printPro.charAt(i);
            for (int j = 0; j < aminoAcids.length; j++) {
                if (aminoAcids[j][0].charAt(0) == singleLetterName) {
                    proteinBuilder.append(aminoAcids[j][1]);
                    proteinBuilder.append(" ");
                    break;
                }
                if (printPro.charAt(i) == '*') {
                    proteinBuilder.append("STOP");
                    proteinBuilder.append(" ");
                    stopFound = true;
                    break;
                }
            }
            if (stopFound == true) {
                break;
            }
        }

        String result = proteinBuilder.toString();

**Comment by aalhossary** [comment]
@DominantDuck Why don't you simply use
`org.biojava.nbio.structure.chem.ChemCompTools.getAminoThreeLetter(Character)`?
Please check [here](https://biojava.org/docs/api/org/biojava/nbio/structure/chem/ChemCompTools.html#getAminoThreeLetter(java.lang.Character)).
Also check [here](https://biojava.org/docs/api/org/biojava/nbio/genome/util/ProteinMappingTools.html), please.

These should reduce your code down to 2 lines.

**Comment by aalhossary** [comment]
Answered within my comment.
If you have any questions, please reopen it.
