### ISSUE TITLE
GenBank export producing spurious %n

### ISSUE THREAD

**Issue by sjaenick** [biojava/biojava#1069]
Hi,

I'm having some problems here trying to write genomic data to Genbank format with a
`GenbankWriter<DNASequence, NucleotideCompound>` instance; instead of proper
line breaks in the Genbank header and list of features, I end up with `%n` instead of
`\n` as proper line ends. 

This is caused by https://github.com/biojava/biojava/blob/master/biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericGenbankHeaderFormat.java#L40 and https://github.com/biojava/biojava/blob/master/biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/GenericInsdcHeaderFormat.java#L52

I was able to circumvent this by copying all required methods (since they are private) and replacing
the `lineSep` with `\n`, but this obviously isn't the right way to go.

Biojava version is 7.0.2.

Any ideas?

**Comment by josemduarte** [comment]
That is likely a bug. With an easy fix. Simply replace the value of the `lineSep` constant from `%n` to `System.lineSeparator()`. I'll create a PR
