### ISSUE TITLE
New release based on Java 17

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [biojava/biojava#1071]
Is biojava ready to support java17? If not what is the plan to migrate it to java17?

Thanks for maintaining this awesome library. It is really helpful.

**Comment by josemduarte** [comment]
The latest BioJava should work under JRE 17. Though it is compiled at Java 11 compatibility level (since 7.0.0). Compiling at Java 17 level will be something that will come later and will take some time. Following recent convention we'd want to bump the major version for that change.
