### ISSUE TITLE
For your information, code remediation via indepth-cli is completely free for open source projects

### ISSUE THREAD

**Issue by jlerbsc** [biojava/biojava#1072]
We suggested code changes corresponding to defects listed by SonarQube.

https://github.com/biojava/biojava/pull/1067
https://github.com/biojava/biojava/pull/1065
https://github.com/biojava/biojava/pull/1062
https://github.com/biojava/biojava/pull/1052

Today we offer all Open source projects the opportunity to use our solution for free, to detect and correct issues in your project yourself. Everything you need to do is explained here https://github.com/javaperf-consulting/indepth

We hope this solution can help you improve the quality of your solution.

Please share your suggestions/comments to help us improve indepth-cli.

**Comment by tejdnk-2019-ShortNotes** [comment]
OK

**Comment by jlerbsc** [comment]
We also noticed that you had 100 violations of the "logging arguments should not require evaluation" rule. This violation is important because it could cause performance problems related to the concatenation of character strings in the logs. You will find detailed explanations on this page (https://rules.sonarsource.com/java/RSPEC-2629/).

Below is a snippet of the type of correction that our solution can provide in this case.

> org\biojava\nbio\structure\xtal\CrystalBuilder.java
@@ -281,5  +281,5 @@
			int auTrials = (numPolyChainsAu*(numPolyChainsAu-1))/2;
			int trials = numPolyChainsAu*numOperatorsSg*numPolyChainsAu*neighbors;
\-			logger.debug("Chain clash trials within original AU: "+auTrials);
\+			logger.debug("Chain clash trials within original AU: {}", auTrials);

Furthermore, Sonar estimates the average correction time for a fault of this type to be 5 minutes. In your case it would take about 8 hours of hard work to complete it. With Indepth it will only take you a few minutes if we consider the time needed to initialize your project in our solution.
Improving the quality of your Java source code has never been easier, faster and more efficient.

**Comment by josemduarte** [comment]
Closing because this is not an issue.
