### ISSUE TITLE
Biojava core tests fail on Windows

### ISSUE THREAD

**Issue by jlerbsc** [biojava/biojava#1092]
Tests fail with the following errors

    [ERROR] Errors:
    [ERROR] FastaStreamerTest.iterate:43 " InvalidPath Illegal char <:> at index 2: /D:/de...
    [ERROR] FastaStreamerTest.stream:21 " InvalidPath Illegal char <:> at index 2: /D:/dev...

**Comment by josemduarte** [comment]
@hilbertglm I think this came in your recent PR: #1080 . Could you have a look?

**Comment by josemduarte** [comment]
In order to prevent this in the future, I've added windows to the OS list to test in github workflows for Pull Requests. See 4fcb3b1b
