### ISSUE TITLE
Improve BioJava cloud support

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#124]
Hadoop-ify and/or Map-Reduce some of the BioJava modules.

_Suggested for [GSoC 2012](http://biojava.org/wiki/Google_Summer_of_Code_2012)_

**Comment by timrcoulson** [comment]
Hi Spencer,
Is this still open? I'm keen to make a contribution to this project.
Thanks,
Tim

**Comment by phidias51** [comment]
You might take a look at Apache Spark. It was designed to address some of
the performance issues with map-reduce.

Mark

**Comment by josemduarte** [comment]
@phidias51  I agree, Spark sounds like a great idea

@timrcoulson I'm sure the issue is still open. To my knowledge there hasn't been any attempts to map-reduce anything in Biojava. I'm not sure what @sbliven had in mind exactly but I would guess that something like the all-to-all structural alignments would be a good candidate to map-reduce

**Comment by pwrose** [comment]
Have a look at our QuickStructureSearch project which is currently under
construction:
https://github.com/rcsb/QuickStructureSearch

It uses Spark for structural alignments. The input is a Hadoop Sequence
file with CA coordinates only for fast processing.

This is work in progress, but it's an example of using Spark for structural
alignment tasks.

-Peter

On Tue, Apr 21, 2015 at 6:15 PM, Jose Manuel Duarte <
notifications@github.com> wrote:

> @phidias51 <https://github.com/phidias51> I agree, Spark sounds like a
> great idea
>
> @timrcoulson <https://github.com/timrcoulson> I'm sure the issue is still
> open. To my knowledge there hasn't been any attempts to map-reduce anything
> in Biojava. I'm not sure what @sbliven <https://github.com/sbliven> had
> in mind exactly but I would guess that something like the all-to-all
> structural alignments would be a good candidate to map-reduce
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biojava/biojava/issues/124#issuecomment-94716086>.
>



-- 
Peter Rose, Ph.D.
Site Head, RCSB Protein Data Bank West (http://www.rcsb.org)
San Diego Supercomputer Center (http://bioinformatics.sdsc.edu)
University of California, San Diego
+1-858-822-5497

**Comment by phidias51** [comment]
Very cool, Peter.  Thanks for the heads up.

Cheers,

Mark

**Comment by sbliven** [comment]
I feel like this is most likely going to be implemented as a layer on top of BioJava. Should we close it?
