### ISSUE TITLE
Improve structural alignment datastructures

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#126]
BioJava contains a number of algorithms for aligning protein structures. In the most general case, an alignment consists of a mapping between residues of two (or more) proteins. However, for historical and performance reasons alignments are stored as linear, sorted arrays. This makes it difficult to express cases where the order of aligned residues differs between the two proteins. For instance, storing the following alignment requires some creative work-arounds:

     123456
     456123

Additionally, the class to store structural alignments (AFPChain) contains a number of unneccessary, poorly documented, or algorithm-specific parameters which should be removed or refactored.

AFPChain should be refactored into a new data structure that
*    Is flexible enough to store topology-independent alignments
*    Efficiently utilizes memory
*    Has good performance for common tasks 
* Works for rigid body, flexible, and local structural alignments
* Maintains consistency when modified

_Suggested for [GSoC 2013](http://biojava.org/wiki/Google_Summer_of_Code_2013)_

**Comment by lafita** [comment]
This should have been closed when the MultipleAlignment Data Structure (to store multiple structural alignments) was merged #278.
