### ISSUE TITLE
Whitespace padding of atom names in mmCIF files

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#148]
What's the proper way to deal with atom names? For PDB files we are careful to treat them as 4-character strings and to include whitespace in all checks (eg alpha-carbon " CA " is different from calcium "CA  "). HetatomImpl even keeps separate dictionaries of the trimmed and untrimmed names for accessing atoms. However, in mmCIF the atom names are always left justified, rather than using quoting to preserve the spaces. So calcium and alpha carbon can only be distinguished by comparing the element.

This bug was exposed by 41d53c3, which results in `TestAltLocs.test3PIUmmcif()` failing despite `test3PIUpdb` passing. Basically, the mmcif has "CA  " atoms, which are matched to alpha carbons in some contexts but not others.

Are there any reasons to store the 4-letter version besides outputting PDB files? We need to use the correct justification when writing PDB files, but internally it should be whitespace insensitive, right? Could we store the trimmed version, and only generate the whitespace version in toPDB based on a lookup table for each element?

**Comment by andreasprlic** [comment]
So I don't think this is working fully right now. This breaks some of the functionality in HetatomImpl. In particular hasAtom will be broken for groups containing Calcium atoms, because they will overwrite c-alpha atoms in addAtom, if the Calciums come later in the file (which they usually do).

**Comment by andreasprlic** [comment]
sorry, mistakenly re-opened.

**Comment by josemduarte** [comment]
That's indeed an issue, which we discussed already some time ago in #175. 

As already discussed there, fixing it requires a new method `getAtom(String, Element)` which would be more precise than just `getAtom(String)` (the javadoc of `Group.getAtom(String)` also explains the issue). 

In any case this really calls for removing the lookup HashMap in `HetatomImpl` as discussed in #391. It really gives very little speed-up in expense of quite some memory. This atom name ambiguity issue is another indication that it's not useful.
