### ISSUE TITLE
Use SLF4J for logging

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#155]
I believe we reached a consensus on the mailing list to use slf4j for logging, due to its easy interoperability with other logging frameworks.

>The “beauty" of slf4j is that it provides a logging framework that doesn’t impose any downstream restrictions or requirements and will actually insulate users from logging dependencies that come from other third-party libraries that you may include. It allows the end user to include the logging framework of their choice, defaulting to a NOP version if none is specified.
> -- Andy Law, biojava-dev list, May 25, 2014

Todo:
* Create a usage policy & documentation (http://www.biojava.org/wiki/BioJava3_logging)
* Add slf4j & an implementation to the pom file
* Change any existing uses of java.util.logging to use slf4j (there shouldn't be ~~any~~ many of these)
* Convert println/printStackTrace statements to logger calls

This would be a great project for someone trying to start contributing to BioJava.

**Comment by sbliven** [comment]
How about now, @josemduarte? Logging doesn't change the API, so it can easily go out in patch commits.

**Comment by josemduarte** [comment]
Yep let's close it, I think the logging coverage now is quite decent. Surely there must be some other places with missing logging but we can add more commits later

**Comment by dmyersturnbull** [comment]
Re-opening this for now so that I can reference it in commits.

**Comment by sbliven** [comment]
Can't you reference a closed issue? jose's commits seem to have been picked up after it closed.

**Comment by dmyersturnbull** [comment]
Yes, apparently I can! (I didn't know.)
