### ISSUE TITLE
Large mmCif structures

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#156]
How are we doing on parsing the large mmCif files from the pdb (ftp://ftp.wwpdb.org/pub/pdb/data/large_structures/mmCIF/)?

I did some tests on 4v51, and the mmCif parser is able to read all the atoms. There are a few fields we don't support:
```
Trying to set field pdbx_src_id in org.biojava.bio.structure.io.mmcif.model.EntitySrcNat, but not found! (value:1)
Trying to set field pdbx_alt_source_flag in org.biojava.bio.structure.io.mmcif.model.EntitySrcNat, but not found! (value:?)
Trying to set field pdbx_beg_seq_num in org.biojava.bio.structure.io.mmcif.model.EntitySrcNat, but not found! (value:?)
Trying to set field pdbx_end_seq_num in org.biojava.bio.structure.io.mmcif.model.EntitySrcNat, but not found! (value:?)
Trying to set field pdbx_leaving_atom_flag in org.biojava.bio.structure.io.mmcif.model.StructConn, but not found! (value:?)
```

I'm pretty sure that large structures break assumptions in some of the analysis code. For instance, two-letter chains aren't going to work in AtomCache (e.g. getStructure("4v51.HD")), but I haven't written tests for this.

**Comment by sbliven** [comment]
Since 4-letter chains work (#67), I'm going to close this. If any more specific problem emerge we can open new issues for them.

**Comment by pwrose** [comment]
I haven't checked, but does StructureIO support the syntax: 1XYZ.ABC for
example to load a single chain?

**Comment by sbliven** [comment]
@pwrose No, `StructureName` specifically checks for 6-character strings. I'll add a new issue for this.
