### ISSUE TITLE
Improve responsiveness of structure alignment database searches

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#196]
Database searches are very slow, but this is not well communicated to the user. The progress bar should show progress downloading structures and running jobs. Some text output would also be nice ('Downloading 4hhb (57/40000)', 'Running d4hhba_ (57/40000)', etc).

Downloading PDB files individually also seems inefficient, and should at least be done in parallel.

PDP domain definitions should be calculated locally, like the local ScopInstallation.

Finally, the calculation time printed at the end is totally misleading. My run printed 'Calculation took : 2388 sec.' after running for several days with 8 cpu. This seems to be the real time elapsed between  submitting the last job and finishing, which is completely misleading. Better would be either the total elapsed time since starting (34 hours, including downloads), or the total calculation time (11946 seconds, by summing the 'time' field in each individual alignment).

**Comment by josemduarte** [comment]
I think this was relying in RCSB's legacy services that are deprecated now. I'll close.
