### ISSUE TITLE
BiojavaJmol transmits structures naively

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#201]
BiojavaJmol transmits structures to Jmol by converting them to a PDB string. This is very simplistic and limits some features:
* Unit cells don't display, since the header records get stripped out, including crystal information
* large structures are going to break, since they don't have a PDB representation (#156)

**Comment by lafita** [comment]
Another problem has popped up: with the current communication it is impossible to display two (or more) aligned *Biological Assemblies*, since the **symmetry generated chains** are also stored in different models. See #220 for a more detailed description of the problem.

**Comment by sbliven** [comment]
Officially solved with #569.

**Comment by andreasprlic** [comment]
great!
