### ISSUE TITLE
Resolve TODOs or remove them

### ISSUE THREAD

**Issue by dmyersturnbull** [biojava/biojava#216]
There are lots of TODO comments in biojava-structure. Some probably no longer apply, but some are concerning because they're in really deep/fundamental parts of the API.
StructureImpl.clone contains this: //TODO: do deep copying of data!

These should all be either resolved or removed. Since many would involve interface changes, Biojava 4.0 (or 5.0?) is the best release to do this.

**Comment by andreasprlic** [comment]
This should not prevent us from making the 4.0.0 release soon. all developers, please fix TODO abuses as you encounter them.
