### ISSUE TITLE
Drop support for non-split PDB directories

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#225]
Following #181 we use a heirarchical directory structure for storing PDB files, e.g. `PDB_DIR/data/structures/divided/mmCIF/xx/1xx0.cif.gz`. But we still have an isSplit flag, which controls whether it is written to the `divided/mmCIF/xx/` or the `all/mmCIF/` directory.

I don't see any use cases where you would prefer the `data/.../all/...` directory. I suggest we remove the isSplit option from StructureIOFile implementations and AtomCache.

**Comment by sbliven** [comment]
One usecase I *can* see is that for storing all files directly in `PDB_DIR`. For instance, PyMOL downloads files to a flat directory (which I make the same as PDB_DIR), so that would reduce redundant downloads between the two programs.

A more complete (and complex) solution would be to replace the isSplit boolean with an enum of various preferred directory layouts:

```java
public enum PDBDirectoryLayout {
  HEIRARCHICAL_SPLIT, // use PDB_DIR/data/.../divided/.../xx
  HEIRARCHICAL_ALL, // use PDB_DIR/data/.../all/...
  FLAT_SPLIT, // use PDB_DIR/xx
  FLAT_ALL; // use PDB_DIR/ for everything
}
```

This would be pretty straightforward to implement if anyone thinks it would be useful. Note that the FLAT_ALL option would also put obsolete files, biological assemblies, chemical components, etc. directly in PDB_DIR.

**Comment by pwrose** [comment]
+1 from me.
