### ISSUE TITLE
Bioassembly handling for entries with highly symmetric AUs (mostly viral capsid proteins)

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#230]
PDB entries with highly symmetric AUs, i.e. those containing MTRIX/struct_ncs_oper records, have special bioassembly annotations in the mmCIF format (but not in PDB format!), e.g. 1ei7:

```
loop_
_pdbx_struct_assembly.id 
_pdbx_struct_assembly.details 
_pdbx_struct_assembly.oligomeric_details 
_pdbx_struct_assembly.oligomeric_count 
_pdbx_struct_assembly.method_details 
1   'complete point assembly'                 68-MERIC 68 ? 
2   'point asymmetric unit'                   ?        ?  ? 
PAU 'point asymmetric  unit, std point frame' ?        ?  ? 
XAU 'crystal asymmetric unit'                 ?        ?  ? 
```
While the corresponding REMARK 350 in the PDB file contains only the id=1 annotation. Actually in those 4 assemblies the only one referring to an actual biological assembly is 1. The others are more related to reconstruction of the crystal or parts thereof.

This annotation is different from the standard biounit annotation found in normal files, usually it looks more like:

```
_pdbx_struct_assembly.id                   1 
_pdbx_struct_assembly.details              author_and_software_defined_assembly 
_pdbx_struct_assembly.method_details       PISA,PQS 
_pdbx_struct_assembly.oligomeric_details   dimeric 
_pdbx_struct_assembly.oligomeric_count     2 
```

At the moment the Biojava code dealing with this has been made to understand all possible ids 1,2,... but also "PAU" or "XAU". I would rather discard those assembly ids altogether and only take those that: a) are numerical and b) have an oligomeric_count value.

Like that, the biojava biological assembly code would deal strictly with biological assemblies and not with crystal reconstruction, which is a separate issue. We do actually have some code already for crystal reconstruction in the `org.biojava.bio.structure.xtal`. Anything related to crystal reconstruction should go there. In fact the crystal reconstruction for the virus capsid entries should come from data in MTRIX/struct_ncs_oper records (stored already in `org.biojava.bio.structure.xtal.PDBCrystallographicInfo`) and not from the pdbx_struct_assembly annotation. 

Additionally the current code is inconsistent in that it treats the assembly id sometimes as a string and sometimes as an int, which is not ideal.

If there's nothing agains it, I'll implement this and create a pull request.

**Comment by andreasprlic** [comment]
+1

**Comment by pwrose** [comment]
+2

Any non-numeric assembly ids (PAU, XAU, etc.) can be ignored.

**Comment by josemduarte** [comment]
Note that as of mmCIF v5, the PAU and XAU identifiers have disappeared for bioassemblies. Now they are strictly numeric. I am fixing the tests accordingly.
