### ISSUE TITLE
Redundant StructureProvider interface

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#231]
Can we drop the StructureProvider interface? It mostly overlaps StructureIOFile (although 'StructureProvider' is a better name). Alternately, we could make the file readers inherit from StructurePrivider and drop/deprecate StructureIOFile. The difference is that StructureProvider has (partial) access to Biological Assemblies, while StructureIOFile knows something about what file extensions are supported.

The only use I know of for StructureProvider in rcsb/symmetry, for comparing structures in the 2011 remediation. I think that could be dropped now (right, @pwrose?).

**Comment by pwrose** [comment]
I've never used the StructureProvider interface, so I cannot comment
directly, but reducing redundant functionality is a good thing.

**Comment by sbliven** [comment]
Ok, I kept most things but integrated them better and clarified their relationship.
