### ISSUE TITLE
Auto-detecting file formats

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#232]
It would be convenient to auto-detect file formats. This is a hard problem, and one where the other Bio* projects differ. BioPerl has pretty good support for guessing file formats based on extension, magic bytes, or contents. BioPython has adhered to the python philosophy of 'explicit is better than implicit', and required the user to provide the format type.

What's the BioJava philosophy? I ask because I would like to implement auto-detecting structure formats (e.g. PDB vs mmCIF vs XML).

**Comment by sbliven** [comment]
There is a bit of magic happening already in `InputStreamProvider` to distinguish gzipped files.

**Comment by josemduarte** [comment]
Auto-detecting PDB vs mmCIF would be a really nice feature indeed. We implemented a very rough one in https://github.com/eppic-team/owl, which would decide by checking the first line of the file against these signatures (regexes):

```java
String[] FILE_SIGNATURES  = {
		"(?:HEADER|TITLE|COMPND|SOURCE|EXPDTA|REMARK|DBREF|SEQRES|CRYST1|MODEL|HELIX|SHEET).*",
		"ATOM\\s+.*",
		"PFRMAT\\s+TS.*",
		"PFRMAT\\s+RR.*",
		// mmCIF files from PDB always start with "data_PDBcode". 
		// Phenix's cif files do start with data_ but then with no PDB code 
		"data_\\w+.*"
	};
```

**Comment by pwrose** [comment]
+1

**Comment by andreasprlic** [comment]
I added some checks for magic numbers at the [InputStreamProvider](https://github.com/biojava/biojava/blob/master/biojava3-core/src/main/java/org/biojava3/core/util/InputStreamProvider.java) to check what kind of compression is getting used.

The main use-case that I see is in user interfaces, where a user can upload a custom file format. This could allow to support both PDB and mmCif file formats. ( I think currently all UIs allow only PDB format).

**Comment by phidias51** [comment]
It might be a good idea to separate the file sniffing code from the input
stream code.  This would let you use the file sniffer in different
contexts.  For example, you might use them as a key to select a file parser
(not just a compressor).

That said, it might be worth looking at Apache Commons Compress
CompressorStreamFactory which handles more file types.

Cheers,

Mark

**Comment by agupta1989** [comment]
+1

email sent using phone app.

**Comment by andreasprlic** [comment]
@sbliven can we close this one with you patches?

**Comment by sbliven** [comment]
Yes. It should autodetect unless your file has the wrong suffix.
