### ISSUE TITLE
Expand StructureName syntax to include multi-letter chain IDs

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#237]
Allow structures like 1XYZ.ABC to be fetched in getStructure methods of AtomCache, StructureIO, etc.

**Comment by dmyersturnbull** [comment]
Perhaps these changes should be integrated with https://github.com/biojava/biojava/blob/master/biojava3-structure/src/main/java/org/biojava/bio/structure/Identifier.java and https://github.com/biojava/biojava/blob/master/biojava3-structure/src/main/java/org/biojava/bio/structure/SubstructureIdentifier.java?

This could allow AtomCache and StructureIO to load SCOP domains and subsets of structures (e.g. 1hiv.A_1-10). The Identifier class isn't used much, but it were designed for this purpose.

P.S. I just noticed that UriIdentifier is still a stub, which is my fault. I remember you suggesting a role for it. Do you have any ideas for how to implement it? Presumably its methods would have to throw IOException. If we can't think of a design, it should probably be removed.

**Comment by andreasprlic** [comment]
if possible I'd like to squeeze this one in for the 4.0 release...

**Comment by sbliven** [comment]
Ok, I'll work on fixing the Identifier class and using it consistently.

In principle I like the idea of using uniform resource identifiers (URI) to identify structures, but they have a pretty formal specification. Ideally, the wwPDB would define a URI or URN (uniform resource name; basically a URI intended to be a unique ID) scheme for identifying structures. We could in principle do this ourselves and hope that others pick it up, but it would be stronger coming from the wwPDB standards body.

**Comment by dmyersturnbull** [comment]
Ok, I see. So no I/O would be involved; instead, UriIdentifier would map (e.g.) "http://wwpdb.org/1hiv/A"  to chain A of 1HIV. (Now I realize that I understood that when I wrote the stub.) In that case, I'm in favor of removing UriIdentifier until we know what to do with it.

**Comment by sbliven** [comment]
I'm pretty sure this part is fully complete in #244. If any problems remain, they will be fixed in 4.1.0 with #81.
