### ISSUE TITLE
Steps needed for the next BioJava release

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#238]
Here a todo list of what is missing before next BioJava release:

- [x] Upload 3rd party dependencies that are currently not in Maven central. ( forester.jar, colorbrewer.jar others? )
- [x] Declare code freeze
- [x] Discuss refactoring. 
- [x] Ensure that all classes contain the copyleft notice
- [x] Draft release announcement message (lots of changes in this release!) [draft of release notes](http://biojava.org/wiki/BioJava:Download_4.0.0#New_Features)
- [x] rename packages 
- [x] Perform refactoring after code freeze. (according to #245)
- [x] Run Optimize Imports across whole project.
- [x] Figure out how to exclude protein-comparison-tool module from upload, since it contains no source. (maven release fails if included)
- [x] Follow the [release instructions](http://www.biojava.org/wiki/BioJava:Make_release)
- [x] Publish release on OSS sonatype
- [x] Push to Maven central.
- [x] Update documentation to point to new availability location. 
- [x] Send release announcement email

**Comment by heuermh** [comment]
Can we also reach out to someone from [DebianMed](https://wiki.debian.org/DebianMed) for help in packaging the 4.0 release?

I was able to package an old release (1.7) at a hackathon with someone from DebianMed looking over my shoulder, and unfortunately that is the last time it happened for biojava-legacy.  There have been a few package updates for the 3.0.x series of releases

http://changelogs.ubuntu.com/changelogs/pool/universe/b/biojava3-live/biojava3-live_3.0.7+dfsg-1/changelog

**Comment by josemduarte** [comment]
How about giving a specific date for the release. I would propose Thursday next week (29th Jan)

I think it helps if we have a clear deadline, a week and a half from now hopefully gives everyone enough time to finish up things.

**Comment by andreasprlic** [comment]
Ok, we can declare the code freeze for next Thursday. Release will be anytime after we managed to push the .jars to maven central after that.

**Comment by andreasprlic** [comment]
About Debian: We certainly can talk to the debian folks. I suggest to do this post-release so all the code is out in the public.

**Comment by heuermh** [comment]
There are things in that changelog that might want to be considered before release, e.g. ```Remove tests needing network access (Closes: #696947)```.  I'll contact Olivier and see if he would be interested in taking a look before we cut 4.0.

**Comment by phidias51** [comment]
Rather coincidentally, I came across this thread on different packaging
tools that can be used to create debian packages:
http://stackoverflow.com/questions/8256326/maven-plugin-for-building-debian-package

Cheers,

Mark

**Comment by sbliven** [comment]
Did we reach a concensus about removing the '3' from module names? If so, that should happen during the code freeze.

**Comment by sbliven** [comment]
I started drafting the release notes at http://biojava.org/wiki/BioJava:Download_4.0.0

**Comment by josemduarte** [comment]
Regarding renaming of modules I would support the idea to do it after the code freeze. Another thing I would still insist on is to rename (during freeze) the packages `org.biojava.bio.structure.*` to `org.biojava3.structure.*` in order to have a consistent package namespace across all modules (the structure module is the only one not following that convention). 

We had a long discussion about all this in the mailing list, see the thread here: http://mailman.open-bio.org/pipermail/biojava-dev/2014-October/007842.html

**Comment by andreasprlic** [comment]
I don't think we have a consensus on this. However if you feel strongly about refactoring, we should organize a vote on this topic.

**Comment by andreasprlic** [comment]
Vote is at #240

**Comment by sbliven** [comment]
Additional vote at #242

**Comment by andreasprlic** [comment]
forester.jar and colorbrewer.jar have been released at Maven Central.

**Comment by andreasprlic** [comment]
import forester:
```
<dependency>
  <groupId>org.biojava.thirdparty</groupId>
  <artifactId>forester</artifactId>
  <packaging>jar</packaging>
</dependency>
```

import colorbrewer:
```
<dependency>
  <groupId>org.biojava</groupId>
  <artifactId>jcolorbrewer</artifactId>
  <version>5.2</version>
 </dependency>
```

**Comment by andreasprlic** [comment]
Who added the todo item about the copyleft notice in the header of every file? Is there a simple IDE shortcut that would allow todo that? Otherwise I'd vote to postpone this for next release, since this is a lot of manual labor and everybody contributing new files should be responsible for making sure that they use the correct headers.

**Comment by andreasprlic** [comment]
thanks to @sbliven for fixing all the missing copyright statements.
