### ISSUE TITLE
Move symmetry detection code in quaternary structures into biojava-structure

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#241]
We'll move the symmetry detection code from https://github.com/rcsb/symmetry into biojava.

**Comment by josemduarte** [comment]
:+1:

**Comment by sbliven** [comment]
+1

Should we move CE-Symm too? It makes some sense to keep it tied to CE/CE-CP in biojava, but the published URL is still rcsb/symmetry. Maybe move the core algorithm files, but leave the CLI?

**Comment by josemduarte** [comment]
I'm attempting to do the move of quaternary symmetry detection, I'll post some commits to my fork to see if you guys like it

**Comment by andreasprlic** [comment]
@josemduarte don't worry, we already almost finished this yesterday. The only reason why we did not commit this yet is because I needed to move the colorbrewer library to Maven Central first...

**Comment by josemduarte** [comment]
Awesome thanks a lot! I have some stuff already anyway. I'll put it in a branch off my fork in case it's useful at some point.

**Comment by josemduarte** [comment]
Alright I've put my version of it in https://github.com/josemduarte/biojava/tree/quat-sym-move and https://github.com/josemduarte/symmetry/tree/quat-sym-move

**Comment by andreasprlic** [comment]
Thanks, Jose. Peter did quite some cleanup and renaming of packages. I believe this can be closed now, unless you have suggestions for improvement.
