### ISSUE TITLE
GenbankSequenceParser does not parse CDS feature properly

### ISSUE THREAD

**Issue by jgrzebyta** [biojava/biojava#252]
For data:
```
     CDS             1..324
                     /gene="msbB"
                     /locus_tag="KPN_02370"
                     /coded_by="complement(NC_009648.1:2595658..2596632)"
                     /inference="ab initio prediction:Genemark:2.0"
                     /inference="protein motif:Pfam:IPR004960"
                     /note="Transfers myristate or laurate, activated on ACP,
                     to the lipid IVA moiety of (KDO)2-(lauroyl)-lipid IVA"
                     /transl_table=11
                     /db_xref="GeneID:5340071"

```
Only first  line is parsed. I found the unit tests for that class functions are too weak, e.g. tests for GenbankProxySequenceParser.

**Comment by paolopavan** [comment]
Hi Jacek,
Can you please provide the whole file? (You can also send it to me by regular mail)
I remember that you volunteered to write test cases on the topic, isn't it?

**Comment by jgrzebyta** [comment]
Hi,
Yeah. And now is the time I guess. The example file might be "BondFeature.gb" inside src/test/resources. 
I suggest load all "\" features as children of the main one.

**Comment by jgrzebyta** [comment]
Hi

I found it. It's inside Qualifiers. No bother. The isssue might be closed.

**Comment by paolopavan** [comment]
Yes, tags starting with / are qualifiers.

2015-02-23 17:12 GMT+01:00 Jacek Grzebyta <notifications@github.com>:
