### ISSUE TITLE
Possible Issue with Calc.angle() and Calc.torsion()

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#275]
From  Jose Colbes:

As a part of my work, I use these methods a lot. But I get NaN when the vectors are parallel. 

I know that it is a common issue (rounding errors and acos()) and there is info in the web to get around the problem, but I wanted you to know anyway.

**Comment by josemduarte** [comment]
Now fixed: angle returns 0 for parallel vectors. 

Note that for undefined cases the return is NaN:
- angle: if either vector length is 0, NaN is returned
- torsionAngle: if vectors are colinear, then NaN is returned

Another possibility would be to throw an IllegalArgumentException with such inputs
