### ISSUE TITLE
Add a tree view for showing the content of a Structure object to structure-gui module

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#283]
Would be great to have a tree-browsers that allows to view and interact with all the content under a biojava-structure object. It could be based on JTree (Swing) or TreeView (JavaFX).

**Comment by sbliven** [comment]
What's the use case for this?

**Comment by andreasprlic** [comment]
This is for interaction with a 3D viewer. (could look similar to Protein Workshop).

**Comment by andreasprlic** [comment]
won't fix

**Comment by andreasprlic** [comment]
I'd say that all future visualization should be on the web. E.g. biojava-http project
