### ISSUE TITLE
Extend biojava-structure to better support energy minimization.

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#284]
After discussion with @mjschnie :

Need to add objects such as 
- Angle
- Torsion
- TorsionTorsion
- PiOrbitalTorsion
- ImproperTorsion
- StretchBend
- UreyBradley
- OutOfPlaneBend
  etc.

see https://github.com/mjschnie/ffx/tree/master/modules/potential/src/main/java/ffx/potential/bonded

The goal is to move the "model" part of energy minimization into BioJava, while keeping the "control" aspect of this in the FFX project.

**Comment by josemduarte** [comment]
I'll close this for now, since it is outside the main scope of biojava-structure. Please reopen if there is interest.
