### ISSUE TITLE
Reading huge FASTA file

### ISSUE THREAD

**Issue by GiBacci** [biojava/biojava#285]
Hi all,
I would like to read a huge DNA fasta file generated through an NGS pipeline. The file is about 7.6Gb but I saw that the BioJava class for reading fasta file (the one reported in the CookBook: ```FastaReaderHelper```) stores all sequences inside a ```LinkedHashMap``` consuming almost all available RAM. I would like to know if there is a method for reading one sequence per time instead of storing all sequences in memory.

Thanks in advance

Giovanni

**Comment by willishf** [comment]
The framework is very flexible so you can try the following method where
you set lazySequenceLoad = true and you will get a LinkedHashMap back with
the accession ID and a corresponding DNASequence object that knows where in
the file based on a fast read using offset to get the sequence when you
request it. If you want to iterate through the file one sequence at a time
you can do that where you should then remove the entry from the
LinkedHashMap to free up the memory used by the sequence. You will need to
make sure you allocate enough memory to hold the indexes.

If 7.6GB file is still too large to hold all the indexes then using the
helper class code as an example  you should be able to put together your
own code to process one line at a time or setup a sequenceListener if you
want to abstract it out. That would be a useful method to add to the Helper
class.


   - readFastaDNASequence

   public static LinkedHashMap
<http://docs.oracle.com/javase/6/docs/api/java/util/LinkedHashMap.html?is-external=true><String
<http://docs.oracle.com/javase/6/docs/api/java/lang/String.html?is-external=true>,DNASequence
<http://www.biojava.org/docs/api/org/biojava/nbio/core/sequence/DNASequence.html>>
readFastaDNASequence(File
<http://docs.oracle.com/javase/6/docs/api/java/io/File.html?is-external=true>
file,
                                                        boolean
lazySequenceLoad)

throws IOException
<http://docs.oracle.com/javase/6/docs/api/java/io/IOException.html?is-external=true>

   Selecting lazySequenceLoad=true will parse the FASTA file and figure out
   the accessionid and offsets and return sequence objects that can in the
   future read the sequence from the disk. This allows the loading of large
   fasta files where you are only interested in one sequence based on
   accession id.
   Parameters:file -lazySequenceLoad -Returns:Throws:IOException
   <http://docs.oracle.com/javase/6/docs/api/java/io/IOException.html?is-external=true>

**Comment by GiBacci** [comment]
So, basically there is no class able to iterate over a file without storing all sequences in memory (or at least their indexes). Will it be possible in the future to have a class similar to ```RichSequence.IOTools``` in the new Biojava library?

Thanks for the reply,

Giovanni

**Comment by aalhossary** [comment]
I had made a function long time ago and forgot write about it in the cookbook

 

 

The function is  FastaReader.process(int)

Which takes maximum number of sequences to read. After reading it doesn’t close the file or InputStream, allowing for iterative calls on the next sequences.

http://www.biojava.org/docs/api/org/biojava/nbio/core/sequence/io/FastaReader.html#process(int)

 

I am not sure this is what you need or not, but I hope it would help.

 

Regards

Amr

**Comment by GiBacci** [comment]
Thanks,
this is what I needed! I can set the max to 1 and read a sequence per time until the ```LinkedHashMap``` will be ```null```. I saw the function called within the ```FastaReaderHelper``` class but I didn't pay much attention on it!

Thanks again!

Giovanni

**Comment by andreasprlic** [comment]
There is an example for this in the tutorial at:

https://github.com/biojava/biojava-tutorial/blob/master/core/readwrite.md

see also the recent thread on the mailing list:

http://lists.open-bio.org/pipermail/biojava-l/2015-June/011397.html
