### ISSUE TITLE
Structure Code behavior depends on the Algorithm Name (FatCat)

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#286]
We have had several problems when dealing with AFPChain alignments (one reported in #268), because the behavior of the code (superposition, display, sequence alignment) changes depending on the algorithm name that generated the AFPChain. In particular, if the algorithm name is jFatCat:

- The sequence alignment has different symbols for gaps.
- The superposition (rotation and translation) is recalculated again for every block in the display.

Even if these variables (sequence alignment and superposition) were not null before, they are recalculated and reset every time if the alignment name is FatCat, which overrides the original AFPChain.

One of the main problems is generated because the DEFAULT_ALGORITHM_NAME = "jFatCat_rigid" in AFPChain, so that if a new AFPChain() is instantiated or a method creates it from scratch, the name is automatically FatCat rigid. 

Possible solutions:
- Check if the variables are already set before calculating them again.
- In case calculation is needed, do not override the original AFPChain if the variables were set.
- Change the DEFAULT_ALGORITHM_NAME of AFPChain to "unknown".
- Every method that generated a new AFPChain has to set the name of the algorithm.

**Comment by andreasprlic** [comment]
Can we close this with your commit?

**Comment by lafita** [comment]
The core of the problem is that the behavior of downstream methods (scores, display, etc) on an **AFPChain** is different whether the **algorithmName** is set fo *jFatCat* or something else. There is not a real bug, but a design issue. If every alignment method ensures that the returned **AFPChain** has the variable **algorithmName** correctly set and that it is not modified, then everything works as expected. 

However, operations like cloning, copying some parts or manipulating the **AFPChain** can change the variable (or forget to set it properly) and produce unexpected results (and this type of bug is hard to find).

My commit only changed the DEFAULT **algorithmName** to "unknown", so that forgetting to set it generates the most common behavior, but if a FatCat **AFPChain** has its variable not properly set, the bug will also appear.

Another solution could be to make the variable **algorithmName** final and force the user to specify it when the **AFPChain** is constructed.
