### ISSUE TITLE
Source organism scientific name incorrectly parsed in 4xcw

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#289]
Reported in the mailing list:

For PDB 4xcw, only partial organism scientific name returned by the following method:

getOrganismScientific()
org.biojava.nbio.structure.Compound 

HELICOBACTER PYLORI (STRAIN J99 / ATCC 7

I traced back to PDBFileParser,  it seems this PDB file being treated in legacy format and the line length being trimmed into 72.

Can this problem be fixed somehow?

Thanks.

Guoying Qi

**Comment by andreasprlic** [comment]
thanks!
