### ISSUE TITLE
Chain getSeqResGroups method returns groups without atoms for nucleic acids

### ISSUE THREAD

**Issue by pwrose** [biojava/biojava#293]
Chain c = ..
List<Group> nucleotides = c.getSeqResGroups(GroupType.NUCLEOTIDE);

returns a list of groups, but the groups contain no atoms.

**Comment by josemduarte** [comment]
Would you have a specific PDB entry to test this?

**Comment by andreasprlic** [comment]
Did you set FileParsingParameters.setAlignSeqRes(true) ? Otherwise the SEQRES groups won't get matched up with the ATOM records.

**Comment by andreasprlic** [comment]
Any updates on this one that allow us to reproduce this? Otherwise I'll close it.
