### ISSUE TITLE
For a given Feature allow multiple Qualifier values per Qualifier key

### ISSUE THREAD

**Issue by zachcp** [biojava/biojava#301]
Hello Team BioJava,

Thanks for the great library! 

I have recently started to use BioJava for parsing Genbank files and I noticed a difference between BioJava and BioPython in their behavior that leads me to propose that BioJava change the `Qualifiers` slot in `org.biojava.nbio.core.sequence.features.AbstractFeature`  from `HashMap<String,Qualifier>` to `HashMap<String, ArrayList<Qualifier>>`.  Here's why:

In Biopython a `Feature` can have multiple `Qualifier` values for the same key. This is great for Genbank parsing a file like the one below where Features have multiple entries for the same key. Here are two examples: 

```
#Example 1 taken from http://mibig.secondarymetabolites.org/
CDS             5287..14826
                     /product="SalB"
                     /codon_start=1
                     /transl_table=11
                     /note="salinomycin polyketide synthase type I"
                     /note="smCOG: SMCOG1022:Beta-ketoacyl_synthase (Score:
                     285.5; E-value: 1.2e-86);"
                     /db_xref="GI:108743979"
                     /sec_met="Type: t1pks"
                     /sec_met="Domains detected: PP-binding (E-value: 3e-13,
                     bitscore: 39.3, seeds: 164); PP-binding (E-value: 1.2e-14,
                     bitscore: 43.8, seeds: 164); PKS_AT (E-value: 8.7e-106,
                     bitscore: 342.7, seeds: 1682); PKS_AT (E-value: 4.4e-109,
                     bitscore: 353.5, seeds: 1682); mod_KS (E-value: 1.4e-216,
                     bitscore: 708.3, seeds: 217); mod_KS (E-value: 1.6e-219,
                     bitscore: 718.0, seeds: 217); adh_short (E-value: 5.3e-57,
                     bitscore: 181.7, seeds: 230); adh_short (E-value: 1.8e-54,
                     bitscore: 173.5, seeds: 230)"
                     /sec_met="Kind: biosynthetic"
                     /sec_met="NRPS/PKS subtype: Type I Modular PKS"
                     /sec_met="NRPS/PKS Domain: PKS_KS (36-450). E-value:
                     1.8e-175. Score: 575.2;"
                     /sec_met="NRPS/PKS Domain: PKS_AT (565-853). E-value:
                     4e-105. Score: 342.7;"
                     /sec_met="NRPS/PKS Domain: PKS_KR (1193-1367). E-value:
                     1.8e-55. Score: 179.0;"
                     /sec_met="NRPS/PKS Domain: ACP (1472-1544). E-value:
                     9.3e-27. Score: 84.5;"
                     /sec_met="NRPS/PKS Domain: PKS_KS (1569-1999). E-value:
                     1.4e-175. Score: 575.6;"
                     /sec_met="NRPS/PKS Domain: PKS_AT (2124-2406). E-value:
                     2e-108. Score: 353.5;"
                     /sec_met="NRPS/PKS Domain: PKS_KR (2744-2917). E-value:
                     5.2e-51. Score: 164.4;"
                     /sec_met="NRPS/PKS Domain: ACP (3024-3095). E-value:


 #Example 2  from https://github.com/biojava/biojava/blob/master/biojava-core/src/test/resources/BondFeature.gb
   CDS             1..133
                     /gene="NDP"
                     /coded_by="NM_000266.2:503..904"
                     /db_xref="CCDS:CCDS14262.1"
                     /db_xref="GeneID:4693"
                     /db_xref="HGNC:7678"
                     /db_xref="HPRD:HPRD_02404"
                     /db_xref="MIM:300658"
```
In the first case extra/arbitrary Feature-specific information using the key "sec_met" is stored in the qualifiers table. Currently, in BioJava, there is no way to extract it. The second example, from the [BondFeature.gb](https://github.com/biojava/biojava/blob/master/biojava-core/src/test/resources/BondFeature.gb), will, when parsed, create a Feature with a single `db_xref` Qualifier entry with a value of `MIM:300658`, thereby dropping the other `db_xref` values.

To correct these issues, and to be in keeping with BioPython's approach, I think the Feature qualifiers should be changed to an array. The primary drawback of this is the possibility of breaking existing parsing scripts which is undersireable, however, I think the generality gained in processing Genbank files is worth it.  If there are no philosophical objections to this change I am happy to submit a pull request.

zach cp

**Comment by emckee2006** [comment]
You might also have to patch the writer as a result as well...

**Comment by andreasprlic** [comment]
Please go ahead and submit a pull request!

**Comment by andreasprlic** [comment]
I think Erik's pull request should have fixed this. Zak, can you confirm that we can close this issue?

**Comment by zachcp** [comment]
confirmed.
