### ISSUE TITLE
Get representative Atoms from Structure different than from Chain

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#309]
Calling: <pre>StructureTools.getRepresentativeAtoms(Structure s)</pre> Gives a different result than calling:
<pre>StructureTools.getRepresentativeAtoms(Chain c)</pre>
The first call returns an array of size 100 and the second an array of size 98 for 1hiv.A. The first method returns two Atoms more, corresponding to a modified residue CSO, in the middle of the array, and the ligand, at the end of the array. The ligand is 1ZK and has an Atom called CA.

This difference between the methods has caused some IndexOutOfBoundsExceptions when manipulating Atoms of a Structure. A solution could be using the chain method from the structure call. A Test and some test cases will be needed to make sure they are consistent.

**Comment by lafita** [comment]
Another issue popped up: the ChemComp information is not being loaded correctly for HETATMs that are modified aminoacids (loaded as nulls and unknowns), like CSO or LLP, so they are not returned as part of the representative Atom array. This breaks some of the existing tests.

**Comment by andreasprlic** [comment]
What ChemCompProvider are you using?

**Comment by lafita** [comment]
The problem was in internal dependencies of the test. The cache for the *ChemCompGroupFactory* was not reset properly when the *ChemCompProvider* was reset. I will create another issue regarding that and propose a fix. The differences between representative Atoms of chains and structures is fixed now.
