### ISSUE TITLE
Can't load bio assembly #7 from 1M4X

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#310]
From Ezra:

Biojava mmCif handler cannot give you info on biological assembly 7 of 1m4x

File loads ok... Indicates that there are 7 biological assemblies... Attempts to access #7 results in:

Exception in thread "main" java.lang.NullPointerException
        at org.biojava.nbio.structure.StructureIO.getBiologicalAssembly(StructureIO.java:158)

Which maps to
        List<BiologicalAssemblyTransformation> transformations =
asymUnit.getPDBHeader().getBioAssemblies().get(biolAssemblyNr).getTransforms();

I suspect some part of the code is looking for the number 7 - or rejecting the PAU

loop_
_pdbx_struct_assembly.id
_pdbx_struct_assembly.details
_pdbx_struct_assembly.method_details
_pdbx_struct_assembly.oligomeric_details
_pdbx_struct_assembly.oligomeric_count
1   'complete icosahedral assembly'                ? 5040-MERIC 5040
2   'icosahedral asymmetric unit'                  ? ?          ?
3   'icosahedral pentamer'                         ? ?          ?
4   'icosahedral 23 hexamer'                       ? ?          ?
5   'pentasymmetron capsid unit'                   ? ?          ?
6   'trisymmetron capsid unit'                     ? ?          ?
PAU 'icosahedral asymmetric unit, std point frame' ? ?          ?

**Comment by josemduarte** [comment]
The PAU/XAU assemblies are ignored since BioJava 4.0. See issue #230 for the full motivation behind that change.
