### ISSUE TITLE
add support for "getEntityInfo" API call to PDBStatus

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#316]
Would be great to get support for the getEntityInfo web service call

http://www.rcsb.org/pdb/rest/getEntityInfo?structureId=1hv4

That way one could easily identify structures that contain nucleotides, without having to actually parse a PDB file directly.

**Comment by josemduarte** [comment]
The RCSB API is in the process of being changed, so this will not apply anymore once that endpoint is deprecated.
