### ISSUE TITLE
Deprecate Chain.getParent(), rename to Chain.getStructure()

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#320]
To be consistent with some of the other recent API changes, we should deprecate ```Chain.getParent()``` and create a new  ```Chain.getStructure()```, which will replace it at some point in the future.

**Comment by jacob-litman** [comment]
As a note: the biojava-ffx branch is already this way, on account of an irrevocable API clash with the MSNode class in FFX, stemming from a Java Swing class.

**Comment by josemduarte** [comment]
+1
Consistency is always good, we should at the same time make sure we have the same convention for the whole `Structure -> Chain -> Group -> Atom` hierarchy and deprecate anything that doesn't follow the convention
