### ISSUE TITLE
GenbankProxySequenceReaderTest hungs

### ISSUE THREAD

**Issue by paolopavan** [biojava/biojava#324]
testProteinSequenceFactoring() hungs and do not permit library compilation and jar file making.

**Comment by andreasprlic** [comment]
What is your system? Seems the test passes ok on Travis CI.

**Comment by paolopavan** [comment]
Windows Java 8. Can I add more details?

Inviato da iPhone

**Comment by andreasprlic** [comment]
yes, a stacktrace or failure-message would be helpful. Thanks,

**Comment by paolopavan** [comment]
Hi Andreas! It seems it was related to my configuration, sorry about that. I'm closing the issue.
