### ISSUE TITLE
problems with parsing PDB 2ja5 under certain conditions

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#326]
reported on mailing list by Guoying Qi

This gives a nullpointer exception:

String pdbFileName = "testdata/test/pdb/pdb2ja5.ent";

        FileParsingParameters fileParsingParameters = new FileParsingParameters();
        fileParsingParameters.setStoreEmptySeqRes(true);
        fileParsingParameters.setLoadChemCompInfo(false);
        fileParsingParameters.setHeaderOnly(true);

        PDBFileParser parser = new PDBFileParser();
        parser.setFileParsingParameters(fileParsingParameters);
        
        BufferedReader pdbFileReader = new BufferedReader(new FileReader(pdbFileName));
        Structure structure1 = parser.parsePDBFile(pdbFileReader);
        
        System.out.println("***\n" + structure1 + "****\n");

        PDBFileReader pdbreader = new PDBFileReader();
        pdbreader.setFileParsingParameters(fileParsingParameters);
        Structure structure2 = pdbreader.getStructure(pdbFileName);

        System.out.println("***\n" + structure2 + "****\n")

**Comment by josemduarte** [comment]
This is fixed, isn't it? I'll close it, please reopen if needed
