### ISSUE TITLE
StructureTools#getGroupsWithingShell(Structure, Group,double,boolean) method should return Set<Group>

### ISSUE THREAD

**Issue by sroughley** [biojava/biojava#327]
The StructureTools#getGroupsWithinShell(Structure structure, Group group, double distance, boolean includeWater) currently returns a List<Group>.

As this method calls the  StructureTools#getGroupsWithinShell(Structure structure, Atom atom, Set<ResidueNumber> excludeResidues, double distance, boolean includeWater) repeatedly for each atom, the returned list can contain multiple copies of the same Group object as it may be within the threshold distance from more than 1 atom in the query group.

The method called also returns a Set<Group>, which makes sense, and it would therefore make more sense for both methods to return a Set.

However, changing the return type of this method may break other code elsewhere, so maybe a new method:

public static Set<Group> getUniqueGroupsWithinShell(Structure structure, Group group, double distance, boolean includeWater)

should be added?

If you let me know which is preferred, I will implement it.

Steve

**Comment by andreasprlic** [comment]
I'd say let's change the signature of that method. I don't think it is widely used, as such this should be not too painful. Any patch for this is welcome! Please also update any other place in the code that is referring to this method. Thanks!

**Comment by sroughley** [comment]
OK, I will check for anywhere in the code referring to that and unless it causes too many problems, submit a pull request in the next few days.

**Comment by josemduarte** [comment]
Just a note related to that method, there's some more code to calculate contacts and atoms within a distance in the `org.biojava.nbio.structure.contact` package. In the `StructureTools` class there's some methods making use of them, see for instance `getAtomsInContact(Chain, Chain, String[], double, boolean)`. The return type of those ones is an `AtomContactSet`, which in turn contains `AtomContact`s (both classes from the `org.biojava.nbio.structure.contact` package).

**Comment by josemduarte** [comment]
The tutorial has something about contacts, have a look too:

https://github.com/biojava/biojava-tutorial/blob/master/structure/contact-map.md

**Comment by sroughley** [comment]
Thanks Jose. I will take a look at those.
I have checked and the method here is not called anywhere else, so I see no problems with changing the signature.  I have therefore changed the signature to return Set<Group>, and the implementation generates a LinkedHashSet<Group> as per the other #getGroupsWithinShell method, and submitted a pull request
Steve
