### ISSUE TITLE
DBREF records in PDB files written from StructureImpl cause IndexOutOfRange exception when reading back in

### ISSUE THREAD

**Issue by sroughley** [biojava/biojava#330]
DBREF records do not all contain 80 characters when written out using StructureImpl#toPdb(), and so re-reading a PDB file written out this way causes an exception to be thrown as the DBREF parser in PDBFileParser at the following line:

String dbinsEnd = line.substring(67,68);  (line 2198)

There are a number of other StructureImpl Member classes which also do not write full length lines (e.g. HEADER is truncated after ~67 chars).  In most cases, these do not affect the biojava parser but may effect other tools which expect the full 80 char lines.  However, e.g. TITLE wraps the title over multiple lines each of 67 chars instead of using the full width.

I suggest:
1) Add an option to FileParsingParameters for allowShortLines, which simply adds ' ' chars to each line shorter than 80 characters during the reading process when it is 'true'
2) (Optional) Ensure all parsing methods which parse lines with optional parameters at the end are "short line safe"
3) Fix the toPDB() methods of all classes to ensure they write full 80-char lines

If agreed, I can start to work through these (starting with the first option)

**Comment by josemduarte** [comment]
I totally agree with your comments, the parser should be able to parse lines with or without padded spaces. From your suggestion I'd definitely support doing 2 and 3, but regarding 1 I would say it's not a good idea to introduce another parsing parameter if not strictly needed. The parser can be made robust enough to parse both style of files, I would not see a use-case for having it as a parameter.

**Comment by sroughley** [comment]
OK - in that case, for most records, the simplest way to achieve 2 is probably to simply right-pad out to 80 chars.  I will take a look at this in the next day or two, and then will start checking through some of the other methods to get 3 implemented.  I guess the one possible advantage of 1) is that it enables some sort of 'strict' parsing mode - but as you say I'm not really sure why anyone would do that!

**Comment by sroughley** [comment]
I have submitted a pull request to deal with the simple case of padding out the lines to 80 chars during parsing, and have started work on the individual #toPDB() methods.

I was also looking, while I was dealing with the DBRef class to add support for DBREF1/2.  That doesn't appear too difficult, but I wondered why StructureException is not part of the method signature for the PDBFileParser#parsePDBFile methods, as this is described as "An exception during the parsing of a PDB file."?  I was about to change the method signature and realised that a lot of classes and testcases break, so decided to take a step back...

**Comment by josemduarte** [comment]
Support for DBREF1/2 would be really nice. Regarding the `StructureException` not being part of the signature, that's definitely an inconsistency. `StructureException` is being used at the moment for any kind of generic problem that occurs while dealing with Structures/Chains/Groups, but not during parsing. 
`StructureIO` (a higher level wrapper for the parsers) also makes use of `StructureException`. Problems during parsing go to `IOException`s only. I think that's fine as long as it is well documented, perhaps we should simply update the docs to reflect that.

**Comment by sroughley** [comment]
If you like, I will see how much work it would be to add StructureException - it would seem to be more consistent that way, and then IOException is retained for real IOException situations e.g. dropped file connections, stream closing issues and the like?

**Comment by andreasprlic** [comment]
In my opinion, changing an API for the sake of renaming an exception is not worth it. 

We should probably fix the javadoc for StructureException and stop making the claim that it gets thrown during parsing. It probably was at some point in the past, but that might have been refactored over time. (If I remember correctly that exception goes back to the early days of biojava-structure)

**Comment by sroughley** [comment]
There is also the PDBParseException in org.biojava.nbio.structure.io which is also described as "An exception during the parsing of a PDB file."  Surely the IOException should only be thrown (as it will be) by problems with the actual stream reading, and either PDBParseException or StructureException by actual problems with the content?  One option could be to convert PDBParseException to a subclass of IOException?

**Comment by josemduarte** [comment]
I'd agree with your last comment: since `StructureException` is already in use by `StructureIO`, it seems logical to use `StructureException` also for parsing problems, so that we end up with a single Exception that encapsulates all problems with PDB/mmCIF data issues. 

Making it a subclass of `IOException` would be tempting so that signatures don't have to change but wouldn't be the cleanest solution since many times the `StructureException` won't really be some sort of parsing issue (and thus loosely related to IO) but some data problem.

A pull request to fix all this would be great, but we'd have to see how much does this affect the API. In principle it is a minor API change that could go in with 4.2.

**Comment by sroughley** [comment]
Thanks Jose.  A quick look shows that the only thing in Biojava itself which breaks are the test cases in biojava-structure, and the integration test - in all cases because the test method signature includes 'throws IOException' to deal with any IOExceptions thrown, so I think it should be fixable with a little care.  I will carry on with it over the next few days/weeks and get that pull request in to you.

**Comment by paolopavan** [comment]
Hi, for SearchIO I have used Java standard ParseException for file format related issues and IOException for file related issues. 
It seemed well suited to me. 




Inviato da iPhone

**Comment by sbliven** [comment]
I cherry-picked sroughley's commits and made sure everything tests out. Merged!
