### ISSUE TITLE
PDB Structure AtomImpl has no charge

### ISSUE THREAD

**Issue by sroughley** [biojava/biojava#331]
The Atom Interface and AtomImpl class in org.biojava.nbio.structure does not handle or store the charge on the atom from the PDB line.  The PDBParser also needs to be modified to store and write this property

**Comment by josemduarte** [comment]
It would be good to have charge as well for completion, though in actual experimental structures (at least from x-ray diffraction) is almost never used. On the other hand MD programs do use them all the time.

One important point is that we would need to have support for it in both the PDB parser and the mmCIF parser (see `org.biojava.nbio.structure.io.mmcif` package). The relevant mmCIF data item is [_atom_site.pdbx_formal_charge.html](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Items/_atom_site.pdbx_formal_charge.html)

**Comment by andreasprlic** [comment]
Can you comment on the use case for this? It would be interesting to learn more about what you have in mind with this.

**Comment by sroughley** [comment]
The initial motivation is to return "correct" 80 char ATOM and HETATM lines - at present the charge information in the last two characters of the line is lost.  Whilst this may be of little consequence in many cases, there are according to the link supplied by Jose ~1% of PDB structures containing information in this field.  Some heterogens have charged atoms e.g. quaternary nitrogen.  Additionally, other tools (e.g. PyMOL) often use this field, and so it is helpful not to lose the information if passing structures through Biojava

**Comment by sbliven** [comment]
One measure of a "complete" parser (PDB/cif) is that parsing a structure and writing it back out matches the input exactly. By this measure it would be nice to add the charge.

This requires adding a field to Atom, right? Will that be a problem?

**Comment by sroughley** [comment]
That is my point above.  It is not a problem to do this, but obviously also needs the mmCif and PDB parser to writer methods adjusted to handle the charge (or empty whitespace).  I will implement in the next few weeks and submit a pull request

**Comment by andreasprlic** [comment]
Perhaps we should introduce alternative implementations for Atom at this point. There could be some more memory efficient implementations containing minimal data for algorithms, as well as "full" data representations for other use cases.

**Comment by sbliven** [comment]
It seems like overkill to have alt implementations. Adding the charge to Atom should be simple enough.

**Comment by andreasprlic** [comment]
Agreed, as we discussed today on skype. For algorithms it is better to work directly with an array of (vecmath) points, rather than the atom class.

**Comment by abradle** [comment]
Hi all,

I was wondering if there's been any progress on this. I'm looking into SDFile support for BioJava (writing ligands) and I need the atom charge in order to proceed. 

Best wishes,

Anthony

**Comment by andreasprlic** [comment]
I believe Antony's commit should address this issue.
