### ISSUE TITLE
PDB files: java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by julie-sullivan** [biojava/biojava#338]
Sorry if this isn't the right place to post but I am getting an error using the BioJava library when processing PDB files:

```
BUILD FAILED
 java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuffer.append(StringBuffer.java:237)
	at org.biojava.bio.structure.PDBHeader.printTitle(PDBHeader.java:249)
	at org.biojava.bio.structure.PDBHeader.toPDB(PDBHeader.java:105)
	at org.biojava.bio.structure.io.FileConvert.toPDB(FileConvert.java:196)
	at org.biojava.bio.structure.StructureImpl.toPDB(StructureImpl.java:559)
	at org.intermine.bio.dataconversion.PdbConverter.processPDBFile(PdbConverter.java:171)
	at org.intermine.bio.dataconversion.PdbConverter.process(PdbConverter.java:104)
```

1. I was using `biojava3-structure-3.0.7.jar` this morning but I also tried `biojava-structure-4.1.0.jar`.
2. I downloaded the PDB files from pdb.org
3. I am getting the error for `1i9o.pdb`. I skipped that one but got the same error on `1i9p.pdb`. I looked at both files and they don't seem weird, but what do I know.
4. My settings are: 

> -server -XX:MaxPermSize=512M -Xmx32G -XX:+UseParallelGC -Xms2G -XX:SoftRefLRUPolicyMSPerMB=1 -XX:MaxHeapFreeRatio=99 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp

Any ideas on how I can fix this? Thanks!!

**Comment by lafita** [comment]
I could not reproduce the error for entry `1i9o`. I tried parsing the structure from a downloaded file from the PDB, as you mention, and used the same parser you are using in the **intermine** repository.

A possible explanation for the `OutOfMemoryError` could be the use of many structures at the same time. Are you parsing a single structure at a time, or are you keeping them all together in memory?

I copy the code I tried to reproduce the error:

```java
public class Issue338 {
	
	public static void main(String[] args) 
			throws IOException, StructureException {
		
		PDBFileParser pdbfileparser = new PDBFileParser();
        Reader reader2 = new FileReader("src/main/resources/1I9O.pdb");
        PdbBufferedReader pdbBuffReader = new PdbBufferedReader(reader2);
        Structure intermineS = pdbfileparser.parsePDBFile(pdbBuffReader);
		
		System.out.println(intermineS.toPDB());
		
	}
}

```

**Comment by julie-sullivan** [comment]
Hi @lafita!! I am processing a lot of PDB files, but one after the other. Here's my code:

https://github.com/julie-sullivan/intermine/blob/dev/bio/sources/pdb/main/src/org/intermine/bio/dataconversion/PdbConverter.java#L120

My code travels through the data directory and parses each PDB file it finds. You can see in the method above, everything is locally scoped. So when the code exits out of the method, everything related to the structure should be garbage collected. Only the proteins and taxon maps are global but they are very small.

What do you think? Ideas?

Thanks!

**Comment by julie-sullivan** [comment]
For the record, that file that fails is the 1929th PDB file being processed. I deleted it (for a test) and the next file failed. So I don't think my problem is file specific.

This may be why we didn't have the problem with Drosophila melanogaster because there were less files than that. For Homo sapiens, there are 25,000 files to parse.

**Comment by pwrose** [comment]
Is this just a memory issue since all atom records are stored in the
proteinStructure object:

proteinStructure.setAttribute("atm", structure.toPDB());

On Thu, Oct 22, 2015 at 9:34 AM, Julie Sullivan <notifications@github.com>
wrote:

> For the record, that file that fails is the 1929th PDB file being
> processed. I deleted it (for a test) and the next file failed. So I don't
> think my problem is file specific.
>
> This may be why we didn't have the problem with Drosophila melanogaster
> because there were less files than that. For Homo sapiens, there are 25,000
> files to parse.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biojava/biojava/issues/338#issuecomment-150281987>.
>



-- 
Peter Rose, Ph.D.
Site Head, RCSB Protein Data Bank West (http://www.rcsb.org)
San Diego Supercomputer Center (http://bioinformatics.sdsc.edu)
University of California, San Diego
+1-858-822-5497

**Comment by josemduarte** [comment]
Yes storing the full `toPDB()` representation (essentially a full PDB file) for many PDB entries will fill the memory very quickly. So it does seem the issue is that you need a lot of memory to store that `proteinStructure` object. The fact that it fails in a biojava call (as your stack trace shows) is just by chance. The memory got full and the first object that couldn't be stored happened to be a StringBuffer from a Biojava call.

The solution would be either to increase the memory of your JVM or not to store so much data into memory.

**Comment by lafita** [comment]
Hi @julie-sullivan,

As @josemduarte and @pwrose point out, it is a problem to keep all the PDB files in memory. Although you are parsing every entry individually, the `protinStructure` objects retain the PDB file as a String. Note that the `Sructure.toPDB()` method produces a String identical to the information contained in a PDB file, in the order of a few MB. The memory will be filled up at one point or another if such a large number of structures are parsed, that is why the error is not entry specific.

I do not know the purpose of storing the whole PDB files as a String in memory. If I understood correctly the files are stored locally, so the best solution would be to read the local files only when they are needed (the getter for the attribute in `proteinStructure` will have to read or download the file). If the files need to be downloaded each time the performance could be affected, but if they are locally stored, this should not be a problem (you can always set the PDB_DIR option to store locally the files you download with BioJava, if you will use the same PDB files from the PDB website a lot). 

Another solution could be to increase the maximum VM memory, but I do not recommend it because I see that you are currently using 32GB (`-Xmx32G`), which should be big enough for any BioJava purpose. It is also a bad idea because the problem is still there, at some point when the number of structures parsed increases the error will reappear.

Did you intend to store the whole PDB files as String in memory? In that case, what are they used for?

I hope the explanation helped.

**Comment by justinccdev** [comment]
Hi folks.  I'm a colleague of @julie-sullivan's at InterMine also now taking a look at this problem.

* Just to clarify, the code we're actually using is the processPDBFile() method on a branch [here](https://github.com/julie-sullivan/intermine/blob/pdb-fix/bio/sources/pdb/main/src/org/intermine/bio/dataconversion/PdbConverter.java#L121).  However, I don't think this substantially changes things.

* On calling 

```
store(proteinStructure);
```

at the end of the method, the proteinStructure is stored to the database.  No reference to the structure remains so it should be GC'd.  If we were holding on to a reference my expectation is we would have noticed a memory problem in other data loaders.

* Looking at BioJava code, I see that the PDBFileReader.getStructure() method, as triggered by

```structure = reader.getStructure(file);```

opens an InputStream to read the file.  However, as far as I can see it never gets closed!  Not closing InputStreams is a possible source of memory leaks which may not be noticeable in an executable that only processes a couple of PDB files.  The issue with not closing InputStreams exists on both BioJava 3.0.7 and 4.1.0 as far as I can see.

Am I mistaken about this?

**Comment by josemduarte** [comment]
Thanks for the clarification! I think we all assumed that `store(proteinStructure)` was storing the whole thing into memory. Now things are clearer, if it goes to a database then that's a harmless call. You might be right about the resource leak with non-closing InputStreams, I'm going to have a good look at it.

**Comment by josemduarte** [comment]
So I've just tried equivalent code as you have, using Biojava 4.1.1-SNAPSHOT (current HEAD of master branch) and could not reproduce the issue. 

I ran with `-Xmx1g` and could parse more than 5000 PDB files without memory issues. The only difference in my code is that I don't have a `proteinStructure` object.

In my experience it is difficult that a resource leak (like not closing InputStream) can produce an out of memory error. It can produce other out of resources errors, but not so easily a memory issue. I'd try to find out whether some references are left around, e.g. in `store(proteinStructure)` that could be causing the memory leak.

**Comment by andreasprlic** [comment]
Just to comment, we are using the parser (biojava 4.1.0) to parse thousands of structures every week. I am sure there is not some obvious memory leak present in BioJava...

**Comment by julie-sullivan** [comment]
First, thanks for all of your replies and pointers! Very helpful.


* I got my build to work when I removed `structure.toPDB()`:

https://github.com/julie-sullivan/intermine/blob/pdb-fix/bio/sources/pdb/main/src/org/intermine/bio/dataconversion/PdbConverter.java#L172-L176

* To test further, I took *everything else* out -- including storing to the database:

```
    private void processPDBFile(File file, String taxonId)
        throws Exception {
        PDBFileReader reader = new PDBFileReader();
        reader.setAutoFetch(false);
        Structure structure = null;
        LOG.error("parsing " + file.getName());
        try {
            structure = reader.getStructure(file);
        } catch (IOException e) {
            // see #1179
            LOG.error("couldn't parse " + file.getName());
            return;
            //throw new BuildException("Couldn't open file for: " + file.getName());
        }
        structure.toPDB();
    }
```

The build still fails.

* Can someone try to reproduce this error? Here are the files I processed before falling over:

```
2015-10-26 17:25:12 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 21bi.pdb
2015-10-26 17:25:12 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 221p.pdb
2015-10-26 17:25:12 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 22gs.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a01.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a0c.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a0q.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a0w.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a0x.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a0y.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a0z.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a14.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a1h.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a1i.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a1j.pdb
2015-10-26 17:25:13 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a1s.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a1t.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a1u.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a1x.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a24.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a25.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a26.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a27.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2a.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2c.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2d.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2k.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2n.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2q.pdb
2015-10-26 17:25:14 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2r.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2s.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a2z.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a30.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a38.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a3i.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a3j.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a3k.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a3r.pdb
2015-10-26 17:25:15 ERROR org.intermine.bio.dataconversion.PdbConverter     - parsing 2a3w.pdb
```


* Here's a visualisation of the dump file I get when it falls over:

![pdb](https://cloud.githubusercontent.com/assets/1663057/10736171/6ff3d7f4-7c03-11e5-8279-86bb3b86db54.png)

Thanks!

**Comment by josemduarte** [comment]
I tried a very similar test (see my comment above) and I could parse more than 5000 files (calling `structure.toPDB()` in all of them) with a max memory of 1GB (`Xmx1g`).

In that last test you ran, how many files has it gone through when it breaks?

**Comment by julie-sullivan** [comment]
@josemduarte Thanks for testing! I was only able to parse those 20 or so files I list above.

**Comment by josemduarte** [comment]
@julie-sullivan I've tried now the exact same list of PDBs you give above and the code runs fine. I've tried it both with Biojava 4.1.1-SNAPSHOT (current master HEAD) and with 4.1.0, both ok.

What's the error you get now? Is it still an out of memory?

**Comment by julie-sullivan** [comment]
yes same error.

**Comment by josemduarte** [comment]
So it seems we can't really reproduce it... I'm afraid you are going to need to isolate the problem a bit more and see if we can reproduce something similar. Otherwise I'm out of ideas. 

Other ideas anyone?

**Comment by andreasprlic** [comment]
Use a profile to trace what is going on in the code?

**Comment by emckee2006** [comment]
You could also take a heap snapshot/dump and try to figure out exactly
what's filling up the heap...

Have you tried different java versions to rule out a vm issue?

**Comment by julie-sullivan** [comment]
@josemduarte Thanks for spending so much time on this! 

When you tested, did you use that AtomCache thing? Or did you just read the file from the directory?

**Comment by julie-sullivan** [comment]
@andreasprlic I posted a profile above. Unless you meant something else?

I notice there are AtomImpl (35,000 of them!) objects in memory, *after* garbage collection. As well as chars and other types InterMine doesn't use.

Since my (now truncated) code isn't holding references to any objects biojava, it's quite a puzzle as to how this may have happened!

**Comment by josemduarte** [comment]
@julie-sullivan I tested with exactly the same code you had, reading PDB files from the directory explicitly.

**Comment by julie-sullivan** [comment]
@emckee2006 I posted a snapshot above. It seems that there are a 2GB of chars and 4 GB of strings in memory, even after garbage collection.

Good idea! I didn't think of that, I am currently using Java 8 but tried with Java 6 and 7, with the same results.

**Comment by julie-sullivan** [comment]
oops I think I may have had my dependencies wrong and really been using the older biojava JAR after all. Let me test.

**Comment by julie-sullivan** [comment]
Yes, the old BioJava JAR was still on my classpath and that's the one this source was using. Apologies! I'm an idiot! I removed it and re-ran the source with no problems at all.

Thank you so much for your time, and thank you so much for this great library so I don't have to parse PDB files myself!

**Comment by andreasprlic** [comment]
I recommend to migrate your build environment to use Maven :-)

**Comment by josemduarte** [comment]
Glad that it is solved in the end! One comment above parsing PDB files, you should really consider using files in mmCIF format instead of PDB format. The PDB format should be considered legacy now, in fact the PDB doesn't provide PDB files anymore for very large structures in the archive, so you won't be able to cover the whole archive unless you use mmCIF. 

Biojava supports parsing mmCIF too, so that shouldn't be an issue. If you see something missing or not working in the parser please feel free to submit a ticket.

**Comment by julie-sullivan** [comment]
@andreasprlic lol, yes, you are not wrong!

@josemduarte Thanks for all your patience! And I didn't realise about PDB files, I will switch to use mmCIF instead. I've made myself a ticket.

Thanks again!
