### ISSUE TITLE
PDB files: error parsing the journal (maybe)

### ISSUE THREAD

**Issue by julie-sullivan** [biojava/biojava#339]
`1crm.pdb`

```
[integrate] file name 1crm.pdb
[integrate] null
[integrate] java.lang.NumberFormatException: For input string: "TION"
[integrate] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[integrate] 	at java.lang.Integer.parseInt(Integer.java:492)
[integrate] 	at java.lang.Integer.valueOf(Integer.java:582)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser$JournalParser.<init>(PDBFileParser.java:2501)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.buildjournalArticle(PDBFileParser.java:2446)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.triggerEndFileChecks(PDBFileParser.java:2193)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2107)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:1963)
[integrate] 	at org.biojava.bio.structure.io.PDBFileReader.getStructure(PDBFileReader.java:486)
[integrate] 	at org.intermine.bio.dataconversion.PdbConverter.processPDBFile(PdbConverter.java:129)
[integrate] 	at org.intermine.bio.dataconversion.PdbConverter.process(PdbConverter.java:104)

```

Which has this text:

```
JRNL        AUTH   K.K.KANNAN                                                   
JRNL        TITL   STRUCTURE AND FUNCTION OF CARBONIC ANHYDRASES                
JRNL        EDIT   R.SRINIVASAN                                                 
JRNL        REF    BIOMOLECULAR STRUCTURE,       V.   1   165 1981              
JRNL        REF  2 CONFORMATION, FUNCTION AND                                   
JRNL        REF  3 EVOLUTION                                                    
JRNL        PUBL   PERGAMON PRESS, OXFORD                                       
JRNL        REFN  
```

1. I was using `biojava3-structure-3.0.7.jar` this morning but I also tried `biojava-structure-4.1.0.jar`.
2. I downloaded the PDB files from pdb.org

**Comment by julie-sullivan** [comment]
Same error on `1a27.pdb`:

```
JRNL        AUTH   C.MAZZA                                                      
JRNL        TITL   HUMAN TYPE I 17BETA-HYDROXYSTEROID DEHYDROGENASE: SITE       
JRNL        TITL 2 DIRECTED MUTAGENESIS AND X-RAY CRYSTALLOGRAPHY               
JRNL        TITL 3 STRUCTURE-FUNCTION ANALYSIS                                  
JRNL        REF    THESIS, UNIVERSITE JOSEPH                  1997              
JRNL        REF  2 FOURIER                                                      
JRNL        PUBL   GRENOBLE : UNIVERSITE JOSEPH FOURIER (THESIS)                
JRNL        REFN     
```

**Comment by josemduarte** [comment]
Could you post some code to show what the issue is exactly?

I've tried the following:

```java
public class TestIssue339 {
	
	public static void main (String[] args) throws Exception {
		
		AtomCache cache = new AtomCache();
		cache.setUseMmCif(false);
		
		
		Structure s = cache.getStructure("1crm"); 
		
		System.out.println(s.getPDBHeader().getTitle());
		System.out.println(s.getPDBHeader().getJournalArticle());
		
	}

}
```
and got this output:
```
STRUCTURE AND FUNCTION OF CARBONIC ANHYDRASES
JRNL        AUTH   K.K.KANNAN,
JRNL        TITL   STRUCTURE AND FUNCTION OF CARBONIC ANHYDRASES
JRNL        EDIT   R.SRINIVASAN,
JRNL        REF    BIOMOLECULAR STRUCTURE,       V.   1   165 1981 CONFORMATION, FUNCTION AND EVOLUTION 
JRNL        PUBL   PERGAMON PRESS, OXFORD
```
So all looks ok to me.

**Comment by julie-sullivan** [comment]
Hi @josemduarte! Yes, most PDB files work fine for me, except for a few. Here's the line of code mentioned in the stacktrace:

https://github.com/julie-sullivan/intermine/blob/pdb-fix/bio/sources/pdb/main/src/org/intermine/bio/dataconversion/PdbConverter.java#L127

I added the try/catch block to (temporarily!) ignore these errors.

Thank you for your help!!

**Comment by josemduarte** [comment]
Hi @julie-sullivan , looking at your code it seems that you are using Biojava 3, not sure exactly which minor version of it, but definitely it's not 4. I also see in your code that you are using `Structure.getHeader()` which has been removed from the API as it was already deprecated in Biojava 3 (see #102). The way to do that now would be through `Structure.getPDBHeader()` which returns a `PDBHeader` object containing accessors to all the data that you are interested in (title, technique, classification, resolution etc).

In any case in order to be able to debug it, it would be helpful to know exactly which PDB entry produces the error. As I show above in current Biojava 4.1 the PDB id 1CRM parses fine for me.

**Comment by josemduarte** [comment]
I forgot to say, it is strongly recommended to upgrade to latest Biojava version (4.1) as there have been a lot of bug fixes and also many new features added since 3. In principle we are not producing bugfix releases for the 3 lineage anymore.

**Comment by julie-sullivan** [comment]
I've updated to 4.1: https://github.com/julie-sullivan/intermine/tree/pdb-fix/bio/sources/pdb/main/lib but still get the same error. 

I've also updated my code to the new methods. Thanks for that!! Much cleaner now. : ) https://github.com/julie-sullivan/intermine/blob/pdb-fix/bio/sources/pdb/main/src/org/intermine/bio/dataconversion/PdbConverter.java#L137

**Comment by julie-sullivan** [comment]
1a27.pdb and 1crm.pdb are the entries that break for me. My code is a bit different from yours in that I don't know what setUseMmCif is or atomcache, I am just reading the data file in. 

All of the other 591 PDB files seem to be processing okay. 

Does the error message make any sense to you? Why would it be treating TION (or RIER in the second case) as an integer? A parsing issue?

**Comment by julie-sullivan** [comment]
I tried redownloading those files from PDB but I still get the error.

**Comment by josemduarte** [comment]
What I did with my code above is essentially parsing the deposited PDB file for 1CRM (AtomCache takes care of downloading it for me, see [this part of the tutorial](https://github.com/biojava/biojava-tutorial/blob/master/structure/caching.md) ).

The more explicit code to directly parse a local PDB file would be:

```java
import java.io.File;
import java.io.FileInputStream;

import org.biojava.nbio.structure.Structure;
import org.biojava.nbio.structure.io.PDBFileParser;

public class TestIssue339 {
	
	public static void main (String[] args) throws Exception {
	
		PDBFileParser parser = new PDBFileParser();
		File file = new File("/Users/jose/1CRM.pdb");
		
		Structure s = parser.parsePDBFile(new FileInputStream(file));
		
		System.out.println(s.getPDBHeader().getTitle());
		System.out.println(s.getPDBHeader().getJournalArticle());
		
	}
}
```
Which for me still produces the correct output:
```
STRUCTURE AND FUNCTION OF CARBONIC ANHYDRASES
JRNL        AUTH   K.K.KANNAN,
JRNL        TITL   STRUCTURE AND FUNCTION OF CARBONIC ANHYDRASES
JRNL        EDIT   R.SRINIVASAN,
JRNL        REF    BIOMOLECULAR STRUCTURE,       V.   1   165 1981 CONFORMATION, FUNCTION AND EVOLUTION 
JRNL        PUBL   PERGAMON PRESS, OXFORD

```

**Comment by julie-sullivan** [comment]
@josemduarte Thanks so much for spending so much time on this. User error! The old BioJava JAR was still on my classpath and that's the one this source was using. Apologies!
