### ISSUE TITLE
RCSBLigandsFactoryTest failing

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#340]
Hi @andreasprlic, 

**BioJava** build is failing in the [RCSBLigandsFactoryTest](https://github.com/biojava/biojava/blob/02952752ada4ddc0e03ce8a4eea4d78d74192aef/biojava-structure/src/test/java/org/biojava/nbio/structure/rcsb/RCSBLigandsFactoryTest.java) (line 70). The test case is hemoglobin [4hhb](http://www.rcsb.org/pdb/explore.do?structureId=4HHB). It has two types of ligands, but because of the multiple chains they appear 6 times. The test expects size 2 when obtaining the ligands list from the RCSB database, but a list of 6 ligands is returned instead. 

It is the first time I see the test failing, and I haven't seen changes in that part of the code lately. As the javadoc of the method suggests: *"If this test fails, it may be because the database changed."*. Do you know of any RCSB database changes concerning the ligand storage or representation? In that case the fix is only to change the expected size to 6.

**Comment by andreasprlic** [comment]
Hi, this test is parsing the response from

http://www.rcsb.org/pdb/rest/ligandInfo?structureId=4hhb

I'll check if anything got changed..

A

**Comment by andreasprlic** [comment]
ok, so a recent change introduced some redundancy at the web service. Will be fixed as soon as the latest code base reaches our production servers (might be too late for tomorrow's weekly update).

**Comment by andreasprlic** [comment]
fixed again now.
