### ISSUE TITLE
mmCIF parsing support for missing SITES information.

### ISSUE THREAD

**Issue by larsonmattr** [biojava/biojava#342]
BioJava should support any SITE information present in mmCIF files.  

The [Simple]MMCIFParser could read _struct_site and _struct_site_gen categories and trigger handlers in the [Simple]MMCIFConsumer to handle these loop entries to build Site classes in the BioJava Structure instance.

Supporting SITE information is present in parsing of PDB files but not yet in mmCIF.

**Comment by larsonmattr** [comment]
Implementation was merged closing this issue.

**Comment by josemduarte** [comment]
There seems to be a bug in matching the residue numbers and chains for the sites in struct_site_gen. Could you take a look? 

I've added a test here to demonstrate the issue: https://github.com/josemduarte/biojava/tree/sitesIssue

I came across this because I was seeing a lot of warnings like this while testing:
```
org.biojava.nbio.structure.io.mmcif.SimpleMMcifConsumer - comp_id doesn't match the residue at H221 - skipping
```

**Comment by larsonmattr** [comment]
Jose,

 Thanks for finding this.  It is a problem with not using the insertion
code when searching for residues.  Also related to this, there is issue
with the Site.toPDB() method not formatting SITE entries correctly for DNA
residues like DT that are three-letter codes with whitespace.

 I'll submit a fix for both issues.



On Thu, Jan 14, 2016 at 7:55 PM, Jose Manuel Duarte <
notifications@github.com> wrote:

> There seems to be a bug in matching the residue numbers and chains for the
> sites in struct_site_gen. Could you take a look?
>
> I've added a test here to demonstrate the issue:
> https://github.com/josemduarte/biojava/tree/sitesIssue
>
> I came across this because I was seeing a lot of warnings like this while
> testing:
>
> org.biojava.nbio.structure.io.mmcif.SimpleMMcifConsumer - comp_id doesn't match the residue at H221 - skipping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biojava/biojava/issues/342#issuecomment-171844414>.
>



-- 
Matt Larson, PhD
Madison, WI  53705 U.S.A.
