### ISSUE TITLE
mmCIF parsing support for missing SSBonds information.

### ISSUE THREAD

**Issue by larsonmattr** [biojava/biojava#343]
BioJava should support any disulfide bond information present in mmCIF files.

_struct_conn categories are already read by SimpleMMCIFConsumer and trigger handlers in a consumer to handle these loop entries.   The SimpleMMCIFConsumer could parse _struct_conn to build SSBond instances that are part of BioJava Structure instances.

Support SSBOND-like information parsed for PDB files but not yet in mmCIF.

**Comment by larsonmattr** [comment]
Closing this issue.  When #220 is implemented (5.0.0?) then a better representation of "connections" (StructConn) and allowing bonds between different symmetry related molecules should be developed.

**Comment by josemduarte** [comment]
There were a few issues remaining with ssbond parsing in both pdb and mmcif that should be fixed now with last commit
