### ISSUE TITLE
DNASequence.getRNASequence() translation does not respect ambiguity CompoundSet

### ISSUE THREAD

**Issue by stefanharjes** [biojava/biojava#344]
Hi biojava,

if you try:
```java
    dna=new DNASequence("AGTCS", AmbiguityDNACompoundSet.getDNACompoundSet());
    rna = dna.getRNASequence();  //fails with missing compound S
    rna = new RNASequence(dna.getSequenceAsString().replaceAll("T", "U"), AmbiguityRNACompoundSet.getRNACompoundSet()); //fails with missing compound S 
    rna = new RNASequence(dna.getSequenceAsString().replaceAll("T", "U"),  AmbiguityRNACompoundSet.getDNACompoundSet());  //works ??? should it not be RNACompoundSet?
```

The above errors resisted me quite some time, until I fell back at the .replaceAll transcription...

Regards

**Comment by josemduarte** [comment]
In my understanding there are 2 separate issues here:
 1. The 2nd line `dna.getRNASequence()` should not fail
 2. The 3rd line should work but not the 4th line

Is that understanding right?

Regarding the second issue, it looks to me like a bug [in this line](https://github.com/biojava/biojava/blob/master/biojava-core/src/main/java/org/biojava/nbio/core/sequence/compound/AmbiguityRNACompoundSet.java#L34). Replacing `getDNACompoundSet` by `getRNACompoundSet` gives the expected result (3rd line above works, 4th line doesn't). I'll commit that fix.

**Comment by stefanharjes** [comment]
Yes this is correct, thanks for the patch, however the first issue still fails

The 2nd line dna.getRNASequence() should not fail

**Comment by josemduarte** [comment]
I've had a look into the other issue but could not find what's going on, I really don't know much about this part of Biojava. In any case I'll rename the issue so that it's clear what the bug is about.
