### ISSUE TITLE
PDB output can write ATOMs out of order for alt conformations.

### ISSUE THREAD

**Issue by larsonmattr** [biojava/biojava#345]
Opening the PDB:4EA9 as a Structure, then writing back again with toPDB() produces out of order atom records for groups that had alternative conformations.  

Open the exported file in text editor and view residue 81, which has multiple conformations

The atom numbering is out of order and don't match the order that is present in the original PDB.

The problem is that BioJava uses the original Atom #'s, but writes out the Atoms per Group, with the alternative conformation as a separate Group.  If the Atoms were interspersed originally, this leads to out of order ATOM indices.  

Renumbering the ATOM indices could happen during the output, but certain records that reference Atom numbers are not currently directly tied to the Atom indices.  The way Structure.setConnections is implemented would require updating the atom indices in the map.  Perhaps a separate class for Connections that can do toPDB or toMMCIF, and directly references Atoms would help for fixing this.  Alternatively, the PDB could be written out sequentially by ATOM #, rather than descending Compound->Chain->Group->Atom as it currently does. 

Output below, with line numbers:
602:ATOM    545  N   LYS A  81     -40.593   0.406 -25.290  1.00  9.41           N
603:ATOM    546  CA  LYS A  81     -41.557   1.495 -25.060  1.00 10.36           C
604:ATOM    547  C   LYS A  81     -41.298   2.194 -23.741  1.00  9.75           C
605:ATOM    548  O   LYS A  81     -41.381   3.433 -23.664  1.00 10.67           O
606:ATOM    549  CB ALYS A  81     -42.984   0.985 -25.105  0.55 12.69           C
607:ATOM    551  CG ALYS A  81     -43.368   0.517 -26.503  0.55 15.14           C
608:ATOM    553  CD ALYS A  81     -44.791  -0.060 -26.466  0.55 20.11           C
609:ATOM    555  CE ALYS A  81     -45.271  -0.550 -27.802  0.55 26.23           C
610:ATOM    557  NZ ALYS A  81     -46.557  -1.355 -27.644  0.55 48.40           N
611:ATOM    549  CB ALYS A  81     -42.984   0.985 -25.105  0.55 12.69           C
612:ATOM    551  CG ALYS A  81     -43.368   0.517 -26.503  0.55 15.14           C
613:ATOM    553  CD ALYS A  81     -44.791  -0.060 -26.466  0.55 20.11           C
614:ATOM    555  CE ALYS A  81     -45.271  -0.550 -27.802  0.55 26.23           C
615:ATOM    557  NZ ALYS A  81     -46.557  -1.355 -27.644  0.55 48.40           N
616:ATOM    550  CB BLYS A  81     -42.946   0.873 -25.055  0.45 13.42           C
617:ATOM    552  CG BLYS A  81     -44.061   1.828 -24.750  0.45 20.17           C
618:ATOM    554  CD BLYS A  81     -45.458   1.215 -24.624  0.45 31.05           C
619:ATOM    556  CE BLYS A  81     -46.433   2.385 -24.469  0.45 37.64           C
620:ATOM    558  NZ BLYS A  81     -46.781   2.966 -25.796  0.45 49.08           N

**Comment by sbliven** [comment]
Is this a problem for you? For what use case is the order in which atoms appear in the file important?

If Structure.setConnections is referring to atom array indices in a persistent way rather than atom ids, I would consider that the bug.

**Comment by larsonmattr** [comment]
Hi Spencer,

  We haven't found that the order the atom ids appear with the PDB file
affects common protein structure viewers.  It is mostly cosmetic.  The use
case would be for writing back the structure or portions of a protein
structure after doing an operation on it.

Structures with alternative conformations are very common and a means to
iterate through Atoms in order of IDs from the Structure class or a from
model could address this and provide an easy access to coordinate data.

At present, Atoms must be accessed via Chain and Group, correct?

Best regards,
Matt

**Comment by andreasprlic** [comment]
Atoms can be accessed either via Chain->Group, or by requesting an atom array from the StructureTools

**Comment by sbliven** [comment]
If this is just a cosmetic change, I think we can close the issue. Thanks for the input.
