### ISSUE TITLE
AbstractFastqReader should be public

### ISSUE THREAD

**Issue by kerner1000** [biojava/biojava#347]
<code>org.biojava.nbio.sequencing.io.fastq.AbstractFastqReader</code> is package private, so cannot be extended.

**Comment by heuermh** [comment]
That is by design.  What is your use case for extending ```AbstractFastqReader```?

**Comment by kerner1000** [comment]
As mentioned in the other issue, I was planning to just extend <code>AbstractFastqReader</code> in order to implement a handy and performant stream/ <code>Iterator</code>-based reading.

**Comment by andreasprlic** [comment]
Can we close this ?

**Comment by heuermh** [comment]
I believe so, thanks!
