### ISSUE TITLE
Update FASTQ I/O API examples in the cookbook documentation

### ISSUE THREAD

**Issue by heuermh** [biojava/biojava#349]
The FASTQ I/O API examples in the cookbook documentation here

http://biojava.org/wiki/BioJava:CookBook3:FASTQ

have not been updated to use the latest Guava APIs (e.g. InputSupplier has since been deprecated and removed).

Mentioned in #348.

**Comment by andreasprlic** [comment]
Also, can this cookbook example get merged with the [Tutorial](https://github.com/biojava/biojava-tutorial/tree/master/genomics) ?

**Comment by heuermh** [comment]
Fixed in commit https://github.com/biojava/biojava.github.io/commit/413f6a382cc3d52f9343c2e4ee407aec652b19e8
