### ISSUE TITLE
Update the forester version (from 1.005 to 1.038)

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#350]
This is important, since the version we are currently using contains a **BUG** that allows for negative branch lengths in trees constructed with the Neighbor Joining algorithm and another bug that incorrectly calculates the branch lengths of the internal nodes. I discovered it with a simple Test that expects a tree of error zero.

This affects all the **phylo** classes (since the NJ is the only tree constructor algorithm) and the *GuideTree* class in the alignment package, used to construct progressive multiple sequence alignments (with the consequence that not necessarily the closest sequences are paired).

**Comment by sbliven** [comment]
We control the forester package on maven central, so we need to wrap the latest release in a pom and upload it. @andreasprlic did this process for 1.005, or I also have permissions to do it.

**Comment by lafita** [comment]
Now that we are discussing this, the **forester** library is mainly a tree visualization library, with very few tree inference and construction support (not very used for the inference features, thus prone to bugs like the one above).

There exist other Java libraries focused on the algorithmic part of phylogenetic tree construction. The most popular one is [Phylogenetic Analysis Library (PAL)](http://iubio.bio.indiana.edu/soft/molbio/java/pal/doc/) a general purpose library for molecular evolution and phylogenetics. Many other libraries use the code, and it covers the whole field (parsimony, distance, maximum likelihood, UPGMA, NJ, etc). 

At the bottom of the page they propose other alternatives for phylogeny in Java (and they cite BioJava as well).

**Comment by josemduarte** [comment]
The PAL project looks good but very out of date, last release was 1.4 in 2002 (http://iubio.bio.indiana.edu/soft/molbio/java/pal/). Aren't there any other more up-to-date and maintained alternatives from the list they provide?

**Comment by lafita** [comment]
I agree that the project is very old, but it looks complete and well organized. It also seems to be very popular, since other projects depend on it for the fundamental phylogenetic algorithms. 

The alternatives they provide (and that I could found to be maintained and up-to date) are either in another language or very specific to a single application. There seems to be a lack of a maintained and up-to date **general purpose phylogenetic library** in Java, which I think is a great opportunity for **BioJava**. 

An idea could be to import the code we consider relevant from the **PAL** library (and possibly other more specialized libraries) and provide support for it (testing and documentation), together with adaptation to the **BioJava** Data Structures. It seems a big project that should be well planned and with the opinion of potential users. Very interesting also!

**Comment by josemduarte** [comment]
+1 for importing code from the PAL library and provide better support for it within Biojava.

**Comment by andreasprlic** [comment]
-1 This reminds me of what we did with the Jama library. I don;t think we should swallow external libraries. Better move them to a new github location and wrap them as Maven projects. A PAL fork is here:

https://github.com/tamuri/pal

**Comment by sbliven** [comment]
-1 I also think that we should leave this to independent libraries unless someone joins BioJava who does  phylogenetic research full-time and would be willing to maintain it. I'm much more comfortable with our current approach of providing parsers & wrappers for external tools.

**Comment by lafita** [comment]
Probably **forester** is enough for what the current users of **BioJava** are doing, and I agree with @sbliven that we would need someone who is in need of more advanced phylogenetic research for the project. It was intended to be just a comment on the **forester** library and its limitations (in case the need appears in the future).

I saw that the same user that has a PAL mirror also has a phylogenetics project that uses **BioJava** parsers and wrappers (we are doing good that job then) and algorithms from PAL and other libraries. The description is: 

*A small program (which glues together other programs) that allows a user to input a codon alignment in FASTA format and produce an annotated phylogenetic tree showing which substitutions occurred on a given branch.*

Find it here: https://github.com/tamuri/treesub

**Comment by josemduarte** [comment]
Alright I think you guys are right, if there's no one around to really take care of it properly, there's no point in swallowing the PAL library in.

Regarding forester, I will be looking into adding it to maven in the next days. It will take a while because I haven't published anything to maven directly myself and I have to get permissions and all that. I'll post any progress here.

**Comment by lafita** [comment]
Thank you @josemduarte! I forgot to attach the link of the newest forester version (the one that I have tested and works correctly). This is the download link of the JAR:

https://googledrive.com/host/0BxMokdxOh-JRM1d2azFoRnF3bGM/download/forester_1038.jar

**Comment by sbliven** [comment]
@lafita Where did you find the above jar link? Is it built from the current trunk (https://github.com/cmzmasek/forester), or is it an older jar? I'm unable to find any version numbers in the source code.

Also, if you want to write code against 1.038 before @josemduarte does the mavenization, you can do a local install like this:

mvn install:install-file -Dfile=forester_1038.jar -DpomFile=forester-1.038.pom

where the pom file can be downloaded from this gist: https://gist.github.com/sbliven/7ebb27b1413c98a39dc6

If the forester devs don't want to switch from ant to maven, we can still upload the jar under org.biojava.thirdparty as before using the pom above (or an updated version thereof).

**Comment by lafita** [comment]
I got the jar from their GUI application website [Archaeopteryx](https://sites.google.com/site/cmzmasek/home/software/archaeopteryx). In the downloads section there is a download link for a jar, tagged as: **Jar file containing Archaeopteryx 0.9901 beta 2014-10-14 (based on forester 1.038)**. 

I don't know if it is build from the github repo, since the repo does not have releases and the commits since that date do not have very informative descriptions. I proposed this version because the bug is fixed and the jar available.

**Comment by josemduarte** [comment]
@lafita you can already try forester out by cloning from my fork: https://github.com/josemduarte/forester. I've got forester mavenized in there. If you build it locally it should work. In the pom.xml I set 1.038 as the version, hoping that it is the same that he published, from the commit dates it looks like it can be. Could you check if it really contains the bug fix?

**Comment by lafita** [comment]
I tried the tests with the version 1.038 jar (as @sbliven described) and they pass. I had some problems with maven in building your mavenized fork, @josemduarte. The part of the code that contained the bug is changed accordingly to the 1.038 version, but I will check with the tests to be sure.

**Comment by andreasprlic** [comment]
@josemduarte has tried to contact the original author of the forester library. Unfortunately we did not get a response. As such we should push an update version of @josemduarte 's mavenized fork from  https://github.com/josemduarte/forester to Maven Central and switch dependency to that one. 

@josemduarte , do you also want to add a readme file to your fork, that explains what is different?

**Comment by lafita** [comment]
I think this is a good solution, with the only drawback that we will not be able to update to newer versions of **forester** if they come in the future (unless they include @josemduarte pull request with mavenization). 

If we need more **features** for phylogenetics in BioJava in the future, though, I will consider other options (like the PAL, discussed above).

**Comment by andreasprlic** [comment]
based on the lack of response of the forester developer, I doubt there will be future versions of the library.

**Comment by josemduarte** [comment]
Forester 1.038 should be now available. Let me know if something doesn't work.

**Comment by lafita** [comment]
Thank you @josemduarte! Everything works fine and tests pass (bug fixed) since 6c4fbc165b39628f1f4d95ae825aede5fd343c7e.
