### ISSUE TITLE
mmCIF SimpleMMcifConsumer incorrectly replaces residue numberings.

### ISSUE THREAD

**Issue by larsonmattr** [biojava/biojava#359]
The SimpleMMcifConsumer class currently replaces residue numbers for Group instances when it parses the _pdbx_poly_seq_scheme.  

1. In multi-model structures, this replacement only searches through the previous 1..N-1 models, as the last current_model does not get added until documentEnd() is reached.  This will cause the models to have out-of-sync numberings.

2. With the example of the model PDB:2KSA, performing this renumbering based on the pdbx_poly_seq_scheme actually incorrectly renumbers residues.  Instead, it seems sufficient to rely on the original _atom_record numbers that would then agree with the PDB entry for 2KSA.  All the current unit tests for pdb/mmcif consistency pass with the renumbering by _pdbx_poly_seq_scheme disabled.

At least fix for (1) would correct the issue, but I am wondering if it would be best to avoid this issue completely by preventing renumbering as suggested by (2)?

I can submit a pull request with related changes but would like a comment if disabling the renumbering should be part of this fix.

**Comment by josemduarte** [comment]
Indeed 1) is clearly a bug. Regarding 2) it does sound like a reasonable approach in principle. However I don't fully understand what part of the code you refer to. I suppose it is the `replaceGroupSeqPos()` method? Could you point to the which part of the code you are referring to, or alternatively create a branch with a test demonstrating the issue for 2ksa?

**Comment by larsonmattr** [comment]
Jose, thanks for looking in on this.  

I've created a branch https://github.com/edlunde-dnastar/biojava/tree/mmcif-seqres that incorporates (1) the fix for the finding all chains in all models, and (2) disables the `replaceGroupSeqPos()` method that causes mis-numbering.  A unit test for 2KSA is in the TestDifficultMmCIFFiles.java.  The first listed residue ASP in chain A, should be residue 2.  This is correctly specified by the _atom_site records, but made incorrect by later changing again in `replaceGroupSeqPos()`.  I think trying to renumber by the _pdbx_poly_seq_scheme is actually incorrect/unnecessary here.

Take a look.  The first change would fix the bug (1) only.

**Comment by josemduarte** [comment]
Great, thanks for the explanation and the test. To me both changes look good, it does seem like `replaceGroupSeqPos()` was not doing anything useful, perhaps it is some left-over from the past and it's not needed anymore. 

If you can submit a pull request, that would be great.

**Comment by larsonmattr** [comment]
Thanks Jose, I've submitted the PR for this.
