### ISSUE TITLE
need to download files from NCBI according to Taxonomy ID

### ISSUE THREAD

**Issue by ylzheng** [biojava/biojava#367]
Hi ,
I need to download files from NCBI according to Taxonomy ID,  can not find a loader by Taxonomy.
Any suggestion?

Thank you!

**Comment by andreasprlic** [comment]
Did you take a look at the NCBI eutils? e.g. http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9913,30521
