### ISSUE TITLE
"Content-Length" of "2000" is incorrect in NCBIQBlastService.java should be set to "200"

### ISSUE THREAD

**Issue by Biobytes1** [biojava/biojava#369]
biojava/biojava-ws/src/main/java/org/biojava/nbio/ws/alignment/qblast/NCBIQBlastService.java

On http://www.ncbi.nlm.nih.gov/BLAST/Doc/node1.html they specify it should be set to "200"

**Comment by josemduarte** [comment]
Thanks! now fixed
