### ISSUE TITLE
incorrect dependency specificatiopn in biojava.org wiki

### ISSUE THREAD

**Issue by cswarth** [biojava/biojava#374]
Documentation issue in the wiki on biojava.org, but I can't figure out where else to report it.
I'd fix it myself but the OpenId authentication won't let me in regardless of which method I use.
Hopefully someone here can help get this fixed, as it's really annoying to run into this when starting out with `maven` and `biojava`

http://biojava.org/wiki/BioJava:GetStarted#Maven

The dependency specifications are incorrect and will not work.  
```
$ mvn -q -U compile
[ERROR] Failed to execute goal on project testing: Could not resolve dependencies for project org.fredhutch.coalescent:testing:jar:1.0-SNAPSHOT: 
Could not find artifact org.biojava:biojava3-core:jar:4.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 

```

The correct specification should not have `biojava3`, i.e. this will work:
```
 <dependency>
        <groupId>org.biojava</groupId>
        <artifactId>biojava-core</artifactId>
        <version>4.0.0</version>
 </dependency>
```

However since any recipie included in the wiki will be out of date, perhaps this shold just provide a link to  http://mvnrepository.com/artifact/org.biojava/biojava-core

**Comment by andreasprlic** [comment]
I updated the wiki. I think more and more of our documentation is now here on GitHub ...
