### ISSUE TITLE
Remove guava dependency from sequencing module

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#375]
The sequencing module currently uses Google Guava for some utility functions. Should we rewrite these as vanilla java and remove the dependency? From a quick glance they look fairly easy to do without (only 4 classes; mostly stuff with an obvious, if less elegant, equivalent).

**Comment by darnells** [comment]
If Google is providing and maintaining the utilities, why would BioJava want to take ownership and the overhead of re-implementing and maintaining them? I support the idea that an extra dependency is acceptable (especially a light-weight one like Guava) when it allows a team to focus less on frameworks and more on achieving project goals. (I'll step off my soapbox now.)

**Comment by dmyersturnbull** [comment]
I'd actually recommend no in this case. Guava has enough useful features that perhaps it should be used _more_ rather than less. Examples: Ranges, multimaps/multisets, immutable collections.

**Comment by josemduarte** [comment]
I would also not support removing guava if it's doing a good job and someone else is maintaining it for us, +1 to @darnells comment.

See also issue #335 that relates to guava: as @heuermh says, guava's Range API could do a better job than we do in dealing with intervals.

**Comment by andreasprlic** [comment]
We had a discussion (on the mailing list?) before introducing the dependency on Guava. Let's not revert this decision. 

I believe the -core module should be free of dependencies, but the other modules are ok to depend on a library that provides benefit and saves devel time (such as Guava).

**Comment by darnells** [comment]
According to the mail archives, Guava was first added as a BioJava dependency (biojava3-sequencing) back in March 2012: http://mailman.open-bio.org/pipermail/biojava-dev/2012-March/007254.html

From @heuermh, "I also hesitate to add new external dependencies, but Guava I/O and collections are invaluable; I wouldn't have been able to get the performance gains with out them."

There did not appear to be any further resistance after his comment.

**Comment by heuermh** [comment]
Is the problem the upstream project (https://github.com/eppic-team/eppic) needs to use biojava-sequencing via GWT?  Much of guava is already GWT compatible, do we just need to add GWT annotations?

Without a strong reason to make a change, I would prefer to keep the dependency in.

**Comment by sbliven** [comment]
> perhaps it should be used *more* rather than less.

+1

I am on board with this sentiment. I just wanted to check we had consensus for it.
