### ISSUE TITLE
Add option for more memory efficient implementation of HetatomImpl

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#391]
The atomNameLookup HashMap is likely to consume a lot of memory for large structures. Add an option for a more memory efficient behavior (at the cost of slower performance when looking up atom names) for large structures, which does not need this map.

**Comment by josemduarte** [comment]
We should also try to make AtomImpl as slim as possible in memory.

**Comment by andreasprlic** [comment]
somehow 14f7a53a42a08537523d92d161d0bfe4355ce425 does not show up here, but it is addressing part of this.

**Comment by andreasprlic** [comment]
I removed the hibernate-ID field from the AtomImpl. Thanks @josemduarte  for the suggestion. It makes no sense to support this. Serialization of atoms to a database has really bad performance and should not be done.

**Comment by andreasprlic** [comment]
What is a good use case for benchmarking atom-name lookup behavior?

**Comment by andreasprlic** [comment]
Groups and Atoms are now more memory efficient. In the future we perhaps can remove the atom name lookup table completely, but for now I am reluctant to do so, until we did some more benchmarking on applications that need to access all atoms. 

The default behavior from now is is NOT to use the lookup table and therefore have less memory requirements.
