### ISSUE TITLE
Bug in display of alignment identity and similarity

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#430]
Reported by Art Nasamran (email):

 If you try DemoSW3DAligner.java from biojava-structure-gui and align 1CDG.A and 1TIM.A, the console says:
"Align 1CDG.A.pdb 686 with 1TIM.A.pdb 247

Twists 0 ini-len 0 ini-rmsd 0.00 opt-equ 56 opt-rmsd 13.21 chain-rmsd 13.21 Score 39.00 align-len 71 gaps 15 (21.13%)

Afp-num 0 Identity 37.50% Similarity 58.93%"

while View -> View Text Only from the text window shows: 

"Align 1CDG.A.pdb Length1: 686 with 1TIM.A.pdb Length2: 247

Equ: 56 
RMSD: 13.21 
Score: 39.00 
Align-len: 71 
Gaps: 15 (21.13%)
TM-score: 0.00

Identity: 29.58% 
Similarity: 46.48%"

Why are the identity and similarity percentages different?

**Comment by lafita** [comment]
_Identity_ is the percentage of aligned residues that are **equal** (identity scoring matrix) and _Similarity_ is the percentage of aligned residues that are similar, where similarity is assessed by a scoring matrix (and a similarity threshold is set by default).

Similarity will always be higher than identity.

**Comment by emckee2006** [comment]
It sounds like the two views disagree about the actual values, though.
Each reports similarity and identity, but the views disagree  (e.g.
identity in view 1 is different from identity in view 2).

**Comment by lafita** [comment]
Sorry I misunderstood the issue. There is definitely a bug (or the calculation method is different) between the **Alignment Panel** and the **Text Only** views. 

I remember that some display options recalculated the superposition and alignment from the AFPChain.

**Comment by altayhunoglu** [comment]
As far as I understand, while finding percentage of similarity and identity; code on the console side uses this: 
 	       

>  afpChain.setIdentity(nrIdent*1.0/pos);
> 		afpChain.setSimilarity(nrSim*1.0/pos);

 In this case pos= 56 (aligned positions)

 But in the code of **"View -> View Text Only**" the algorithm uses 71 (Align-len) instead of 56 (aligned positions)

**Comment by josemduarte** [comment]
This was fixed, right @andreasprlic ?

**Comment by andreasprlic** [comment]
based on the history of this ticket, yes!
