### ISSUE TITLE
Add Bird parsing functionality

### ISSUE THREAD

**Issue by abradle** [biojava/biojava#436]
We should add functionality to parse "BIRD" information from the PDB. 

Available here:

ftp://ftp.wwpdb.org/pub/pdb/data/bird/prd/

I have started work on this on a feature branch.

**Comment by andreasprlic** [comment]
You can try to see how far you get with the ChemCompConsumer (there are some similarities), but prob. this needs a new MMcifConsumer .

**Comment by josemduarte** [comment]
Parsing for BIRD data is now possible thanks to the new more generic parser of any CIF data introduced in #912  (thanks to https://github.com/rcsb/ciftools-java). I'll close this. Another separate issue is adding support for BIRD data in the BioJava data structure.
