### ISSUE TITLE
JavaDoc linting (java 8)

### ISSUE THREAD

**Issue by abradle** [biojava/biojava#438]
By default Java 8 is very strict with doclinting. It will fail unless the docs are appropriately documented. See:
http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

We have two options to get round this for builds. 
1) Alter the pom.xml to not be so strict
http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete

2) Convene to the standards...

My suggestion would be 1) (and it's what I'm doing for the alpha release). But I thought it should be discussed.

**Comment by sbliven** [comment]
Both?

**Comment by sbliven** [comment]
Maybe a third option would be to switch to a more powerful doc parser. The [pegdown-doclet](https://github.com/Abnaxos/pegdown-doclet) lets you use markdown and PlantUML, in addition to the standard html syntax. It even has IntelliJ support (although not Eclipse, afaik).

**Comment by andreasprlic** [comment]
I like both. 

Can the alternative doc parser get hooked up with mvn release? 

A

**Comment by josemduarte** [comment]
I'd vote against doing non-standard docs. As good and easy-to-use as the markdown thing can be, the fact that it is non-standard makes it difficult for other people (possibly used to normal javadocs elsewhere) to contribute javadocs.

Also there are tons of tools to deal with javadoc following the standard, if we move away from that, we won't be able to use those. A standard might be bad, but its power resides precisely in that it's standard and everyone has agreed to use it.

I'd say that realistically we'd need to keep the non-strict parsing mode as @abradle suggests, while trying to fix as many as possible of the broken docs.

**Comment by heuermh** [comment]
I vote for 2) Convene to the standards...

**Comment by josemduarte** [comment]
I'll close this one for now. We'll have to keep improving the javadocs going forward.
