### ISSUE TITLE
Add public code signing keys for all release managers to KEYS

### ISSUE THREAD

**Issue by heuermh** [biojava/biojava#447]
Our [https://github.com/biojava/biojava/blob/master/KEYS](KEYS) file only has public code signing keys for Spencer, Andreas, and myself.

**Comment by josemduarte** [comment]
I've also pushed my key now

**Comment by heuermh** [comment]
Are there any other folks that may want to cut releases?  If not I can close this issue.

**Comment by josemduarte** [comment]
@abradle might want to add his key too?

**Comment by sbliven** [comment]
I'm going to close for now. If @abradle expects to make a release he is of course welcome to add a key.
