### ISSUE TITLE
Biojava 3 downloads missing

### ISSUE THREAD

**Issue by holtgrewe** [biojava/biojava#451]
Is this an oversight? Also see here: https://github.com/cBioPortal/cbioportal/issues/1038

The (apparently copied over Wiki page for 3.0.7 still says it's available from biojava.org http://biojava.org/wikis/BioJava:Download_3.0.7/)

**Comment by heuermh** [comment]
@holtgrewe the former site hosting for http://biojava.org is down, including unfortunately the biojava maven repository.  Some content has been migrated to https://github.com/biojava/biojava.github.io but not javadoc, downloads, or the maven repository yet.

In the meantime, I'll see if I can help upstream migrate to a biojava version available from Maven Central.

**Comment by holtgrewe** [comment]
@heuermh If you could help the cbioportal guys, that would be awesome!

**Comment by heuermh** [comment]
Fixed upstream in https://github.com/cBioPortal/cbioportal/pull/1066.

This issue should remain open until we migrate the Biojava Maven Repository over to Github hosting or otherwise figure out a way to host those files.

**Comment by pgleeson** [comment]
It would be great to get this fixed. We have a number of builds failing due to Biojava Maven repos not available at http://biojava.org/download/maven/:

https://travis-ci.org/NeuroML/org.neuroml.import/jobs/108932145
https://travis-ci.org/NeuroML/NeuroML2/builds/122573640

Thanks!

**Comment by andreasprlic** [comment]
I added this to https://github.com/biojava/biojava.github.io/issues/4

**Comment by andreasprlic** [comment]
@pgleeson I notice that you are using the biojava 1 series. If you upgrade to BioJava 1.9.2, that's available from Maven Central.

**Comment by andreasprlic** [comment]
I looked at simply moving the biojava maven repo over to its own git project. However the repo is too large and takes about 4 GB. Too big for the maximum Github project size.

**Comment by phidias51** [comment]
Andreas,
I wonder if bintray would would work.

Mark

**Comment by andreasprlic** [comment]
It might! Just doing some read-up how to bulk upload. We need this, since we have a lot of jar files that need to be included.

**Comment by sbliven** [comment]
We could manually attach binaries to github releases. For major release I think this would be a very good idea (they can have the release notes attached). Hosting binaries on github seems preferable to an external solution like bintray. I wonder if there's a way to automate this in maven, so that alpha builds can also have binaries (if that's even desirable). I'll do the 4.1.0 release as a demo.

**Comment by andreasprlic** [comment]
@sbliven our releases are usually a collection of several jars. That sounds like a lot of manual work. I'd hope for something more automated.

**Comment by sbliven** [comment]
@andreasprlic Rereading this thread, I think I was misunderstanding the issue. I thought we were talking about full releases. I realize now that the repo was used mostly for snapshots, so my comments didn't apply.

(Posting release notes on github is still a good idea and shouldn't take any more work than posting to the wiki used to).

Could we purge some old snapshots to get the repository down to <4GB? For instance, there are 251 jars for the protein-comparison tool and >10000 pom files for the symmetry module (although only 12 jars). I don't see a point in keeping snapshots for versions that were actually released.

**Comment by andreasprlic** [comment]
@sbliven You are right, the SNAPSHOT builds take most space and we don't need to host them. I think I can get a GitHub based repo to work, when excluding SNAPSHOT builds.

**Comment by andreasprlic** [comment]
The repo is up and running. New location:

https://github.com/biojava/maven-repo/tree/master

You can add it to your project's pom.xml by adding

```xml
<repository>
    <id>biojava-legacy-repo</id>
    <name>BioJava's Git based legacy maven repo</name>
    <url>https://github.com/biojava/maven-repo/raw/master/</url>
</repository>
```

**Comment by pgleeson** [comment]
The new repository location works fine for us now. Thanks!

@andreasprlic the choice of Biojava version to use was set by another package we use (jSBML) so we didn't have a choice to change it, but everything works now.

**Comment by andreasprlic** [comment]
@pgleeson  you could have overwritten and excluded this dependency by using something like this:

```xml
 <dependency>
      <groupId>org.sbml.jsbml</groupId>
      <artifactId>jsbml-core</artifactId>
      <version>${jsbml.version}</version>
      <exclusions>   
                <exclusion>
                    <groupId>org.biojava</groupId>
                    <artifactId>core</artifactId>
                </exclusion>               
      </exclusions>
    </dependency>
```

**Comment by pgleeson** [comment]
@andreasprlic thanks for the tip!
