### ISSUE TITLE
Default parsing params for AtomCache

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#455]
I recently got tripped up by the fact that AtomCache's constructor disables alignSeqRes and parseSecStruc specifically.

```{java}
// we don't need this here
params.setAlignSeqRes(false);
// no secstruc either
params.setParseSecStruc(false);
```

The current default for FileParsingParams.alignSeqRes is true. I would have expected `cache.setFileParsingParams(new FileParsingParams())` to reset a cache to its default state, but this is not true.

Would anyone object if I deleted the above two lines, making `alignSeqRes=true` the default?

**Comment by josemduarte** [comment]
That looks like a bug indeed. Go ahead, it'd be good to have this for 4.2.1

**Comment by josemduarte** [comment]
Could you push the fix to `master` and `bugfixes-4.2`? 

I think we should be ready for a 4.2.1 release after that. Or are there any other patches coming?

**Comment by josemduarte** [comment]
Oh sorry, I now saw the pull request. Let's merge that one then...

**Comment by josemduarte** [comment]
I've cherry-picked it to `bugfixes-4.2` too. I'll try to produce the 4.2.1 release later.

**Comment by sbliven** [comment]
Thanks, @josemduarte. I meant to make the pull request directly into bugfixes-4.2 but accidentally used master instead.
