### ISSUE TITLE
Groups mapping to multiple residues in sequence, how to deal with them?

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#457]
Some groups in PDB structures can map to more than 1 residue in the sequence. The chemical component dictionary gives several letters for them in `_chem_comp.one_letter_code` instead of the usual single letter. This happens for instance in many chromophores appearing in GFP proteins.

Some examples:
- `CRO` residue in 1ema (chain A)
- `CR2` residue in 3dqj (chain A)
- `SUI` residue in 1oew (chain A)
- `NRQ` residue in 3cfh (chain A)

In my opinion this is badly modelled in the mmCIF files: they should be modelled as multiple groups not to break the 1-to-1 relationship between groups and residues in the sequence. 

Anyway for the moment this is an issue in biojava that can lead to inconsistencies when going from seqres groups to sequence and viceversa. At the moment `Chain.getSeqResSequence` will produce the sequence with multiple letters for these groups, thus resulting in a sequence with longer length than the size of `Chain.getSeqResGroups`.

**Comment by andreasprlic** [comment]
I'd say this is a feature. BioJava is representing the data as it is encoded in the mmcif files and chemical component dictionary. 

https://github.com/biojava/biojava-tutorial/blob/master/structure/special.md
