### ISSUE TITLE
add a unit test for correct behavior of Chromophores

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#460]
We don't have any unit tests for testing the representation of chromophores in green fluorescent proteins.

See https://github.com/biojava/biojava-tutorial/blob/master/structure/special.md

**Comment by josemduarte** [comment]
See also #457

**Comment by MaxGreil** [comment]
Hi @josemduarte ,
I would like to take on this issue. Can you please explain what needs to be done here?

**Comment by josemduarte** [comment]
Thanks for offering help @MaxGreil . I've been looking into this and I'm not sure what we could test. I'd rather close this one which is not very clear in scope.

I'm looking at other issues that you could contribute to. I'll ping you in other issues to ask if you are interested.
