### ISSUE TITLE
Unit tests don't compile

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#463]
Currently NCBI's eutils are down, so the BioJava unit tests won't compile.

**Comment by andreasprlic** [comment]
E.g. GenbankCookbookTest tries to access

 http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=protein&id=NP_000257&rettype=gb&retmode=text

**Comment by andreasprlic** [comment]
and eutils seem to  be back....

**Comment by andreasprlic** [comment]
and eutils is down again. Let's move the genbank files into the tests/resources folder so we don't have this external dependency which is beyond our control.

**Comment by lafita** [comment]
Instead of closing, we can leave it for the next release together with the reduction of other Network dependencies in the unit tests.

**Comment by lafita** [comment]
A new issue specific for that has been created #606, so I will close this.
