### ISSUE TITLE
Add better support for asym chain ids as well as auth ids

### ISSUE THREAD

**Issue by abradle** [biojava/biojava#469]
Meeting notes from a discussion between @josemduarte @arose @andreasprlic @abradle : 

We can improve the support for working with both public (authId) and private (asymId) chain IDs assigned by PDB by adding several new methods to the Structure interface:

* `getChainByPdb(String authId);` (the current behavior)
* `getPolyChain(String asymId);`
* `getNonPolyChain(String asymId);`
* `getPolyChainByPdb(String authId);`
* `getNonPolyChainByPdb(String authId);`

Underlying we can store both asymId as well as authId in chain.name and chain.id;

`chain.getId()` will now respond with asymId; (note: currently getId() returns a Long, first take out from interface, then refactor chain.getInternalChainId() to getId() )
`chain.getName()` will now respond with authId; (note: currently called getChainID() , needs to be refactored to getName();

Internally the Structure object will contain a list of Chain objects, where polymeric and non-polymeric chains will be represented separately. Each chain will have a unique Id (asymId) but one polymeric and one non-polymeric chain can share the same name (=authId, =public PDB chain Id).

`Structure.getChainByPdb()` currently returns one chain. With this change, we will introduce a new `ChainCollection` class that implements `Chain` and contains a collection of polymeric and nonpolymeric ChainImpls that share the same authId (name).

`Structure.getChains()` will return a List of `ChainCollection`s.
`Structure.getPolyChains()` will return all polymeric chains.
`Structure.getNonPolyChains()` will return all non-polymeric (ligand) chains.

**Comment by josemduarte** [comment]
A note: the model above __is essentially the mmCIF data model__. When parsing from PDB files (which don't naturally adhere to this data model) we would have to find the different parts of the chains that are polymeric/non-polymeric to be able to create the data structure as above (including creating some fake asym_ids).

**Comment by andreasprlic** [comment]
I have an initial version of this working in my branch. However there are now still a lot of problems with unit tests that need to be addressed.

**Comment by andreasprlic** [comment]
I have fixed many unit tests that got broken because of this (mostly minor data changes due to ligands now being in their own chains). Currently 27 / 297 unit tests are failing. @abradle  can you take a look a the test related to bonds? @josemduarte can you take a look at the ASA test?

**Comment by andreasprlic** [comment]
fixed with #479
