### ISSUE TITLE
Support BIOL prefix for BioAssemblyIdentifiers

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#474]
In the _javadoc_ of [StructureIO](https://github.com/biojava/biojava/blob/30ce63e5a64c0c790279902012029fdb977d0707/biojava-structure/src/main/java/org/biojava/nbio/structure/StructureIO.java#79) the **BIOL** prefix is suggested as the format to specify and parse biological assemblies. Should we support it in addition to **BIO**, or should we change the _javadoc_?

**Comment by josemduarte** [comment]
+1 to change javadoc

**Comment by sbliven** [comment]
This might have originated from the BioUnitDataProvider class, which uses "biol" in some (but not all) of the function names.

Actually, the name in conventions for biological assemblies are a mess. We have classes and methods using "BioUnit," "BioAssembly," "BiolAssembly" and "BiologicalAssembly".

**Comment by andreasprlic** [comment]
todo: remove classes and rename some prefixes

**Comment by josemduarte** [comment]
PR #739 should fix this. @lafita please could you review and close the issue?
