### ISSUE TITLE
RemoteBioUnitDataProvider broken

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#476]
RCSB seems to no longer provide the biological assembly REST service. This completely breaks RemoteBioUnitProvider, which appears to have never been fully implemented anyways. I vote we remove it entirely and always parse BAs from the file header.

While we're in there, maybe we should standardize the way we refer to biological assemblies in class names and public methods. I vote we use "BioAssembly" and rename classes with "BioUnit", "BiolAssembly", etc.

**Comment by sbliven** [comment]
Note that naming issues were mentioned in #474.

For posterity, here is some code to test the RemoteBioUnitProvider, since it doesn't have a unit test.

```{java}
String name = "4hhb";

BioUnitDataProviderFactory.setBioUnitDataProvider(BioUnitDataProviderFactory.remoteProviderClassName);
BioUnitDataProvider biounit = BioUnitDataProviderFactory.getBioUnitDataProvider();

if( ! (biounit instanceof RemoteBioUnitDataProvider)) {
	System.err.println("Got wrong instance: "+biounit.getClass().getSimpleName());
	System.exit(1); return;
}

if( ! biounit.hasBiolAssembly(name)) {
	System.out.format("%s has no biol assemblies%n",name);
	return;
}

int num = biounit.getNrBiolAssemblies(name);
System.out.format("%s has %d biol assemblies:%n",name,num);

for( int i=0;i<num;i++) {
	List<BiologicalAssemblyTransformation> transforms = biounit.getBioUnitTransformationList(name, i);
	System.out.format("pdb%d has %s transforms%n",i,transforms.size());
}
```

**Comment by josemduarte** [comment]
+1 to removing it

**Comment by josemduarte** [comment]
I've discovered recently that the `PDBBioUnitDataProvider` does not actually go to the PDB file but instead reads the mmCIF file. So that functionality is also broken. I think the whole bioassembly creation could be a lot simpler: I'd say we could simply remove the whole `org.biojava.nbio.structure.quaternary.io` package and create bioassemblies from the file header, simplifying the interfaces enormously. I'm working on a pull request that does that.

**Comment by andreasprlic** [comment]
+1 for deprecating this code. I think there are mostly historic reasons why this is there.

**Comment by josemduarte** [comment]
Now removed after pull request #490
