### ISSUE TITLE
Cleanup issues

### ISSUE THREAD

**Issue by m-ezzat** [biojava/biojava#484]
Here are some rules exist in biojava, and each of them has a number of occurrences:

https://dev.eclipse.org/sonar/coding_rules#q=squid:S2039
https://dev.eclipse.org/sonar/coding_rules#q=squid:S106
https://dev.eclipse.org/sonar/coding_rules#q=pmd%3AImmutableField
https://dev.eclipse.org/sonar/coding_rules#q=pmd%3AUseStringBufferForStringAppends
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00115
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00116
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00117
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS3052
https://dev.eclipse.org/sonar/coding_rules#q=squid:CommentedOutCodeLine

**Comment by heuermh** [comment]
All of these rules sound reasonable and non-controversial to me.

**Comment by josemduarte** [comment]
Agree, they all sound reasonable. Some of them even essential.

Regarding logging (rule https://dev.eclipse.org/sonar/coding_rules#q=squid:S106), note that we are using the slf4j API for logging (see #155). Any conversion from stdout/err printing should be refactored into slf4j logging.

**Comment by josemduarte** [comment]
I'll close this, we'd like to add SonarQube support in CI which will handle this. See #924
