### ISSUE TITLE
VersionEye dependency badges appear to be broken

### ISSUE THREAD

**Issue by heuermh** [biojava/biojava#523]
The VersionEye dependency badges in all the module readme files appear to be linked incorrectly, to a project name: biojava/biojava3-sequencing (53f8bf2ee09da3cc0f0003a4), which is certainly no longer valid.

There's also a warning message "Project could not be parsed from the GitHub API. Please make sure that the credentials are still valid and the repository still exists."

Do these all need to be updated or should we remove them?

**Comment by andreasprlic** [comment]
need to update the hooks in versioneye, or perhaps remove this hook again. Do people find this useful?

**Comment by andreasprlic** [comment]
I re-imported the main pom.xml. Versioneye now has better support for hierarchical Maven projects, such as BioJava. I updated several README.md files in various modules to contain the new links, and also updated several versions in the main pom.xml

**Comment by heuermh** [comment]
Thanks, @andreasprlic!  Looks better.
