### ISSUE TITLE
Embedded HTTP server for HTML/JS based GUIs

### ISSUE THREAD

**Issue by sbliven** [biojava/biojava#529]
While BioJava is primarily intended for programmatic use, it is often useful to present data to users after an analysis. For instance, BioJava provides the structure-gui package for this, e.g. for interacting with Jmol.

With the obsolescence of applets, Java GUIs are no longer a viable way to interface with BioJava through a browser interface. Rather than requiring all client code to be written twice, it would make more sense to make HTML/Javascript the new default way to create GUIs. This could be enabled by embedding a lightweight HTTP server in a BioJava module, similar to how servers are shipped with many workflow engines, ipython notebooks, etc.

The goal would be to create a new biojava module for launching the server, converting Java data structures to JSON, and perhaps some HTML/JS templates for common tasks. The line between reusable code (belonging in BioJava) and application-specific code (belonging in client libraries) is likely to be blurry and would have to be discussed carefully. Likewise, we should discuss what types of data should be handled (e.g. should it include both structure and alignment module dependencies if we want to display both structure and sequence data?).

This could potentially be a project for the [BOSC Codefest 2016](https://www.open-bio.org/wiki/Codefest_2016) ([Project List](https://docs.google.com/document/d/1XQr4xgVneR9PopAdyrGH-DogKju5Lzn30J5Ak2Ugbc4/edit?usp=sharing)).

**Comment by andreasprlic** [comment]
I don't think a http server should be part of the core-biojava release. However this could be a derived project that can still get developed under the biojava umbrella.

**Comment by sbliven** [comment]
Prototype at https://github.com/biojava/biojava-http
