### ISSUE TITLE
Merge Genomics and Sequencing modules

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#536]
The genomics and sequencing modules are very similar. With #534  they now both depend on the Guava library. Is there any strong reason to keep them separated? I feel the overall organization would be simplified if the two modules would be merged.

**Comment by josemduarte** [comment]
+1 for merging

**Comment by heuermh** [comment]
Package and module names usually match.  Would this involve a package name change?

**Comment by andreasprlic** [comment]
I'd say no package name change.

**Comment by heuermh** [comment]
I'm +0 then, I think they're ok where they are but won't stand in the way of progress  :)

**Comment by josemduarte** [comment]
Working on a pull request for this.
