### ISSUE TITLE
CATH installation broken due to organizational changes

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#544]
The `CathDomainTest` has been failing for some time (two weeks at least). I have been looking at the **CATH** webpage and I noticed that the downloads format and directory structure has changed.

At the top level there is a [README](http://download.cathdb.info/cath/cath-download.README), which contains information about the new organizational structure. Interesting is that they plan to release a new **CATH** version every 12 months, and release in addition a daily domain classification, in order to keep the database up to date with the **PDB**. The latest release of `CATH-Gene3D (v4.1)` was released this July 2016.

I could not find any news message in the webpage announcing the changes, so I find strange that the old link http://release.cathdb.info is down. It seems to have been moved to http://download.cathdb.info. However, because the directory structure has changed (now there is `latest`, `daily` and `previous` directories), we cannot just replace the link, but we have to adapt all links to the new structure.

All of this are good news, but requires some work on our side. Should we contact them for more information?

**Comment by josemduarte** [comment]
I've written to their support forum to ask about it. Haven't got an answer yet.
