### ISSUE TITLE
Maximum RMSD Parameter for SmithWaterman3D Aligner

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#552]
I think that a useful feature for the structural alignment algorithm `SmithWaterman3Daligner` would be to take a maximum **RMSD** as parameter and drop alignment columns iteratively (the column with highest distance each step) until the the **RMSD** of the alignment is lower than the specified.

This is similar to what **PyMol** does with the [align command](http://pymol.org/dokuwiki/doku.php?id=command:align).

I have been looking at the `SmithWaterman3Daligner` class and found this comment:

> version history:
>  1.1 - Added more parameters to the command line, including -maxOptRMSD
>  1.0 - Initial version

The parameter **-maxOptRMSD** sounds like what I am describing here, but I could not find any such parameter in the `SmithWaterman3DParameters` class, nor in the rest of the algorithm code. 

Does anyone know if this feature was implemented?

**Comment by andreasprlic** [comment]
Agreed re. usefulness. I think @sbliven and I were discussing this at some point but I can't remember that we actually had a working implementation of this.

**Comment by sbliven** [comment]
I don't think we ever did any code along these lines.

Besides dropping columns, shifting gap boundaries can often improve RMSD considerably. For instance, SW doesn't include double gaps, so you often end up with a residue from the start of an unaligned loop getting aligned to one at the opposite side of the insertion.
