### ISSUE TITLE
Add reporting for code coverage 

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#561]
Currently we don't have any reports on the code coverage. Add support for e.g.  https://coveralls.io/

see also 

http://blog.eluder.org/2013/06/code-coverage-for-github-hosted-java-projects-with-coveralls

**Comment by sbliven** [comment]
I'm scared to see what our coverage is o_o

**Comment by andreasprlic** [comment]
quick status update: there are a few problems with this

- log files length > 4 MB cause Travis to be unhappy
- cobertura plugin has problems with MMCifFileTools.java 
    (I suspect with ```getFields(Class<?> c) ```
- when running locally, problems with ```SymmetryTools.getQuaternarySymmetry(CeSymmResult)``` (stream operation on collections causing problems?)

**Comment by andreasprlic** [comment]
running ```mvn cobertura:cobertura coveralls:report``` from command line currently fails with:

 Build error: Line number 91 is greater than the source file biojava-structure/src/main/java/demo/DemoFATCAT.java size -> [Help 1]

**Comment by sbliven** [comment]
I'm guessing that comes from the fact that we have two demo.DemoFATCAT classes. The one from biojava-structure has 87 lines, while biojava-structure-gui has 101.

**Comment by andreasprlic** [comment]
With the latest commits on my branch, I could complete a run. Results should show up here soon https://coveralls.io/jobs/17327290

**Comment by andreasprlic** [comment]
I don't see an immediate work around to the problem of the long-log file. This is an issue with Travis: https://github.com/travis-ci/travis-ci/issues/3865

For now, #555 allows users to run the coverage reports locally. We can come back to this once the Travis issue can be addressed.

**Comment by andreasprlic** [comment]
Btw: currently we have about 38% code coverage.

**Comment by phidias51** [comment]
Andreas,
If the log file is configured using a rolling appender, you should be able
to skirt the file size issue.

Mark

**Comment by andreasprlic** [comment]
so, the problem is not to run this locally, but using the travis-ci engine at https://travis-ci.org/biojava/biojava . This service terminates a build if the log is too long. If I configure a rolling appender, that would influence my local builds, but it would not change the behavior of travis-ci. Do I understand that correctly?

**Comment by josemduarte** [comment]
A possible easy fix for the too-long log problem is to switch the logging level to warn for travis. In any case going forward we should really try to cut the verbosity of some of the tests.

**Comment by phidias51** [comment]
Hi Andreas,
Changing the log level would help, as would not dumping out sequences. :-)
I assume that every module has its own test log; if not, that might help as
well.  Setting the rolling appender size would further reduce the log size,
by causing the log to roll over to another file whenever it reaches a
predefined limit.  You end up with a series of log files (test.log.0,
test.log.1, etc).

Hope this helps,

Mark

**Comment by andreasprlic** [comment]
working on reducing verbosity of unit tests. See #555

**Comment by rmoszczynski** [comment]
Why do not use [Atlassian Clover](https://www.atlassian.com/software/clover)? 

A powerful code coverage tool supporting [20+ metrics](https://confluence.atlassian.com/display/CLOVER/%3Ccolumns%3E+element). Here is a nice Clover/Cobertura [comparison](https://confluence.atlassian.com/display/CLOVER/Comparison+of+code+coverage+tools). 

And it's for free for open source projects https://www.atlassian.com/software/clover/pricing.

BTW: We can set a static code analysis tool on top of that for example [SonarQube](http://www.sonarqube.org/) aggregating additional code quality information.

**Comment by andreasprlic** [comment]
I'd prefer a solution that works on the GitHub ecosystem.

**Comment by rmoszczynski** [comment]
@andreasprlic 

Atlassian products are very powerful but I agree that it is better to choose a solution that works on the GitHub ecosystem.

**Comment by andreasprlic** [comment]
Yes they are, I am using many of them in my daily work.

**Comment by josemduarte** [comment]
SonarQube (mentioned in #789) should be a good tool for coverage and for many other quality controls. They provide github integration with their cloud service for free for open source projects.

**Comment by josemduarte** [comment]
Closing, superseded by #924
