### ISSUE TITLE
Port org.biojava.bio.program.abi package from legacy biojava to current biojava series

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#574]
Feature request from Scott Markel: 

Would you please have a look at porting the ABITrace class to BioJava 4.2?  The BioJava 1.9.1 class path is org.biojava.bio.program.abi.ABITrace.

see also #535

**Comment by el1jaC** [comment]
Hello @andreasprlic

I've tried test file with our internal analysis software, and it works well :)

It can be a good starting point to trivially copy the classes, isn't it? And then we can think to refactor some code to integrate it in new biojava repo.

**Comment by MaxGreil** [comment]
I can have a look at it.

**Comment by josemduarte** [comment]
Indeed, this will go released with 5.1.0
