### ISSUE TITLE
Create a Changelog file

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#581]

**Comment by josemduarte** [comment]
I'd say the release notes in github are a good way of keeping a changelog. We've had a few releases already with release notes in github. I'll close unless you guys @andreasprlic @lafita  have something against.

**Comment by lafita** [comment]
I agree although the release notes will not be in the code itself (depend on GitHub and are not available offline). We could leave it open and mark it as low priority, or close it, as you prefer.

**Comment by paolopavan** [comment]
There are some projects out there which compile a changelog text from
git/github projects, which can be included in the source code. Could it be
a good choice, maybe?
The one below follows the ideas explained at http://keepachangelog.com and
it is interesteing. But anyway this is not my advice, is just an idea to
think about.
https://github.com/skywinder/github-changelog-generator


Il giorno lun 12 feb 2018 alle ore 11:29 Aleix Lafita <
notifications@github.com> ha scritto:

**Comment by josemduarte** [comment]
Thanks @paolopavan, that changelog generator looks like the way to go. I'll have a look into how to use it.

**Comment by josemduarte** [comment]
We do have a https://github.com/biojava/biojava/blob/master/CHANGELOG.md file already, thanks @andreasprlic . I've just updated it and added some notes for the upcoming 5 release. At some point we should consider making it more automated using the changelog generator project.
