### ISSUE TITLE
Correctly set up branch protection for master branch.

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#585]
on #583 Github is currently displaying `Required statuses must pass before merging`, although all changes have been approved and all checks have passed.
 
![image](https://cloud.githubusercontent.com/assets/187599/18566280/251dd4ec-7b48-11e6-9aa5-f6ecd7d2d23c.png)

How can we fix this?

Current project config is shown here:

![image](https://cloud.githubusercontent.com/assets/187599/18566252/05222b0c-7b48-11e6-91c7-56ee2c7cb944.png)

**Comment by andreasprlic** [comment]
I contacted github support about this issue.

**Comment by lafita** [comment]
On September 14 they announced a lot of new features in GitHub:

https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

The most important **Projects** and **Code Reviews**.

**Comment by andreasprlic** [comment]
I am still in contact with GitHub about this. They did not provide an ETA until when this will be fixed, but I guess it means they reproduced the issue and accepted it as a bug report.

**Comment by josemduarte** [comment]
The issue seems to be solved now! I'll close this
