### ISSUE TITLE
Bug in SuperPositionSVD

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#588]
The SuperPosisionSVD doesn't seem to calculate the correct rmsd, whilst the other 2 superposers work fine. I've added a test to reproduce it in this branch: https://github.com/josemduarte/biojava/tree/svdsuperimpIssue

The test simply does rmsd for a protein chain against itself for the 3 superposers. SuperPositionSVD doesn't return a 0 rmsd, whilst the other 2 do. I guess the unit test https://github.com/biojava/biojava/blob/master/biojava-structure/src/test/java/org/biojava/nbio/structure/geometry/TestSuperPosition.java is somehow not working  or otherwise it should have caught this problem.

**Comment by lafita** [comment]
Thanks @josemduarte, I will take a look on Monday.

**Comment by lafita** [comment]
There was bug in calculating the centroid. The test did not capture it because the points are centered at the origin already. I summit a PR with the fix.
