### ISSUE TITLE
Genbank files changed format: GenbankProxySequenceReaderTest is broken

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#596]
We found out today that the genbank tests are failing, specifically `GenbankProxySequenceReaderTest`. After digging a bit into it I found this was related to a change just implemented in genbank, this is the relevant extract from ftp://ftp.ncbi.nih.gov/genbank/gbrel.txt :

```
 1.4.3 GI sequence identifiers to be removed from GenBank/GenPept/FASTA formats
      and FASTA header to be simplified

                        **NOTE**
  The removal of GI identifiers from GenBank (and RefSeq) Release and
  Update products has been postponed until March of 2017. NCBI will initially
  implement this change only in the Entrez system, in order to better gauge
  the impact that it will have on users. We expect that the Entrez change will
  take place in late October or early November of 2016.
                        **NOTE**
```

Basically the VERSION line of the gb files used to look like:

```
VERSION     U49845.1  GI:1293613
```

and now it looks like this:

```
VERSION     SCU49845.1
```

**Comment by sbliven** [comment]
Is anyone working on this currently? It would be really nice to get travis passing again.

**Comment by sbliven** [comment]
I don't see any other place where the GI is available. Should we deprecate AccessionId.getIdentifier()? Or just remove the test for it?

**Comment by sbliven** [comment]
I removed the broken test from both 4.2 and 5.0 branches. If more is needed please re-open (e.g. if the GI should actually be calculated elsewhere).
