### ISSUE TITLE
Phosphosite file format changed

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#610]
Hi,

the latest file format of Phosphositeplus.org has changed and the parser in BioJava can not parse the current version of the files.

Andreas

**Comment by lafita** [comment]
Was this entirely fixed by #612? Should we close?

**Comment by josemduarte** [comment]
Indeed, it looks like it was solved already. I'll close it, @andreasprlic if you think it wasn't solved please reopen.
