### ISSUE TITLE
where are dependencies download?

### ISSUE THREAD

**Issue by osallou** [biojava/biojava#616]
Hi,
for biojava packaging, we used to download forester dependencies under biojava.org/download/maven/....

this web page does not exists anymore (404 not found). Where can we get 3rd party dependencies now?

Thanks

**Comment by osallou** [comment]
just additional info, I need used forester sources, not final jar that can be found in maven repo.

**Comment by heuermh** [comment]
Hello @osallou!

The forester artifact and sources are available from Maven Central under the org.biojava.thirdparty groupId, http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.biojava.thirdparty%22

**Comment by sbliven** [comment]
Note that we are just providing the maven releases. If you want the most up-to-date version of forester, you should get it directly from https://github.com/cmzmasek/forester.

**Comment by josemduarte** [comment]
This is our fork of the forester project that we created to be able to publish it to maven: https://github.com/josemduarte/forester

**Comment by didiksupriadi41** [comment]
Hi @josemduarte , can you draft a new release on https://github.com/josemduarte/forester?
Just so it's clear that the latest log is version 1.038. :confused:

**Comment by josemduarte** [comment]
Not sure what you mean @didiksupriadi41 . There's a forester release with version 1.038 already: https://search.maven.org/artifact/org.biojava.thirdparty/forester/1.038/jar

**Comment by didiksupriadi41** [comment]
Oh, I mean exactly the github repository.
![image](https://user-images.githubusercontent.com/19786918/79089777-96066780-7d71-11ea-81c4-4757ae99fd1c.png)

**Comment by josemduarte** [comment]
Oh I see. Sure that's a good idea.
