### ISSUE TITLE
Add an EMBL file parser to BioJava

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#621]
See discussion at
http://www.mail-archive.com/biojava-l@mailman.open-bio.org/msg00188.html

The BioJava 1-legacy series used to contain an EMBL file format parser. Would be great to also get one for the current BioJava.

**Comment by wernerkrampl** [comment]
Could someone please provide an actual EMBL file for testing?

**Comment by noureddine-mb** [comment]
dear @andreasprlic 
I have implemented an EMBL file parser and i want to ask you about the approach that you use to upload new feature

**Comment by noureddine-mb** [comment]
@andreasprlic  
Yes , thank you for your response.
