### ISSUE TITLE
ResidueType.getResidueTypeFromString performance

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#622]
Did some profiling why AllChemCompProvider on master branch is slow. Looks like all time is spent in ResidueType.getResidueTypeFromString() . Need to speed this up. Possible solution: rather than looping over all values of the enum, this needs a lookup table for speedup.

**Comment by andreasprlic** [comment]
Added some cleanup in #623, but so far only minimal performance improvements.  I came onto this while trying to track down why mmtf parsing is slow. Still work in progress.

**Comment by josemduarte** [comment]
Unclear if this is still relevant. Closing for now. Please reopen if more hints are found.
