### ISSUE TITLE
mmtf parsing is slow

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#624]
I wrote a small unit test that compares mmtf and pdb file parsing times. From this comparison it looks like pdb format is faster than mmtf parsing. 

for 4CUP:
time to load mmtf from local file: 868 ms.
time to load pdb from local file: 219 ms.

Need to track down why this is so slow.

**Comment by andreasprlic** [comment]
There are too many layers stacked up which causes the slow performance. First mmtf builds a GenericDecoder which then gets converted to a Structure using StructureDataToAdapter -> MmtfStructureReader.

It would be significantly faster to bypass the GenericDecoder and provide a BioJava structure specific decoder instead.

**Comment by andreasprlic** [comment]
moving this over to mmtf-java since the underlying Java decoder seems to be slow.

see https://github.com/rcsb/mmtf-java/issues/22

**Comment by andreasprlic** [comment]
Once the underlying decoder has been improved, we will add a BioJava structure specific proxy.

**Comment by lafita** [comment]
I believe the performance of mmtf is as expected now.
