### ISSUE TITLE
Generating pseudo amino acid composition programmatically using biojava

### ISSUE THREAD

**Issue by srikanthBezawada** [biojava/biojava#641]
Hi,

Does biojava support generating pseudo amino acid composition programmatically from protein sequence.

Reference - http://www.csbio.sjtu.edu.cn/bioinf/PseAAC/

Thanks!

**Comment by sbliven** [comment]
No, we don't have it currently.

Is PseAAC widely used? I'd feel like this might be better suited as an external library using biojava, rather than including it in the main project.

**Comment by srikanthBezawada** [comment]
@sbliven ,
I am not sure of the usage of PseAAC but I read about how AA composition is used in the pattern recognition since a digital vector of length 20 makes sense than the alphabets when a sequence is looked at. 
I made a toy program which finds AA composition from the sequence by counting the frequency of each AA. Thanks for the response!
