### ISSUE TITLE
Link to cookbook in the github README is broken

### ISSUE THREAD

**Issue by psoares** [biojava/biojava#664]
The link to the cookbook in the documentation of this project is broken.

**Comment by josemduarte** [comment]
Can you specify what link? The link in the biojava.org site works for me (http://biojava.org/wiki/BioJava:CookBook4.0/).

Note that you can also use the tutorial in github (which is more up to date in some parts): https://github.com/biojava/biojava-tutorial

**Comment by psoares** [comment]
The one at [https://github.com/biojava/biojava
](https://github.com/biojava/biojava) just under the "Documentation" title.

**Comment by josemduarte** [comment]
Now fixed, thanks for reporting!
