### ISSUE TITLE
Remove BioJava dependency on source.rcsb.org server

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#692]
The test `CeCPMainTest.testCECP1()` is failing because the PDP domain cannot be retrieved. The exception happens at line 191 of RemotePDPProvider class:

```java
InputStream response = URLConnectionTools.getInputStream(u);
```

If I reconstruct the URL `u` it is: http://source.rcsb.org/jfatcatserver/domains/getPDPDomain?pdpId=PDP:3A2KAc

Is this PDB service temporarily unavailable or should we update the code?

**Comment by lafita** [comment]
I realized the whole http://source.rcsb.org domain is down.

**Comment by josemduarte** [comment]
Yes indeed that's the cause of tests failing. I'll try to look into it and see if we can bring the server back or even better if we can replace that data source by something else.

**Comment by lafita** [comment]
I agree, it does not seem to be used in a lot of places, so maybe it is possible to replace it.

**Comment by lafita** [comment]
The server is back again, but I will leave the issue open to remove the dependency of biojava on this server.

**Comment by sbliven** [comment]
The source server is essential for the remote implementations of several services (SCOP and PDP come to mind). Basically, it's a servlet that parses the PDB-wide files and lets them be queried for individual structures. I think this is an important service to maintain, although perhaps its time to replace the Tomcat backend (RCSB's internal jfatcatserver) with something leaner and more modular. Either way, source.rcsb.org should be treated as a public RCSB API and maintained in some form.

**Comment by lafita** [comment]
Ok sounds fair, I am closing this then. Thanks @sbliven
