### ISSUE TITLE
OBO parser: namespace

### ISSUE THREAD

**Issue by tulay** [biojava/biojava#695]
Hi,
I don't see where namespace is stored in the ontology. For Gene ontology there are several namespaces as opposed to the single sequence namespace in [biosapiens.obo](http://sourceforge.net/p/song/svn/HEAD/tree/trunk/subsets/biosapiens.obo?format=raw) in the demo.
Thanks!

**Comment by lafita** [comment]
I think the `namespace` is not parsed, but I would imagine that `Ontology.getName()` is the place for it, currently only set by the user. 

Is the `namespace` important for the interpretation of the ontology? What is the use case for parsing it as well?

Can you provide a file where there are several namespaces? 

Thanks @tulay!

**Comment by tulay** [comment]
An example ontology for this issue: [go.obo](http://www.geneontology.org/ontology/go.obo)
