### ISSUE TITLE
Github CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#699]
GitHub has a new feature to specify some basic guidelines for contributing to projects in a file called `CONTRIBUTING`:

>It explains how a participant should do things like format code, test fixes, and submit patches. From a maintainer's point of view, the document succinctly communicates how best to collaborate. And for a contributor, one quick check of this file verifies their submission follows the maintainer's guidelines.

I think it would be great to have one for BioJava to help and make life easier to new contributors.

**Comment by lafita** [comment]
This is an explanation from github help on how to setup this file: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by lafita** [comment]
There is also a possibility to set up a template for the text in issues and pull requests: 

- https://help.github.com/articles/creating-an-issue-template-for-your-repository/
- https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by josemduarte** [comment]
Added an initial CONTRIBUTING file. Again please feel free to add to it!
