### ISSUE TITLE
Github SUPPORT file

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#700]
Additionally to the README, we can use the github support file to point users to the documentation sources: 
>SUPPORT files can be used to direct users to dedicated support resources, such as community forums, FAQ documents, or corporate support channels.

https://github.com/blog/2400-support-file-support

How to set the SUPPORT file in a repository: https://help.github.com/articles/adding-support-resources-to-your-project/

**Comment by josemduarte** [comment]
I've added a minimal support file now, please feel free to add to it.
