### ISSUE TITLE
Structure.clone() doesn't copy AtomImpl.bonds lists.

### ISSUE THREAD

**Issue by larsonmattr** [biojava/biojava#712]
This is a problem in the 4.2.x branch and the master branch.

Structure.clone() is described as "Return an identical copy of this Structure object".  

1) If the original Structure was parsed with the FileParsingParameters.setCreateAtomBonds(true), a Structure will be created there each Atom in the Structure has a list of Bonds to describing connections to other Atom instances.

2) If you then make a deep copy by Structure.clone(), the new Structure will be missing any Bond information inside the cloned Atom instances.

I would expect that connectivity would also be preserved in a deep copy.

[TestClone.java.gz](https://github.com/biojava/biojava/files/1423341/TestClone.java.gz)

**Comment by josemduarte** [comment]
Thanks for the report and the test, I've committed it into existing test TestCloning in branch https://github.com/biojava/biojava/tree/issue712. Pull requests are welcomed :)

**Comment by josemduarte** [comment]
Solved in #786. Closing
