### ISSUE TITLE
Error resolving version for plugin 'javaws:javaws' (a structure-gui dependency)

### ISSUE THREAD

**Issue by Takkoona** [biojava/biojava#714]
Hi,

Need help!

I'm very new to biojava and having difficulty in importing structure-gui module (version 4.2.0). Apache Maven (3.3.9) gave me this:

[ERROR] Error resolving version for plugin 'javaws:javaws' from the repositories [local (/home/Chengyang/.m2/repository), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginVersionResolutionException

And I looked up this 'javaws' in https://mvnrepository.com/ but no record found.
Other version 4 biojava modules worked out fine by following the tutorial https://github.com/biojava/biojava-tutorial.

Can it be fixed and how?

Java version:
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

I'm on eclipse (installed just few days ago...):
Version: Oxygen.1a Release (4.7.1a)

**Comment by Takkoona** [comment]
Saw a similar question https://github.com/biojava/biojava/issues/459

**Comment by josemduarte** [comment]
For the record, the answer is to just use the latest bugfix version (4.2.9).
