### ISSUE TITLE
SubunitClustererParameters question

### ISSUE THREAD

**Issue by biocryst** [biojava/biojava#720]
As far as I can understand, at some point the subunit clustering was based on a TM-Score threshold, then it was changed to a pair of RMSD/structure coverage thresholds. See here 
https://github.com/biojava/biojava/commit/8414244002fa8ffb7f961ed724c91e2f02b2acd4#diff-0c44f560d38ebbf42e961750ae39f15a

What was the reason for the change? It appears that the TM-Score (normalized by the larger structure) is easier to fine-tune and produces more consistent results (if only because it's one number instead of two).

**Comment by lafita** [comment]
I do not see a problem in using TM-score as a threshold for the structural clustering, I think I used RMSD and coverage separately to ensure that they both were reasonable, and not high TM-score with low coverage and low RMSD or high coverage but low RMSD. 

You should be able to add a parameter for a TM-score threshold!

**Comment by biocryst** [comment]
Closed due to #724
