### ISSUE TITLE
Reset the QCP superposition method step-wise calculation

### ISSUE THREAD

**Issue by lafita** [biojava/biojava#725]
@pwrose reported this:

I was just trying to use the QCP superposition method in BioJava.  There is only one problem with the new design in that doesn't take advantage of QCP and will be slower in situations like the one below:

For example, I have the following code:

		SuperPositionQCP qcp = new SuperPositionQCP(false);
		double rmsd = qcp.getRmsd(x, y);
		double tm = 0.0;
		if (rmsd < maxRmsd) {
			qcp.superposeAndTransform(x, y);
			tm = TMScore(x, y);
		}

The getRmsd method does the majority of the work. But when superposeAndTransform(x, y) is run with the x,y arguments, it resets all intermediate results repeats the whole calculation from scratch.

In the original version (https://github.com/sbl-sdsc/QuickStructureSearch/blob/master/src/main/java/org/rcsb/structuralAlignment/SuperPositionQCP.java), you could get the RMSD first, then if you requested a superposition or the transformation matrix, it would use the intermediate results from the RMSD calculation to calculate the transformation matrix.

So QCP is conceptually different from the other superposition methods. I propose to add a QCP specific method: superposeAndTransform(), which would reuse the intermediate results from the RMSD calculation. The only downside is that it would fail if getRMSD(x, y) wasn't called before.

**Comment by josemduarte** [comment]
Any chance this can be done before the 5.0.0 release? Otherwise I'll move it to 5.1

**Comment by lafita** [comment]
Yes it should be 5.0.0. I am working on it in a separate branch and will submit a pull request soon.
