### ISSUE TITLE
Preparing the 5.0.0 release

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#727]
Work in the master branch towards a 5.0.0 version has been going on for quite some time now. In fact we have a bunch of alpha releases in maven central already, the first one almost 2 years ago!

I'd like to move ahead and release 5.0.0, setting a date in about a month from now: **15th March 2018**.

Please comment on this issue in case you like or dislike the idea. At this time it would be important to include any needed refactoring that would break the API. So please comment if there is something anyone needs more time for.

As usual there will be a list of tasks to do:

- [x] Triage current [milestone 5.0.0 issues](https://github.com/biojava/biojava/milestone/5). I'll start doing that. 
- [x] Draft the release notes
- [x] Declare a code freeze. Proposed date **12th March 2018**
- [x] Ensure all classes contain the license notice (there's a script for that [here](https://github.com/biojava/biojava/blob/master/development/addlicense.sh))
- [x] Perform release, uploading artifacts to sonatype and maven central (easily done with maven release plugin)
- [x] Upload new javadocs to biojava.org

**Comment by heuermh** [comment]
I'd like to see the binary API incompatibilities compared to 4.x documented clearly.

The [clirr-maven-plugin](http://www.mojohaus.org/clirr-maven-plugin/) is one way to do it, there may be others.

**Comment by josemduarte** [comment]
> I'd like to see the binary API incompatibilities compared to 4.x documented clearly.
>
>The clirr-maven-plugin is one way to do it, there may be others.

Absolutely. We've got to work on a comprehensive release note document that documents all incompatibilities. Thanks for the clirr plugin tip, didn't know that!

**Comment by josemduarte** [comment]
FYI: I've started compiling release notes here: https://github.com/biojava/biojava/releases/tag/untagged-b36aa68041a8a0e18746

**Comment by lafita** [comment]
@josemduarte the link does not work for me.

**Comment by josemduarte** [comment]
Sorry about that, I thought that would be a shareable link... it seems that's only in my account. I'll try something different that we can all edit.

**Comment by josemduarte** [comment]
Alright I've copied my notes over to https://github.com/biojava/biojava/blob/master/CHANGELOG.md . We had the CHANGELOG file already, I've just updated it with a few missing bugfix releases and added some  more content to the 5.0.0 release.

**Comment by josemduarte** [comment]
A reminder to everyone. Next Monday will be code freeze for the 5.0.0 release. Please submit anything you'd like to see in 5 before that, especially important any API breaking changes. Thanks!

**Comment by josemduarte** [comment]
FYI the clirr maven plugin seems to be very outdated. It seems that a good replacement is [revapi](https://revapi.org/). It's still in beta but actively developed.

**Comment by josemduarte** [comment]
Some problems with maven and plugins... I'll defer the release to tomorrow.

**Comment by josemduarte** [comment]
I am going to give up on the maven release plugin. It's breaking at `release:perform` and I can't figure out why. The thing is it provides very little value, so I'd rather do without it. Plenty of people seem to agree on that: [1](https://dzone.com/articles/why-i-never-use-maven-release), [2](https://axelfontaine.com/blog/final-nail.html)

Without the plugin a release will be pretty straight forward and more or less the same number of steps than with the plugin:

1. Switch version in poms from `M.m.b-SNAPSHOT` to `M.m.b` and commit. Can be done easily with `mvn versions:set -DnewVersion=M.m.b -DgenerateBackupPoms=false`
3. Build and deploy: `mvn deploy`
4. Tag `biojava-M.m.b`
5. Switch version in poms from `M.m.b` to `M.m.b+1-SNAPSHOT` and commit
6. Push everything to origin. 
7. Build javadocs with `mvn javadoc:javadoc` and push to website

Advantages:
- Easy to roll back anytime. No risk of extra commits in git.
- No need to run tests (with release plugin tests had to be run 3 times at least)

Is there anything I'm missing? Any recommendations on other plugins or other procedures for releasing?

**Comment by heuermh** [comment]
There are few pieces of software that have caused me to swear and throw things more than the Maven release plugin, but I would suggest we stick with it.  Ping me on gitter or somewhere and I'll try to help.

**Comment by josemduarte** [comment]
So why sticking with it? In the end of the day it doesn't save any work while having a few disadvantages:

- There's no way to avoid tests, so every time you do release:prepare and release:perform you have to wait for tests to run ~ 3 times
- It commits, tags and pushes automatically, if something goes wrong a lot of noise ends up in the commit history, plus you have to manually undo the tag (release:rollback won't do that)
- Debugging it is a pain because of the previous points

It seems that the plugin was useful in the svn days but not with git.

Anyway @heuermh  feel free to experiment with it, try see if you can run it and make the release. You do have the sonatype keys, don't you?

**Comment by heuermh** [comment]
When testing out new build changes, we (myself and collaborators on all the other projects I cut releases for) try one or more release candidate builds (e.g. 5.0.0-rc1) and then drop the staging repository so those artifacts aren't pushed to Maven Central.  We don't see anything wrong with having release candidate tags in the git history.

>  You do have the sonatype keys, don't you?

I believe so, I can give it a try over the weekend.  Could you gist or email me your failure(s)?

**Comment by josemduarte** [comment]
[Here](https://drive.google.com/file/d/18UNq-sYPEr5M2fXf88i8r7fiRpkbxZKR/view?usp=sharing) is the log from running `mvn -X release:perform`

**Comment by josemduarte** [comment]
@heuermh any luck at debugging release problems?

**Comment by sbliven** [comment]
If it's too frustrating we can try to drop it, but I do think mvn has merits. Automating the release avoids bugs like forgetting to increment a version in one of the submodules. It also handles some not-so-intuitive step with the Sonotype staging to get it to maven central. When I make Jmol releases I have to do it manually (it builds with Ant), and it is definitely more work than a correctly configured release:perform.

One thing I definitely avoid is release:rollback. It's clearly a hold-over from SVN days. It can be replaced with a simple `git reset --hard ...`

I'll try my hand at releasing tomorrow and see if it goes better. Sorry it's been so frustrating!

**Comment by heuermh** [comment]
@josemduarte @sbliven I'm still looking at it, will let you know by tomorrow AM.

**Comment by josemduarte** [comment]
Thank you! @sbliven @heuermh

**Comment by heuermh** [comment]
I was able to cut a 1.9.3-rc1 (which I then dropped from the staging repository and deleted from the release tags) and then a [1.9.3 release for biojava-legacy](https://github.com/biojava/biojava-legacy/releases/tag/biojava-legacy-1.9.3), so my setup and code signing keys still work fine.

The problem I see in the build log above is that the `biojava-integrationtest` module has no java source and so no artifact is created for maven-gpg-plugin to sign.  Has a release been cut with this module before?

**Comment by josemduarte** [comment]
Thanks @heuermh ! that clue explains what's happening then: a few weeks ago I did some clean up to avoid building a jar for `biojava-integrationtest` which has no actual code but only test code, so there's no point in distributing it. Now the gpg plugin tries to sign it but it doesn't exist anymore. My fault, really sorry about that.

Is there a way to tell the release plugin (or the gpg plugin) to avoid that module? Or do we have to go back to distributing an empty jar?

**Comment by josemduarte** [comment]
Ok found it, adding this to gpg plugin config should do the trick:
```xml
<configuration>
	<excludes>
		<exclude>biojava-integrationtest*</exclude>
	</excludes> 
</configuration>
```
I'll give it a try

**Comment by josemduarte** [comment]
Alright that exclude didn't quite work. I'll continue trying.

**Comment by heuermh** [comment]
I believe that module may need to be excluded from the entire release process.  The Sonatype Nexus validation process will choke if there are missing -sources.jar or -javadoc.jar artifacts.

**Comment by heuermh** [comment]
@josemduarte This may work,

```
$ git diff .
diff --git a/biojava-integrationtest/pom.xml b/biojava-integrationtest/pom.xml
index 337a015f9..58b7d9f21 100644
--- a/biojava-integrationtest/pom.xml
+++ b/biojava-integrationtest/pom.xml
@@ -93,7 +93,13 @@ mvn verify</description>
           </execution>
         </executions>
       </plugin>
-      
+      <plugin>
+        <groupId>org.apache.maven.plugins</groupId>
+        <artifactId>maven-deploy-plugin</artifactId>
+        <configuration>
+          <skip>true</skip>
+        </configuration>
+      </plugin>
     </plugins>
   </build>
```

**Comment by josemduarte** [comment]
@heuermh thank you so much for the tip. That worked out, this is the commit 87e7fc7bfc37525dd5a8930b5efd4459e5b73e98

I'll attempt to perform the release now.

**Comment by josemduarte** [comment]
Success! jars are uploaded to sonatype. Thanks all for the help!

**Comment by josemduarte** [comment]
I've just uploaded the javadocs to biojava.org. Will close this issue.
