### ISSUE TITLE
OBO Parser: replaced_by

### ISSUE THREAD

**Issue by PatrickDeelen** [biojava/biojava#731]
I'm trying to parse the HPO OBO file. Unfortunately the `replaced_by` triple is not parsed. It would be great if you can add this in a future version.

**Comment by josemduarte** [comment]
Good suggestion. I've added it to 5.1.0 milestone. Note that 5.0.0 is going to be released soon, see #727

**Comment by PatrickDeelen** [comment]
Great, thank you!

**Comment by MaxGreil** [comment]
I can have a look at it.

**Comment by josemduarte** [comment]
Now implemented with #731 . Will be available in next release 5.1.0
