### ISSUE TITLE
Potential bug in MultipleMcOptimizer

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#741]
See this line:

https://github.com/biojava/biojava/blob/646fce016d321ef7c398043b27da6b57b2c4b4bb/biojava-structure/src/main/java/org/biojava/nbio/structure/align/multiple/mc/MultipleMcOptimizer.java#L496

The eclipse compiler gives a warning there that seems well founded. `freePool` is a `List<SortedSet<Integer>>` whilst the value that is searched (`residue`) is an `Integer`. @lafita could you have a look when you have time?

**Comment by lafita** [comment]
The selection of the structure is missing. This means that the `shiftRow` operation is never successful. I submitted a PR with the fix.
