### ISSUE TITLE
Consider relicensing as Apache v2

### ISSUE THREAD

**Issue by heuermh** [biojava/biojava#765]
I've been a supporter of the GPL and LGPL for a very long time, and in fact use them for several of my own projects, but I've been running into an unwillingness to depend on biojava in Apache v2 licensed projects.

Which licenses may NOT be included within Apache products?
https://www.apache.org/legal/resolved#category-x

What do folks think about relicensing as Apache v2?

**Comment by darnells** [comment]
I do not think the "BioJava project" exists as an entity, thus no one person or small group of people own the copyright of the source code. Please correct me if I am wrong.

From the Javadoc of the source files:
"Copyright for this code is held jointly by the individual authors.  These should be listed in @author doc comments."

[IANAL] Since copyright is jointly held, I expect you will need **every author** to agree to the license change. Maybe the LGPL code from holdouts could be segregated from the newly licensed code. [/IANAL]

I would hate to be the one to champion this issue.

**Comment by heuermh** [comment]
> Since copyright is jointly held, I expect you will need every author to agree to the license change.

That is my understanding as well.  I do not propose this change lightly.

**Comment by brianrepko** [comment]
There has always been unanswered issues with the GPL / LGPL on what is considered to be "linking" with respect to Java code and that is the main argument against those licenses. An Apache 2.0 License is preferred (my personal opinion) and yes - I believe it's a bit damn deal to do that as @darnells points out and @heuermh acknowledges. You might need "Contributor Agreements" from copyright holders on this (and how to even get that list - all the @author tags?)

**Comment by sbliven** [comment]
Shouldn't it be OK to link against BioJava (e.g. adding it to the classpath as opposed to generating a shaded jar)? I was surprised to see LGPL in the category-x list:

> The LGPL is ineligible primarily due to the restrictions it places on larger works, violating the third license criterion

However, I think in this section "INCLUDED WITHIN APACHE PRODUCTS" means direct source inclusion or static linking. My reading of [LGPL](https://www.gnu.org/licenses/lgpl-3.0.en.html) section 3 is that dynamic linking is just fine (after all, that's the point of LGPL vs GPL).

BioPython recently relicensed their code by soliciting permission from >200 authors. It was a huge undertaking, and they got a much clearer benefit (they were using a custom license). I would be reluctant to undertake such a project for BioJava unless it was really significantly blocking adoption.

@heuermh BTW, are we talking BioJava 5 or just legacy? The latter might reduce the number of contributors.

**Comment by sbliven** [comment]
@heuermh Can you give some more info about why linking LGLP from Apache 2 is a problem? Do you want to make shaded jars or something?

I'm inclined to close this issue unless there's some more active discussion.

**Comment by heuermh** [comment]
> Can you give some more info about why linking LGPL from Apache 2 is a problem?

I'm not able to argue for that position.

Pragmatically I have observed that Apache Software Foundation will not allow linking to LGPL dependencies from any JVM-based Apache project.

The same is true for the [Big Data Genomics](https://github.com/bigdatagenomics) organization, which is frustrating to me personally as I can't use any of the Free/Libre and Open Source software I've written for my day job.

> I'm inclined to close this issue unless there's some more active discussion.

I'd suggest leaving it open at least until after the BOSC conference and hackathon at the end of the month.  Perhaps some of us can meet up there and discuss it in person.

**Comment by heuermh** [comment]
Closing as WontFix
