### ISSUE TITLE
Error when parsing NCBI FASTA file - "Cannot find compound"

### ISSUE THREAD

**Issue by julie-sullivan** [biojava/biojava#777]
I am trying to parse the FASTA file from here:

https://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/Assembled_chromosomes/seq/

But get this error:

```
[integrate] [main] WARN org.biojava.nbio.core.sequence.io.FastaReader - Sequence with header 'ref|NC_000001.11| Homo sapiens chromosome 1, GRCh38.p12 Primary Assembly' has unrecognised compounds (Cannot find compound for: M), it will be ignored
[integrate] reading dna sequence from: /data/human/fasta/current/hs_ref_GRCh38.p12_chr10.fa
```

How can we process these data? 

Can we have the option to make the FastaReader more permissive? 

Thanks!!

**Comment by josemduarte** [comment]
I think you simply need to use one of the ambiguity compound sets. Something like:

```java
DNASequence seq = new DNASequence("ATCMAA", AmbiguityDNACompoundSet.getDNACompoundSet());
```
The `AmbiguityDNACompoundSet.getDNACompoundSet()` should understand `M` as a valid character.

In any case if you can post a snippet of your code, that will help understanding your problem.
