### ISSUE TITLE
GOD CLASS in biojava

### ISSUE THREAD

**Issue by wayaya13** [biojava/biojava#782]
I come across the following code smell (design defect) in the effective project: 
    (1)   Type of code smells: GOD CLASS
    (2)   Associated project: biojava
    (3)   Associated link: 
           https://github.com/biojava/biojava/blob/master/biojava-aa-prop/src/main/java/org/biojava/nbio/aaproperties/CommandPrompt.java
    (4)   Associated class: class CommandPrompt​
    (5)   Smells detected by: JDeodorant, PMD, and CheckStyle
    I also notice that the code smell was introduced several years ago, and it remains unsolved after the associated codes are modified several times. I just wonder why it is not resolved during maintenance. Thanks:)

**Comment by sbliven** [comment]
Can you be more specific about what should be changed? The class looks pretty self contained, and I wouldn't characterize it as a [God Class](https://www.c-sharpcorner.com/article/god-object-a-code-smell/).

**Comment by sbliven** [comment]
Hmm, looks like @wayaya13 is probably a bot. I'm going to close this.
