### ISSUE TITLE
Bioassembly fails for a structure with null seqres groups (MMTF only)

### ISSUE THREAD

**Issue by biocryst** [biojava/biojava#792]
StructureIO.getStructure("BIO:2X3T:1") causes exception when cloning the asymmetric unit, if MMTF is used (cache.setUseMmtf(true)). The reason is null seqres groups.

There are two issues here: difference in the data between MMTF and MMCIF, and "safe" code.

I can make the code a bit safer, i.e. take this test:
https://github.com/biojava/biojava/blob/8a7b651afc1bd75bf70f03d309250058a45b982d/biojava-structure/src/main/java/org/biojava/nbio/structure/ChainImpl.java#L190-L193
and put a similar one here:
https://github.com/biojava/biojava/blob/8a7b651afc1bd75bf70f03d309250058a45b982d/biojava-structure/src/main/java/org/biojava/nbio/structure/ChainImpl.java#L638-L643

I am not sure what to do with the difference in the data at this point.

**Comment by josemduarte** [comment]
Good catch! The fix in #793 is definitely needed. 

As for the other issue, it looks like 2X3T is not read correctly from mmtf. In fact that structure fails this test: https://github.com/biojava/biojava/blob/master/biojava-structure/src/test/java/org/biojava/nbio/structure/io/mmtf/TestMmtfRoundTrip.java

**Comment by josemduarte** [comment]
I've checked was going on with 2X3T mmtf parsing and indeed there is an issue: the seqres groups of chain E are not populated. The chain is polymeric with residues of type dpeptide and because of that somehow the seqres groups remain null.

**Comment by josemduarte** [comment]
Note this is losely related to #671

**Comment by josemduarte** [comment]
I've added a test for this in PR #850 (and set as ignored). My conclusion is that SEQRES groups that are unobserved and non-standard aminoacids (like in chain E of 2X3T) are going to be always null when coming from MMTF. This is because of a limitation of MMTF where seqres groups are represented as 1-letter strings and thus any non-standard aminoacid is encoded as 'X', so the information on chemical component id is lost in the case when the residue is unobserved.

I've created an issue at mmtf: https://github.com/rcsb/mmtf/issues/43

**Comment by pwrose** [comment]
The full chemical component ID is stored with the group data for observed
residues here:
https://github.com/rcsb/mmtf/blob/master/spec.md#group-data

In principle, unobserved chemical components could be added to that list.

**Comment by josemduarte** [comment]
Indeed, but that would require either a new flag `observed y/n` or making the `formalChargeList`, `elementList` and `atomNameList` optional fields (now they are required).

**Comment by pwrose** [comment]
The formalCharge, element, and atomName are available from the Chemical
Component Dictionary, so it should be possible to populate these fields.

**Comment by josemduarte** [comment]
True, those fields are independent of whether atoms are observed or not. But in any case a flag to indicate whether group is observed or not would be required.

**Comment by pwrose** [comment]
The sequenceIndexList keeps track of the correspondences between the SEQRES
sequence and the group information, so for unobserved residues, this
correspondence would need to be tracked as well, e.g., how KXXXXXXEX maps
to K(DBB)(DVA)(DBB)(DBB)(DVA)(DBB)E(BAL).
