### ISSUE TITLE
kaplan-meier chart - implementation example

### ISSUE THREAD

**Issue by betrw** [biojava/biojava#807]
Could you give me an implementation example of the kaplan-meier chart please?

It is the best and the fastest way to get started with.

**Comment by willishf** [comment]
In the main of the method is a working example to generate a figure.

   /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        try {

            KaplanMeierFigure kaplanMeierFigure = new KaplanMeierFigure();
            LinkedHashMap<String, ArrayList<CensorStatus>>
survivalDataHashMap = new LinkedHashMap<String, ArrayList<CensorStatus>>();

            if (false) { //
http://sph.bu.edu/otlt/MPH-Modules/BS/BS704_Survival/
                ArrayList<CensorStatus> graph1 = new
ArrayList<CensorStatus>();
                graph1.add(new CensorStatus("A", 24.0, "0"));
                graph1.add(new CensorStatus("A", 3.0, "1"));
                graph1.add(new CensorStatus("A", 11.0, "0"));
                graph1.add(new CensorStatus("A", 19.0, "0"));
                graph1.add(new CensorStatus("A", 24.0, "0"));
                graph1.add(new CensorStatus("A", 13.0, "0"));

                graph1.add(new CensorStatus("A", 14.0, "1"));
                graph1.add(new CensorStatus("A", 2.0, "0"));
                graph1.add(new CensorStatus("A", 18.0, "0"));
                graph1.add(new CensorStatus("A", 17.0, "0"));
                graph1.add(new CensorStatus("A", 24.0, "0"));
                graph1.add(new CensorStatus("A", 21.0, "0"));
                graph1.add(new CensorStatus("A", 12.0, "0"));

                graph1.add(new CensorStatus("A", 1.0, "1"));
                graph1.add(new CensorStatus("A", 10.0, "0"));
                graph1.add(new CensorStatus("A", 23.0, "1"));
                graph1.add(new CensorStatus("A", 6.0, "0"));
                graph1.add(new CensorStatus("A", 5.0, "1"));
                graph1.add(new CensorStatus("A", 9.0, "0"));
                graph1.add(new CensorStatus("A", 17.0, "1"));

                survivalDataHashMap.put("Label 1", graph1);



            }


            if (true) {



                ArrayList<CensorStatus> graph1 = new
ArrayList<CensorStatus>();
                graph1.add(new CensorStatus("A", 1.0, "1"));
                graph1.add(new CensorStatus("A", 1.0, "1"));
                graph1.add(new CensorStatus("A", 1.0, "1"));
                graph1.add(new CensorStatus("A", 2.0, "1"));
                graph1.add(new CensorStatus("A", 2.0, "1"));
                graph1.add(new CensorStatus("A", 3.0, "1"));

                graph1.add(new CensorStatus("A", 4.0, "1"));
                graph1.add(new CensorStatus("A", 4.0, "1"));
                graph1.add(new CensorStatus("A", 4.0, "1"));
                graph1.add(new CensorStatus("A", 4.0, "1"));
                graph1.add(new CensorStatus("A", 4.0, "1"));
                graph1.add(new CensorStatus("A", 4.0, "1"));
                graph1.add(new CensorStatus("A", 4.0, "0"));

                graph1.add(new CensorStatus("A", 5.0, "1"));
                graph1.add(new CensorStatus("A", 5.0, "1"));

                graph1.add(new CensorStatus("A", 8.0, "0"));
                graph1.add(new CensorStatus("A", 8.0, "0"));
                graph1.add(new CensorStatus("A", 8.0, "0"));
                graph1.add(new CensorStatus("A", 8.0, "0"));
                graph1.add(new CensorStatus("A", 8.0, "0"));
                graph1.add(new CensorStatus("A", 8.0, "0"));
                graph1.add(new CensorStatus("A", 8.0, "1"));

                graph1.add(new CensorStatus("A", 9.0, "1"));
                graph1.add(new CensorStatus("A", 9.0, "1"));
                graph1.add(new CensorStatus("A", 9.0, "1"));
                graph1.add(new CensorStatus("A", 9.0, "1"));
                graph1.add(new CensorStatus("A", 9.0, "1"));


                graph1.add(new CensorStatus("A", 13.0, "0"));
                graph1.add(new CensorStatus("A", 13.0, "0"));
                graph1.add(new CensorStatus("A", 13.0, "1"));

                survivalDataHashMap.put("Label 1", graph1);

                ArrayList<CensorStatus> graph2 = new
ArrayList<CensorStatus>();
                graph2.add(new CensorStatus("A", 1.0, "1"));
                graph2.add(new CensorStatus("A", 1.0, "1"));
                graph2.add(new CensorStatus("A", 1.0, "0"));
                graph2.add(new CensorStatus("A", 3.0, "0"));
                graph2.add(new CensorStatus("A", 3.0, "1"));
                graph2.add(new CensorStatus("A", 4.0, "1"));

                graph2.add(new CensorStatus("A", 4.0, "1"));
                graph2.add(new CensorStatus("A", 4.0, "1"));
                graph2.add(new CensorStatus("A", 4.0, "1"));
                graph2.add(new CensorStatus("A", 5.0, "1"));
                graph2.add(new CensorStatus("A", 5.0, "0"));
                graph2.add(new CensorStatus("A", 5.0, "0"));
                graph2.add(new CensorStatus("A", 5.0, "0"));

                graph2.add(new CensorStatus("A", 6.0, "1"));
                graph2.add(new CensorStatus("A", 6.0, "0"));

                graph2.add(new CensorStatus("A", 7.0, "0"));
                graph2.add(new CensorStatus("A", 7.0, "0"));
                graph2.add(new CensorStatus("A", 7.0, "0"));
                graph2.add(new CensorStatus("A", 7.0, "0"));
                graph2.add(new CensorStatus("A", 8.0, "1"));
                graph2.add(new CensorStatus("A", 8.0, "1"));
                graph2.add(new CensorStatus("A", 8.0, "1"));

                graph2.add(new CensorStatus("A", 8.0, "1"));
                graph2.add(new CensorStatus("A", 8.0, "1"));
                graph2.add(new CensorStatus("A", 8.0, "0"));
                graph2.add(new CensorStatus("A", 9.0, "0"));
                graph2.add(new CensorStatus("A", 9.0, "1"));


                graph2.add(new CensorStatus("A", 10.0, "0"));
                graph2.add(new CensorStatus("A", 10.0, "0"));
                graph2.add(new CensorStatus("A", 10.0, "0"));

                survivalDataHashMap.put("Label 2", graph2);
            }

            ArrayList<String> figureInfo = new ArrayList<String>();
            DecimalFormat dfe = new DecimalFormat("0.00E0");
            DecimalFormat df = new DecimalFormat("0.00");



            JFrame application = new JFrame();
            application.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            application.add(kaplanMeierFigure);
            kaplanMeierFigure.setSize(500, 400);

            application.setSize(500, 400);         // window is 500 pixels
wide, 400 high
            application.setVisible(true);

            ArrayList<String> titles = new ArrayList<String>();
            titles.add("Line 1");
            titles.add("line 2");
            kaplanMeierFigure.setSurvivalData(titles, survivalDataHashMap,
true);

            //   figureInfo.add("HR=2.1 95% CI(1.8-2.5)");
            //   figureInfo.add("p-value=.001");
            kaplanMeierFigure.setFigureLineInfo(figureInfo);


kaplanMeierFigure.savePNGKMNumRisk("/Users/Scooter/Downloads/test.png");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
