### ISSUE TITLE
Magic number in org.biojava.nbio.core.sequence.io.ABITrace#getImage

### ISSUE THREAD

**Issue by dylanyerly** [biojava/biojava#813]
Hello, in the method getImage in the class org.biojava.nbio.core.sequence.io.ABITrace the argument widthScale is not fully used where it should be.
There is a magic number (2) instead of widthScale.
Thanks in advance.

**Comment by josemduarte** [comment]
Are you referring to this line?: https://github.com/biojava/biojava/blob/fd4f8ef29c25d6329c903687c08d78c6c03a8a76/biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/ABITrace.java#L236

Could you perhaps provide a [pull request](https://help.github.com/articles/about-pull-requests/)?

**Comment by dylanyerly** [comment]
Yep sure, it's done.

**Comment by heuermh** [comment]
Fixed by #814
