### ISSUE TITLE
Kaplan-Meier - How to label axes and how to change the interval of numbers on the x-axis

### ISSUE THREAD

**Issue by betrw** [biojava/biojava#815]
How can I label the y- and the x-axis?
How can I change the interval of the numbers on the x-axis? One diagram shows the months 0, 37, 74, 111 and 148. I would prefer steps of 10.

**Comment by sbliven** [comment]
@betrw Adding a code snippet would help us answer better.

Axis legends are set like this:
```java
kaplanMeierFigure.getKMFigureInfo().xAxisLegend = "X AXIS";
```

Regarding the steps, the default is to show 5 labels. You can change the fraction of the data covered by each label:
```java
int numLabels = 10;
kaplanMeierFigure.getKMFigureInfo().xaxisPercentIncrement = 1./(numLabels-1);
```

You can also set labels specifically:

```java
ArrayList<Double> steps = new ArrayList<>();
for(double i=0;i<155;i+=10) {
	steps.add(i);
}
kaplanMeierFigure.getKMFigureInfo().xAxisLabels = steps;
```

**Comment by betrw** [comment]
Worked very well. Thanks.
