### ISSUE TITLE
How to do a Log Rank test with Hazard Ratio - Functions - CoxInfo, CoxR, CoxCoefficient

### ISSUE THREAD

**Issue by betrw** [biojava/biojava#826]
How can I do a Log Rank-Test with the Hazard Ratio of two groups? I get a bit confused how to use the classes CoxInfo, CoxR and CoxCoefficient.

Could you give me an example how to do a Log Rank test with the Hazard Ratio please?

**Comment by josemduarte** [comment]
Could you point us to what code exactly are you trying to use (biojava module, classes etc). Perhaps just post an excerpt of code of some things that you've tried?

**Comment by betrw** [comment]
Something like this:


`CoxInfo CI = new CoxInfo();
	CoxR R = new CoxR();
	ArrayList<SurvivalInfo>SurvInfo = new ArrayList<SurvivalInfo>();
	ArrayList<String>Variables = new ArrayList<String>(); // two groups
	
	
	for (int i = 0; i <= (int)first - 1; i++)
	{
	    SurvivalInfo si = new SurvivalInfo(GeneValues.get(i).SIS.OverallSurvival, GeneValues.get(i).SIS.IsCensored == true ? 0 : 1 );
	    BPSG.Group1Information.add(GeneValues.get(i).SIS);
	    SurvInfo.add(si);
	    Variables.add("Variable1");
           //For group 1
	}

	for (int i = (int)first ; i <= GeneValues.size() - 1; i++)
	{
	    SurvivalInfo si = new SurvivalInfo(GeneValues.get(i).SIS.OverallSurvival, GeneValues.get(i).SIS.IsCensored == true ? 0 : 1 );
	    BPSG.Group2Information.add(GeneValues.get(i).SIS);
	    SurvInfo.add(si);
	    Variables.add("Variable2");
           // for group 2
	}
	

	try
	{
	    CI = R.process(Variables, SurvInfo,false,false,false,false); //performing a Hazard Ratio based on 
                                                                                                     //two gorups and, Log Rank, p-value
                                                                                                     //simplified R.process(group1, group2)
	    BPSG.Result = CI;
	}
	catch (Exception e)
	{
	    // TODO Auto-generated catch block
	    e.printStackTrace();
	}`

return BPSG;

**Comment by willishf** [comment]
For Cox if you compare two groups you will get a very similar/the same HR
as log-rank with a slightly different p-value. I didn't see the
LogRank code checked in so need to go back to another computer that has the
code and figure out the dependencies and examples. I seem to recall the
LogRank code I used was modified from some other code that I found. I
didnt have time to sort through the licensing dynamics so didn't check in
with the survival code.

**Comment by betrw** [comment]
I try to understand the logic of the three classes. I would like to know how to use the classes.
Which methods do I have to call for two groups I would like to compare? Which class is needed to pass the survival data? The class 'CoxCoefficient' has all information I would like to have but how can I generate the information. Do I have to use 'CoxInfo' or 'CoxR'?

An example would be great.

**Comment by willishf** [comment]
Will need to get to another computer and can send you example code.

**Comment by betrw** [comment]
I had looked up the formula for the log-rank test, the hazard ratio, the 95% confidence interval and the p-value. I wrote an own class for calculating the values.

Nevertheless thank you very much.

**Comment by miaoyibo** [comment]
> How can I do a Log Rank-Test with the Hazard Ratio of two groups? I get a bit confused how to use the classes CoxInfo, CoxR and CoxCoefficient.
> 
> Could you give me an example how to do a Log Rank test with the Hazard Ratio please?

I have the same question,could you give me an example please?
