### ISSUE TITLE
producing an alignment file

### ISSUE THREAD

**Issue by rayoub** [biojava/biojava#827]
What is the best approach to producing a protein structure alignment file where 1 structure is represented as chain A and another is represented as chain B and the transformation matrix has been applied to the coordinates of the superimposed structure?

**Comment by josemduarte** [comment]
This part of the tutorial explains alignments in detail:

https://github.com/biojava/biojava-tutorial/blob/24ba882918116aa96fcebd98dd74082b83251268/structure/alignment.md#creating-alignments-programmatically

**Comment by lafita** [comment]
@rayoub the default when creating a structural alignment is to use a separate model for each structure in the alignment. If you need the two structures in the same model but with different chain identifiers you can do the alignment programatically (as @josemduarte pointed out) and combine the models into two different chains with a few extra lines of code.

**Comment by rayoub** [comment]
I applied a transformation matrix to coordinates of a superimposed structure, applied these back to the atoms in each group of a chain, and then used the toPDB() function to output lines of well-formed PDB ATOM records. The toPDB() function was helpful in this regard.
