### ISSUE TITLE
> How can I do a Log Rank-Test with the Hazard Ratio of two groups? I get a bit confused how to use the classes CoxInfo, CoxR and CoxCoefficient.

### ISSUE THREAD

**Issue by miaoyibo** [biojava/biojava#840]
> How can I do a Log Rank-Test with the Hazard Ratio of two groups? I get a bit confused how to use the classes CoxInfo, CoxR and CoxCoefficient.
> 
> Could you give me an example how to do a Log Rank test with the Hazard Ratio please?

I have the same question,could you give me an example please?

_Originally posted by @miaoyibo in https://github.com/biojava/biojava/issues/826#issuecomment-500358340_

**Comment by willishf** [comment]
If you look at CoxHelper.java the Main has an example where the returned
CoxInfo has all the relevant metrics. If you look at the source code you
should be able to do your own implementation of loading survival data from
a tab-delimited file. I went looking for the example data set used when I
wrote the original code and that was a few laptops ago and don't have that
specific data file. Let me know if you can't figure it out and will look
through the archives.

**Comment by miaoyibo** [comment]
I try it like this:
`public static void main(String[] args) throws Exception {
		ArrayList<SurvivalInfo> survivalInfoList = new ArrayList<SurvivalInfo>();
		int a = 0;
		double[] times= {1.800,2.300,3.800,5.500,6.300,6.400,16.600,17.100,23.800,33.700,33.700};
		int[] censor= {1,1,1,1,1,1,0,0,0,0,0};
		
		double[] times2= {2.800,3.000,4.300,4.500,5.800,6.800,7.800,8.200,8.200,9.200,9.200,10.800,
				11.000,15.900,18.100,21.400,22.100,23.000,26.900};
		int[] censor2= {1,1,1,1,1,1,0,0,0,1,1,0,0,1,0,0,1,0,0};
		for(int i=0;i<times.length;i++) {
			SurvivalInfo si = new SurvivalInfo(times[i], censor[i]);
			//si.setOrder(a);
			si.setOrder(i);
			si.addUnknownDataTypeVariable("STRATA", "1");
			survivalInfoList.add(si);
		}
		for(int i=0;i<times2.length;i++) {
			SurvivalInfo si = new SurvivalInfo(times2[i], censor2[i]);
			//si.setOrder(a+1);
			si.setOrder(i);
			si.addUnknownDataTypeVariable("STRATA", "2");
			survivalInfoList.add(si);
		}
		CoxR cox = new CoxR();
		ArrayList<String> variables = new ArrayList<String>();
		variables.add("STRATA");
		//variables.add("VALUE");
		CoxInfo ci = cox.process(variables, survivalInfoList, false, false,false, false);
		System.out.println(ci);
		System.out.println(ci.getScoreLogrankTestpvalue());

	}`
but  the result is slightly different from that obtained in other methods, i am not sure whether my demo is right.

**Comment by willishf** [comment]
What are you comparing against? You will see slight differences in
precision. The cox regression is a port of the R survival package.

If you do the KM figure I think that logrank code is from a slightly
different implementation that I ported.



If you do a KM figure

**Comment by miaoyibo** [comment]
ok  I got it,thank you very much
