### ISSUE TITLE
Accept contribution of biojava-adam module

### ISSUE THREAD

**Issue by heuermh** [biojava/biojava#842]
It has always been my goal to contribute the following repository to Biojava, either as a module in this repository, or a separate repository under the Biojava Github organization

https://github.com/heuermh/biojava-adam

Because of license incompatibilities (LGPL vs Apache 2, see e.g. #765), this code cannot be part of the [ADAM codebase](https://github.com/bigdatagenomics/adam) nor under the [Big Data Genomics Github organization](https://github.com/bigdatagenomics).

With regards to timing, `biojava-adam` still contains some snapshot dependencies, so perhaps any migration should wait until those are resolved.

**Comment by josemduarte** [comment]
I think it would be great to have it as a separate repo under the BioJava github organization. In principle with next BioJava release you will not have the SNAPSHOT dependency anymore and should be able to migrate it.

**Comment by heuermh** [comment]
Thank you, @josemduarte!

As a separate repository, should versioning still track Biojava (i.e. release in lock-step with same version number) or should we start anew, with an upcoming version 1.0 targeting Biojava 5.2.2 and ADAM 0.28.0 release versions?

**Comment by josemduarte** [comment]
> should we start anew, with an upcoming version 1.0 targeting Biojava 5.2.2 and ADAM 0.28.0 release versions?

I'd go for this strategy

**Comment by heuermh** [comment]
ADAM 0.28.0 has been released, so I can update the snapshot dependency and begin the migration and release process.  I think I'll start with version 0.1.0 rather than 1.0, since we're still not at 1.0 in ADAM, and as such aren't strictly following the SemVer guidelines yet.

**Comment by heuermh** [comment]
@josemduarte It appears that I don't have permissions to transfer the repository

> You don’t have the permission to create repositories on biojava 

Perhaps this is restricted to Owners in the BioJava organization.  Might you or another Owner be able to do the transfer?

**Comment by josemduarte** [comment]
I've just made you an owner, please try again

**Comment by heuermh** [comment]
Thank you, @josemduarte! I've completed the transfer.
