### ISSUE TITLE
Advance notice: next release 5.3.0

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#848]
It's been a while since last release. I'd propose to release 5.3.0 on the 6th of September. It will include some bug fixes, support for BinaryCif and a new mmCIF parser (see #839).

Make sure you commit any contributions that you'd like to see in 5.3.0 before that time.

Question for @JonStargaryen . Should we upgrade the dependency on ciftools-java to latest release 0.5.4?

**Comment by JonStargaryen** [comment]
@josemduarte Yeah, I recommend bumping the version to 0.5.4. It fixes a bug which can crash CIF writing when concurrency is involved. Moving to 0.5.4 doesn't require any changes in the BioJava.

**Comment by josemduarte** [comment]
Thanks @JonStargaryen , we'll do

**Comment by heuermh** [comment]
I don't see a milestone for 5.3.0, I would like to include #852 #851 in this release.  I'll also take a look at #843 to see if there is a quick fix.

**Comment by josemduarte** [comment]
> I don't see a milestone for 5.3.0, 

Sorry I didn't create the milestone. There were various outdated milestones that I had to clean up and move around. We'll be more diligent for next release.

> I would like to include #852 #851 in this release. 

Absolutely, I'll merge them when the tests pass. Thanks

>  I'll also take a look at #843 to see if there is a quick fix.

That'd be be great, thanks! If you need a bit more time, please let me know.

**Comment by josemduarte** [comment]
@heuermh would it be ok to postpone #843 to next bugfix release? If ok, I'll go ahead and release 5.3.0 today

**Comment by heuermh** [comment]
@josemduarte Yes, I don't have a quick fix for it.  Please go ahead with the release!
