### ISSUE TITLE
unable to access packages in Eclipse

### ISSUE THREAD

**Issue by mimiagurcia** [biojava/biojava#856]
Hello
I am learning to use Biojava 1.7.1  via Eclipse Version: 2019-09 R (4.13.0). 

    Downloaded the file from the link polaris.umuc.edu/~sgao/BIFS618/Homework/biojava-1.7.1_all_mod.jar 
, hit "OPEN with JDK library"
    Place file in some folder: I used C:\biojava
    Since I already have a path for Java
    Opened CMD
    Used cd and dir until I reached my folder:
        C:\>biojava\
    Then in the cmd I copy\pasted jar -xvf biojava-1.7.1_all_mod.jar and hit ENTER
        One of the Biojava files opened (I assume the one named biojava-1.7.1_all_mod)
    Moved decompressed folder into C:\biojava\biojava-1.7.1
Then typed: set classpath=%classpath%;.;c:\biojava\biojava-1.7.1\biojava-1.7.1.jar
Then setup the path in my system (This PC > properties...)
    Then went to Eclipse, created a week 10 project
        Right click > Properties > Java Build Path > Libraries > add External JARS Button and added the path to my folder
After all this, Eclipse does show the contents under "Referenced Libraries". But when I try to import any package to use them it says "The type xxxx is not accessible".

I even try to follow the instructions in biojava.org site (the ones about Maven and SVN). Any suggestions?

**Comment by heuermh** [comment]
Hello @mimiagurcia!

Biojava versions 1.x are maintained in the https://github.com/biojava/biojava-legacy repository.  You may want to [create a new issue in that repository](https://github.com/biojava/biojava-legacy/issues).

That said, I am not familiar with the file linked at `polaris.umuc.edu`, it is not an official Biojava release artifact.  It appears to be a zipped version of contents similar to a binary release, but I cannot guarantee so.

```
$ wget polaris.umuc.edu/~sgao/BIFS618/Homework/biojava-1.7.1_all_mod.jar
$ jar tvf biojava-1.7.1_all_mod.jar
$ cd biojava-1.7.1
$ ls
LICENSE                     biojava-1.7.1.jar           commons-pool-1.1.jar        junit-4.4.jar
LICENSE.COMMONS             build.xml                   demos                       manifest
README                      bytecode.jar                demos-1.7.1.jar             resources
README.biosql               commons-cli.jar             doc                         src
apps                        commons-collections-2.1.jar dtd                         tests
apps-1.7.1.jar              commons-dbcp-1.1.jar        jgrapht-jdk1.5.jar
```

You may be able to add those jars to your Eclipse project to fix your errors.

However, unless those artifacts are specifically required for "Homework" (guessing from the path), I would suggest using the most recent Biojava 1.x release (version 1.9.3) or the most recent Biojava release (version 5.3.0).

**Comment by mimiagurcia** [comment]
Hello
thank you for replying! I am new to both programming and GitHub. Sorry I did not know of the other github, thank you for the link. 
And yes, is for a introduction to Java Class. I finally got it to work, however I tried so many things I'm not sure which one did the trick.
