### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by accismus** [biojava/biojava#863]
Hi all,

I'm a bioinformaticist turned technical writer, and I'm working on a new open source technical documentation framework called Accismus. I'm trying to gauge what the interest in something like that might be. I'm planning the framework so no knowledge of HTML is necessary, you can do everything in plain text, and the resulting pages meet accessibility standards. Would this be something BioJava could use?

To be clear, I am NOT asking for money. I do plan to launch a Kickstarter campaign eventually, but for now, I just want to know if the whole thing would actually help anybody. There's no reason to try and build something that won't be of any use, after all.

I'd appreciate any opinions you might have; thanks!

**Comment by accismus** [comment]
My apologies, I realized after posting this that it might be considered soliciting. That was not my intention; I was just trying to gauge interest. Please disregard this post.

**Comment by heuermh** [comment]
Hello @accismus!

As Phil Ewels mentions in a recent talk, there are a lot of options in the project documentation space
https://twitter.com/tallphil/status/1233062875012501504

The BioJava site currently uses Jekyll and is hosted at
https://github.com/biojava/biojava.github.io

That doesn't mean we're not open to suggestions or pull requests ;)

**Comment by accismus** [comment]
Hi, thanks for not minding the opened issue. Accismus is going to be
dynamic, searchable, and able to meet accessibility standards. Can your
current solution do that too?
