### ISSUE TITLE
AltAligComparator logic

### ISSUE THREAD

**Issue by automenta** [biojava/biojava#864]
Contains a repeat inequality condition:

https://github.com/biojava/biojava/blob/18f57de72a271ae5cbff6f586ee83831089f54fd/biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/AltAligComparator.java#L61

Proposed fix: use Double.compare:

https://github.com/automenta/biojava/blob/master/biojava-structure/src/main/java/org/biojava/nbio/structure/align/pairwise/AltAligComparator.java#L57

```
			double rms1 = a.getRmsd();
			double rms2 = b.getRmsd();
			return Double.compare(rms1, rms2);
```

**Comment by josemduarte** [comment]
Good catch, thanks! Could you submit a pull request?

**Comment by josemduarte** [comment]
@MaxGreil this is a very easy fix and described above. Could you look into it?
