### ISSUE TITLE
Roadmap for 6.0.0

### ISSUE THREAD

**Issue by josemduarte** [biojava/biojava#879]
A rough roadmap for 6.0.0. All input is welcomed.

- Drop java-8 compatibility. First java-11 release [optional, depends on timing and community needs]
- Drop dependency on legacy RCSB PDB services, e.g. source.rcsb.org. Remove code that uses the dependencies.
- Remove BioJava's own mmCIF parser, making the ciftools-java parser the default one (code already in since 5.3.0). Drop all unneeded code.
- Full support for branched entities in structure module (related to PDB carbohydrate remediation appearing in July 2020)
- More clean up of error handling. Throw early, catch late.
- More clean up of tests: reduce external resources need at test time

Process improvements
- Use SonarQube to measure coverage and quality. Hook it up in CI for pull requests (see #561 )

**Comment by sbliven** [comment]
Is java-8 compatibility a burden? Although the Oracle JDK isn't being updated, it's not officially end-of-life until 2022 ([roadmap](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)).

**Comment by josemduarte** [comment]
I don't oppose keeping java-8 compatibility for 6.0.0. We could drop java-8 in version 6.1 or 7.0

Any opinions?

**Comment by sbliven** [comment]
ciftools-java seems to be using 11 by default. Maybe that's reason enough to move up.

**Comment by sbliven** [comment]
How are we doing with the 6.0.0 release? 5.4.0 is currently broken due to the legacy RCSB  services, so we don't have a stable released that passes tests. Can we push out a 6.0.0 quickly?

**Comment by josemduarte** [comment]
Yes I was also concerned about that... I wanted to push an alpha 6.0.0 release ASAP. Later today I'll merge #912 and then I'll tag `6.0.0-alpha1`.

**Comment by heuermh** [comment]
There are a lot of open issues tagged with [Milestone 6.0.0](https://github.com/biojava/biojava/milestone/9) and even a bunch still on [Milestone 5.3.1](https://github.com/biojava/biojava/milestone/8).  Can we triage these with an eye to making binary incompatible changes now for 6.0.0 and moving others to new 5.4.1/5.5.0 and 6.0.0/6.1.0 milestones?

**Comment by josemduarte** [comment]
Good point. Let's try to do some updating and triaging as soon as possible.

**Comment by heuermh** [comment]
I've taken a look and updated/closed a few things.

**Comment by josemduarte** [comment]
FYI I'm working on releasing the first alpha since yesterday, but I'm having trouble with the upload to maven. I need to do some refreshing of the pom, will likely submit a PR.

**Comment by josemduarte** [comment]
I've now released 6.0.0-alpha2 (alpha1 was a test).

**Comment by aalhossary** [comment]
Will we support long PDB IDs in version 6.0?
I am still working on it.

**Comment by josemduarte** [comment]
Long PDB ids are not that urgent. I think it would be more urgent to release 6.0.0. For that, we only need worrying about breaking changes and removals. I suppose long PDB ids are not a breaking change, so they wouldn't be that urgent.

**Comment by aalhossary** [comment]
My changes are Breaking ones with some removals. :)
Anyway, my previous comment was 11 days ago and I already did and submitted a pull request. Spencer's comments should be addressed tonight, insha' Allah.

**Comment by josemduarte** [comment]
I will release the final 6.0.0 later today. After that I'll clean up the milestones and bump them up to next version if they are still valid.

**Comment by josemduarte** [comment]
Now released!
