### ISSUE TITLE
Override packaged log4j2.xml

### ISSUE THREAD

**Issue by rayoub** [biojava/biojava#883]
Using the maven-assembly-plugin to create a single jar with dependencies, I'm unable to create my own log4j2.xml file with a log level of "error" since the log4j2.xml file included from biojava cannot be overwritten from what I can tell. What is the simplest way to raise the default log level to "error" when using biojava?

Thanks.

**Comment by josemduarte** [comment]
I believe you can override the log4j2 configuration at runtime passing this to the java command line:
```
java -Dlog4j.configurationFile=/path/to/my/file/log4j2.xml ...
```

**Comment by rayoub** [comment]
This works for me. I was hoping to find a way to do this in the maven pom but alas I have given up on that. This is sufficient. Thanks for help.
