### ISSUE TITLE
Question: assignment of the alpha helices

### ISSUE THREAD

**Issue by Domino2357** [biojava/biojava#887]
Hey folks!

First of all, your software has been incredibly helpful for us to parse the files and to handle the calculations of secondary structures. Thank you very much!
I do have a small question: when calculating the ss, I realized that sometimes alpha helices are not visualized in the 3D-Viewer of the rscb.org. I have attached the example of “3nir”. There is a short alpha helix which is not represented as such in the viewer, but the DSSP from BioJava assigns it. Is this due to its length, i.e. are only alpha helices visualized if they are long enough, or am I getting something wrong here?

![ambigiousHelix](https://user-images.githubusercontent.com/45595982/92977983-c5d7a980-f48e-11ea-8e59-b8e3e0b4e688.png)

**Comment by lafita** [comment]
Hi @Domino2357 there are still some differences between the original DSSP and the implementation in BioJava, see #627 
Although they are generally minor and affect borderline assignments, but it might be useful to be aware of it. Hope this helps!

**Comment by Domino2357** [comment]
It does help, thank you!

**Comment by sbliven** [comment]
I don't think this is even a DSSP issue. I tried DSSP at https://www3.cmbi.umcn.nl/xssp/ and it assigned both helices. It looks like the authors chose not to assign the second helix (there is only one HELIX record in the PDB file)
