### ISSUE TITLE
Question: Protein to DNA

### ISSUE THREAD

**Issue by dami-gingko-app** [biojava/biojava#888]
Really sorry to post this here, but am on a deadline. I cannot find a mechanism to convert a protein sequence to DNA. Is there a way to do so please in Biojava 5?

**Comment by foreveremain** [comment]
not sure if biojava has a tool that does this - but you could use: http://www.bioinformatics.org/sms2/rev_trans.html

**Comment by dami-gingko-app** [comment]
Oh dear.... I am writing a program, so may need to hand write a translator, thanks!

**Comment by foreveremain** [comment]
Unless you care about *optimising* the coding for the protein this is quite trivial - first look at the code that does it the other way ( https://biojava.org/wiki/BioJava%3ACookbook%3ATranslation ) and then pick the first codon for each amino acid in the protein sequence ;)

**Comment by dami-gingko-app** [comment]
DNATools is in legacy biojava, and I don't seem to be able to download it. Let me figure out the current implementation.

**Comment by dami-gingko-app** [comment]
Do you have the code/jar for Biojava 1.9 please? It would be an enormous help.

**Comment by dami-gingko-app** [comment]
It's ok, I found 1.9

**Comment by heuermh** [comment]
For reference, the 1.x version of biojava is still actively maintained at https://github.com/biojava/biojava-legacy.

The latest release version is 1.9.3, e.g. for Maven
```
<dependency>
  <groupId>org.biojava</groupId>
  <artifactId>core</artifactId>
  <version>1.9.3</version>
</dependency>
```

**Comment by sbliven** [comment]
Note that the reverse translation will be useless for aligning to real DNA since it will use different codons.
