### ISSUE TITLE
DNA Alignment k

### ISSUE THREAD

**Issue by rgb4268** [biojava/biojava#889]
I know this is a question, but is there a way to align a DNA sequence to a protein? Can we get the location of the sequence on the protein?

**Comment by josemduarte** [comment]
How about by translating DNA to protein and then doing a local alignment? Translating is quite easy, see #888 . Regarding alignments, see the relevant part of the tutorial: https://github.com/biojava/biojava-tutorial/blob/master/alignment/README.md
