### ISSUE TITLE
Proteomics classes (from biojava-legacy) implemented in biojava

### ISSUE THREAD

**Issue by nnalpas** [biojava/biojava#895]
Hi all,

I was wondering if the proteomics classes (from biojava-legacy) have been transferred to the current biojava?

Thanks,

**Comment by josemduarte** [comment]
I'm going to say they weren't transferred from biojava-legacy. But I'm not sure which classes exactly you are referring to. Do you happen to know some class names or package names as pointers?

**Comment by nnalpas** [comment]
Hi,
I was particularly interested in the digest class.
Do you know if there are plans to re-include in the future?
If not I wouldn't mind trying to re-implement myself.

**Comment by josemduarte** [comment]
Alright, found it now thanks. This is the whole proteomics package in legacy: https://github.com/biojava/biojava-legacy/tree/33bedd56d3c0c321748f16073ec2307b745db745/core/src/main/java/org/biojava/bio/proteomics

I don't think there was anyone working on re-including it. But definitely it would be a great contribution, happy to get new Pull Requests!

I think it even deserves a new module: biojava-proteomics

**Comment by heuermh** [comment]
That said, if the classes in legacy work fine for you, there isn't any reason not to use them.  Biojava-legacy is maintained, and can co-exist with Biojava proper, as the package names were changed.

**Comment by nnalpas** [comment]
Yes you are correct, but I also wanted to introduce some additional features.
I will have look and see how much work it is though and then do a pull request.
Thanks again.
