### ISSUE TITLE
testDSSPParser fails in nbio/structure/secstruc/TestDSSPParser

### ISSUE THREAD

**Issue by Shilpa-Rani** [biojava/biojava#896]
The above test deterministically fails due to the commits made after 129a0a1dd0fe2e8daac2b19748e707bcbfd3978d.

**Comment by josemduarte** [comment]
Good catch, thanks!

I think this is due to the RCSB PDB having deprecated the dssp file service (i.e. URLs like http://files.rcsb.org/dssp/pt/5pti/5pti.dssp.gz). The solution will be removing the `DSSPParser.fetch()` method for the upcoming 6.0.0 release.

I'll work on a PR for this.
