### ISSUE TITLE
TestHardBioUnits#test4A1I fails when parsing BinaryCIF

### ISSUE THREAD

**Issue by JonStargaryen** [biojava/biojava#914]
- test passes on CIF but fails on BinaryCIF
- 6th or higher decimal place of coordinates differ between CIF and BinaryCIF - somehow that causes completely wrong results

See discussion in #912.

**Comment by josemduarte** [comment]
This is likely a bug in SuperpositionQCP. It'd be good to have a unit test that can reliably reproduce the issue.

**Comment by JonStargaryen** [comment]
Increasing the precision threshold in QCP can fix address this as it will trigger additional iterations for small eigenvectors. See:
https://github.com/biojava/biojava/blob/3b1f1beb48123cfec002fcdaeaa7c1bff79c7f24/biojava-structure/src/main/java/org/biojava/nbio/structure/geometry/SuperPositionQCP.java#L495

I'm not sure about the implications of changing that value. I've checked other tests that call `SuperpositionQCP` and, after changing the value, the branch is only executed by `TestHardBioUnits#test4A1I`.

**Comment by pwrose** [comment]
You may want to ask the original author Douglas Theobald (
dtheobald@brandeis.edu) about this case.

**Comment by JonStargaryen** [comment]
> You may want to ask the original author Douglas Theobald ( dtheobald@brandeis.edu) about this case. .

Good suggestion @pwrose. I've reached out, let's see if I hear back on the issue.
