### ISSUE TITLE
BondMaker - Could not find atoms specified in SSBOND record

### ISSUE THREAD

**Issue by zedomel** [biojava/biojava#929]
Hi, 

I'm getting the follow warning when reading a PDB file:
<pre>
[main] WARN  org.biojava.nbio.structure.io.BondMaker - Could not find atoms specified in SSBOND record: [SSBOND:
Atom 1:
	Chain: I
	Residue #: 24
	Ins. Code: 
Atom 2:
	Chain: I
	Residue #: 56
	Ins. Code: 
]
</pre>

Looking at the code it seems that `PDBFileParser::triggerEndFileChecks` is being called before `PDBFileParser::formBonds`. The method `triggerEndFileChecks` calls `assignAsymIds` which changes the ID's of the chains and, then the method `BondMaker::formDisulfideBonds` can't find the chains of the SSBonds, since it has changed by `assignAsymIds`.

I will try to do a pull request to fix it, but before I need to know what is the best approach to fix it.

thanks.

**Comment by josemduarte** [comment]
Thanks for the report @zedomel . First of all one important point: I think this feature works well when reading from mmCIF files. If you are dealing with PDB-deposited files, then I would strongly recommend to use mmCIF. It has been the main format for many years now, whilst the PDB format is considered legacy. Also most software packages for structure solution will output in mmCIF format.

In any case, regarding the bug you report, I think the best strategy would be to write a small unit test that demonstrates the issue. Then it should be pretty straight forward to fix. The problem sounds like a confusion with asym_ids and author chain ids. In PDB files there's only 1 identifier per chain (the author chain id).

**Comment by erikedlund** [comment]
I'm running into a variant of this bug loading structure 1A4W from a .pdb with `FileParsingParams.setCreateAtomBonds(true)`

It results in a NullPointerException preventing parsing. Looks like the SSBondImpl gets an author chain ID, while the BondMaker class is looking for an asym_id in `getAtomFromRecord()`


> java.lang.NullPointerException
> 	at org.biojava.nbio.structure.io.BondMaker.getAtomFromRecord(BondMaker.java:475)
> 	at org.biojava.nbio.structure.io.BondMaker.formDisulfideBond(BondMaker.java:298)
> 	at org.biojava.nbio.structure.io.BondMaker.formDisulfideBonds(BondMaker.java:292)
> 	at org.biojava.nbio.structure.io.PDBFileParser.formBonds(PDBFileParser.java:2778)
> 	at org.biojava.nbio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2700)
> 	at org.biojava.nbio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2557)

**Comment by josemduarte** [comment]
Thanks @erikedlund . Actually this is related to a bug that was recently fixed (see #943 and #961 ). It seems that ssbonds are not treated correctly yet. I'll look into it.

**Comment by josemduarte** [comment]
In any case, again I'll reiterate that this yet another PDB parser bug, that is not present in mmCIF parser. PDB-format files are legacy and going forward support for them will be waning. 

If you are dealing with PDB-deposited structures, then please switch to mmCIF or BinaryCIF.

**Comment by josemduarte** [comment]
Now fixed. I'll create a new 6.0.0-alpha release as soon as possible, which will include this fix.

**Comment by josemduarte** [comment]
`6.0.0-alpha7` is out, which includes this fix. In any case, we hope to have the official 6.0.0 out soon.
