### ISSUE TITLE
URLConnection to invalid HTTP URL is not detected as a failure

### ISSUE THREAD

**Issue by aalhossary** [biojava/biojava#933]
TestDownloadChemCompProvider.testIfWeCachedGarbageWeCanDetectIt() still fails to detect when the target URL is invalid or the file has no contents. Instead of deleting the local cache file, a 20 bytes file (effectively an empty one) is saved.
Related to #703

**Comment by josemduarte** [comment]
Thanks @aalhossary . Actually I noticed this and fixed it in master a few days ago. Are you in latest master?

**Comment by aalhossary** [comment]
Yes I am. I noticed it when I was running the tests to building a jar before sumitting another fix.

To fix it I added a flag that will be true only if a file could be actually read.
I will create a PR soon.

Amr
