### ISSUE TITLE
Compilation errors on classes CRC64ChecksumTest, FlatFileCacheTest

### ISSUE THREAD

**Issue by jlerbsc** [biojava/biojava#963]
It seems there is compilation errors on the lastest version. Can you reproduce these errors? What is the java version to use with this project?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project biojava-core: Compilation failure: Compilation failure: 
[ERROR] /D:/dev/projects/biojava/biojava-core/src/test/java/org/biojava/nbio/core/util/CRC64ChecksumTest.java:[74,14] no suitable method found for update(byte[])
[ERROR]     method org.biojava.nbio.core.util.CRC64Checksum.update(int) is not applicable
[ERROR]       (argument mismatch; byte[] cannot be converted to int)
[ERROR]     method org.biojava.nbio.core.util.CRC64Checksum.update(java.lang.String) is not applicable
[ERROR]       (argument mismatch; byte[] cannot be converted to java.lang.String)
[ERROR] /D:/dev/projects/biojava/biojava-core/src/test/java/org/biojava/nbio/core/util/FlatFileCacheTest.java:[28,31] cannot find symbol
[ERROR]   symbol:   method of(java.lang.String)
[ERROR]   location: interface java.nio.file.Path
[ERROR] /D:/dev/projects/biojava/biojava-core/src/test/java/org/biojava/nbio/core/util/FlatFileCacheTest.java:[69,31] cannot find symbol
[ERROR]   symbol:   method of(java.lang.String)
[ERROR]   location: interface java.nio.file.Path
[ERROR] /D:/dev/projects/biojava/biojava-core/src/test/java/org/biojava/nbio/core/util/XMLHelperTest.java:[71,25] cannot find symbol
[ERROR]   symbol:   method of(java.lang.String)
[ERROR]   location: interface java.nio.file.Path

**Comment by jlerbsc** [comment]
It seems that with java 11 there is no compilation errors but there are test failures.

**Comment by josemduarte** [comment]
I've just built and run all tests with java 11 and did not get any test failures.

In PR #959 a test that did not work on java 8 was removed (CRC64ChecksumTest). When that is merged, it should build and test correctly both on 8 and 11.

**Comment by josemduarte** [comment]
This is fixed in master now.
