### ISSUE TITLE
ParseGO demo application doesn't work

### ISSUE THREAD

**Issue by richarda23** [biojava/biojava#964]
Initially this doesn't work as the URL
`http://sourceforge.net/p/song/svn/HEAD/tree/trunk/subsets/biosapiens.obo?format=raw` is redirected to https. So  changing the URL to https will fix this. 
Using a logger to show output is also broken - no output is actually printed to the console. For a simple main application, would it be more robust to use System.out.println statements to ensure some output is shown?
Will raise a PR to fix the URL.
Looking at the SF project it's not been touched for 6 years - is there a newer active repository for this?

**Comment by josemduarte** [comment]
I do agree that demo applications are better off with simple System.out/err.print statements. Logging is not guaranteed to be set up properly in an end-user environment.
