### ISSUE TITLE
Main methods in classes are untested and some no longer work

### ISSUE THREAD

**Issue by richarda23** [biojava/biojava#966]
Many classes have main methods. E.g. here is a listing of those in core project:
```
grep -r 'public static void main' . 
./src/main/java/org/biojava/nbio/core/util/UncompressInputStream.java:	public static void main(String[] args) throws Exception {
./src/main/java/org/biojava/nbio/core/util/FileDownloadUtils.java:	public static void main(String[] args) {
./src/main/java/org/biojava/nbio/core/sequence/location/InsdcParser.java:	public static void main(String[] args){
./src/main/java/org/biojava/nbio/core/sequence/loader/GenbankProxySequenceReader.java:	public static void main(String[] args) throws Throwable {
./src/main/java/org/biojava/nbio/core/sequence/loader/UniprotProxySequenceReader.java:	public static void main(String[] args) {
./src/main/java/org/biojava/nbio/core/sequence/DNASequence.java:	public static void main(String[] args) throws Exception {
./src/main/java/org/biojava/nbio/core/sequence/io/FastaReaderHelper.java:	public static void main(String[] args) throws Exception {
./src/main/java/org/biojava/nbio/core/sequence/io/GenbankReaderHelper.java:	public static void main(String[] args) throws Exception {
./src/main/java/org/biojava/nbio/core/sequence/io/GenericFastaHeaderParser.java:	public static void main(String[] args) {
./src/main/java/org/biojava/nbio/core/sequence/io/FastaGeneWriter.java:	public static void main(String[] args) {
./src/main/java/org/biojava/nbio/core/sequence/io/GenbankWriter.java:	 * public static void main(String[] args) { try { FileInputStream is = new
./src/main/java/org/biojava/nbio/core/sequence/io/FastaWriter.java:	public static void main(String[] args) {
./src/main/java/org/biojava/nbio/core/sequence/io/FastaReader.java:	public static void main(String[] args) {
./src/main/java/org/biojava/nbio/core/sequence/io/CasePreservingProteinSequenceCreator.java:	public static void main(String[] args) throws Exception {
./src/main/java/org/biojava/nbio/core/sequence/ProteinSequence.java:	public static void main(String[] args) throws Exception {
./src/main/java/demo/ParseFastaFileDemo.java:	public static void main(String[] args) throws Exception {
./src/main/java/demo/DemoSixFrameTranslation.java:	public static void main(String[] args){
```
These may be to help users run the code, to get started, as a basic quick and dirty CLI tool or simply a test that the code works. it's not really clear what is the purpose. 

Some of these don't run. For example `FastaReader` expects a hardcoded file '/Users/Scooter/scripps/dyadic/c1-454Scaffolds.faa'
which clearly won't run anywhere except that person's own machine.

Other failures involve 400 errors when requesting a non-existent URL
It would be good to
1) Decide which of these main methods to  keep/maintain
2) Fix broken main methods
3) Run them regularly to test for regressions 

Re 3) I  will raise a PR with a possible solution that could be run automatically,  for discussion.

**Comment by josemduarte** [comment]
I think many of those main methods are tests used for debugging or quick and dirty CLIs. My opinion is that those should be removed. 

Any main method that is there for the purpose of demoing a functionality could stay, or even better be transferred to the demo package, which is the preferred BioJava convention.

**Comment by richarda23** [comment]
Sorry for the delay on this, was working on another project.

Will raise a PR based on these  proposed actions. For main classes that may be useful as tests i will write junits for them if one doesn't already exist.

class, proposed action, reason

FileDownloadUtils,remove,hardcodedfiles and  doesn't work
InsdcParser,remove or rewrite as junit,is test only
GenbankProxySequenceReader,remove,doesn't work
UniprotProxySequenceReader,remove,doesn't work -accession number is invalid
UncompressImputStream,todemos,maybe useful
DNASequence,remove,is test only/ no real use
FastaReaderHelper,remove, does nothing useful and doesn't work
GenbankReaderHelper,remove, does nothing useful and covered by existing demos
GenericFastaHeaderParser,remove or rewrite as junit,seems mainly test code
FastaGeneWriter,remove or rewrite as test,seems mainly for testing
GenbankWriter,remove,is commented out
FastaWriter,remove,uses hard coded files on a personal path
FastaReader,remove,doesn't work and unclear purpose
CasePreservingProteinSequenceCreator,remove or rewrite as test
ProteinSequence,remove or rewrite as test, may be useful as test code
