### ISSUE TITLE
SCOP files < 2.08 not available for download

### ISSUE THREAD

**Issue by aalhossary** [biojava/biojava#969]
the web folder [https://scop.berkeley.edu/downloads/parse/](https://scop.berkeley.edu/downloads/parse/) contains files of version 2.08 only.

All previous files are no longer available.

**Comment by jmchandonia** [comment]
Sorry, that was an error on my part in releasing SCOPe 2.08.  All the downloadable files for previous releases are now available again.  We're still working on generating ASTRAL sequences and subsets for 2.08, so those will be available soon.

**Comment by josemduarte** [comment]
Thanks for the info @jmchandonia  

In any case, changing the default to 2.0.8 ( #972) is still a good idea, thanks @aalhossary .
