### ISSUE TITLE
Switching to ciftools-java 3.0.0

### ISSUE THREAD

**Issue by pgrt** [biojava/biojava#986]
Hello,

I am working on the Debian packaging of biojava 5.4.0 : I wrote the enclosed patch to depend on ciftools-java 3.0.0 instead of the version your code is written for. I am proposing the patch in case you would like to upgrade the dependency.

[adapting_to_ciftools-java3.txt](https://github.com/biojava/biojava/files/7424199/adapting_to_ciftools-java3.txt)

Best,
Pierre

**Comment by josemduarte** [comment]
Fixed in 6.0.0 release (now out)
