### ISSUE TITLE
Wrong dependencies version in a sub-pom of biojava 5.4.0

### ISSUE THREAD

**Issue by pgrt** [biojava/biojava#987]
Hello,

In one of the poms of biojava 5.4.0, the versions of the dependencies are wrong. The attached patch corrects this.

[wrong_version_in_dependency.txt](https://github.com/biojava/biojava/files/7424221/wrong_version_in_dependency.txt)

Best,
Pierre

**Comment by josemduarte** [comment]
Now fixed in master. It will be out in 6.0.0 to be released later today.
