### ISSUE TITLE
Switching to jgrapht 1.5.1

### ISSUE THREAD

**Issue by pgrt** [biojava/biojava#988]
Hello,

While packaging biojava 5.4.0 for Debian, I used jgrapht 1.5.1. If you would like to upgrade the dependency of biojava to jgrapht 1.5.1, the enclosed patch should be useful to you.

[adapting_to_jgrapht1.5.1.txt](https://github.com/biojava/biojava/files/7424228/adapting_to_jgrapht1.5.1.txt)

Best,
Pierre

**Comment by josemduarte** [comment]
Ok it turns out it was quite straight forward. Now upgraded. The change will be out in 6.0.0 later today.
