### ISSUE TITLE
CONECT records multiplied when parsing structures

### ISSUE THREAD

**Issue by erikedlund** [biojava/biojava#990]
Hello,

I've noticed an issue where parsed Structure objects aren't consistently creating CONECT records when exported to PDB format. This appears to be a regression since version 4.2.8. Here's an example with RCSB's 4HHB. 

I'd expect these counts to match, but they appear to be multiplied.

[4hhb.pdb.txt](https://github.com/biojava/biojava/files/7437551/4hhb.pdb.txt)

```
PDBFileParser parser = new PDBFileParser();
FileParsingParameters params = new FileParsingParameters();
params.setCreateAtomBonds(true); // should create the bonds we want
parser.setFileParsingParameters(params);
String txt = Files.readString(new File("4hhb.pdb.txt");
System.out.println(String.format("File %s contains %s CONECT records: ", struct.getName(), txt.split("CONECT").length - 1));
Structure s = parser.parsePDBFile(new FileInputStream(struct));
String parsed = s.toPDB();
System.out.println(String.format("Parsed structure contains %s CONECT records: ", parsed.split("CONECT").length - 1));
```

`File 4hhb.pdb.txt contains 180 CONECT records: 
Parsed structure contains 9408 CONECT records: 
`

edit: fixing counts

**Comment by aalhossary** [comment]
@erikedlund if you don't have more comments, may you close this issue please?
